### ISSUE TITLE
Trailers render as purple & black cubes

### ISSUE THREAD

**Issue by WenXin20** [MrCrayfish/MrCrayfishVehicleMod#103]
Forge v14.23.5.2810-1.12.2
Vehicle v0.36.1

Here's what I know:
- All trailers render as purple and black cubes, but the Vehicle Trailer, bikes, planes, and cars render normally.
- The Vehicle Crates also renders as purple and black cubes when placed. 
- The Seeder and Fertilizer Trailer's inventories can be opened, but the storage trailer cannot be opened. 
- I can still interact with the tow bars, although they are invisible. 
- Only the wheels and any tow hooks (Storage Trailer) render.
- I can pick up all vehicles, but they render invisible. 
- Nothing is printed in the logs when they are placed.
- Waila can't see these trailers.

![2019-03-01_17 03 45](https://user-images.githubusercontent.com/12000593/53671485-2e13c100-3c44-11e9-8348-1ec0b7d6c305.png)
- Top left: Storage Trailer
- Top middle: Seeder
- Top right: Fertilizer
- Bottom middle: Vehicle Crate as it is opening.

**Comment by MrCrayfish** [comment]
Usually when missing models occur, it will print an error in the logs. Can you send me your startup logs?

**Comment by WenXin20** [comment]
Here is the [log](https://gist.github.com/WenXin20/df5b2b014ad385e16eaf5cebc573c8f8).

**Comment by MrCrayfish** [comment]
Can you try manually reloading resources? F3 + T when in game. Does it show the trailers after that?

**Comment by WenXin20** [comment]
I'll see what I can do, but I have a big modpack, so it takes a long time for it to reload resources. I suspect though that it's another mod's interaction causing problems with it.

**Comment by WenXin20** [comment]
I finally found out that the render glitches are caused by the mod [Baublelicious](https://minecraft.curseforge.com/projects/baublelicious).
