### ISSUE TITLE
Kart, Bath and Electric Vehicle glitch

### ISSUE THREAD

**Issue by RenanVieira88** [MrCrayfish/MrCrayfishVehicleMod#104]
Kart, Bath and Electric Vehicle don't render at server, single works fine

forge-1.12.2-14.23.5.2810
Vehicle: 0.36.1

**Comment by MrCrayfish** [comment]
What?

**Comment by RenanVieira88** [comment]
Kart, Bath and Electric vehicle on server missing body model, kart only remains wheel, steering wheel and motor for example
If u like I can send a picture together.
I've testing with version 0.36.1 on curse site and testing cloning your project on github, in both has the same error.

Sorry for my grammatical errors, English isn't my native language

**Comment by MrCrayfish** [comment]
Does the server have the Furniture Mod installed?

**Comment by RenanVieira88** [comment]
Yes, sofacopter for exemple render normally

Em Seg, 4 de mar de 2019 13:32, MrCrayfish <notifications@github.com>
escreveu:

**Comment by RenanVieira88** [comment]
![54](https://user-images.githubusercontent.com/24437327/53762269-64e91180-3ea6-11e9-8112-65377a34a4fa.png)

**Comment by RenanVieira88** [comment]
Still happens on "vehicle-mod-0.37.0-1.12.2"

**Comment by MrCrayfish** [comment]
Do you have any other mods installed? This is not a simple fix because literally the go kart and atv are item renderers. Please provide more details!

**Comment by RenanVieira88** [comment]
I made more tests and found the problem, it's the mod CTM required for Chisel mod

**Comment by RenanVieira88** [comment]
Hi MrCrayfish, I'm talking to devs from chisel and he's says that a problem by your side... I don't know what I can do to help

**Comment by dragonshardz** [comment]
> 
> 
> Hi MrCrayfish, I'm talking to devs from chisel and he's says that a problem by your side... I don't know what I can do to help

You could paste here what the Chisel dev said to you? I am also having this same issue where many of the models are invisible with Vehicles 0.36.0 and CTM 0.3.3.22

**Comment by dragonshardz** [comment]
On the server I am running, the Speedboat, Off-roader, Sport Plane, and Smart Car body models don't render. All other vehicles do.

**Comment by RenanVieira88** [comment]
Sorry, I'm didn't see your message, he only says that isn't he fault, to check with MrCrayfish why he using model as item... I'm talking to him in discord channel btw

**Comment by RenanVieira88** [comment]
Hi, MrCrayfish, after so many test I've found the problem, is the textures, CTM try manege textures when they do this yours models go away... Anvil Base, Stone and other texture I dont recall now... anyway, iv' create a resooucepack and works fine
tnks anyway
