### ISSUE TITLE
Weird behavior when Control is your crouch key.

### ISSUE THREAD

**Issue by NoxyNixie** [MrCrayfish/MrCrayfishVehicleMod#108]
I generally play with Control being my crouch key as opposed to Shift and this causes some weird behavior with in vehicle coupling and decoupling.

Each time I dismount the trailers are being unhooked (or hooked if they weren't hooked).

Apparantly https://github.com/MrCrayfish/MrCrayfishVehicleMod/blob/master/src/main/java/com/mrcrayfish/vehicle/client/ClientEvents.java#L495 will trigger by just dismounting even though the event is clearly onJump.

It would be nice if the "Control" key could be configured here (or perhaps use the sprint key) so that odd key configuration like mine would work without unexpected unhooking.

**Comment by MrCrayfish** [comment]
Ignore the method name, I forgot to change it. The event is a KeyInputEvent and simply checks if Ctrl is pressed down. I will add a keybinding soon.

**Comment by MrCrayfish** [comment]
I've changed this now to use whatever you configure your sprint key to be. A released should be coming soon!
