### ISSUE TITLE
Sports Plane Vanished

### ISSUE THREAD

**Issue by sachamaoi** [MrCrayfish/MrCrayfishVehicleMod#110]
Sports plane just vanished while flying them on a server randomly. First happened on V0.36. I tried updating the mod to V0.37 but it still happens.. And I only got this when it disappears. 

> [13:35:34] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Sports Plane moved wrongly!
> [13:35:34] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Sports Plane moved wrongly!
> [13:35:34] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Sports Plane moved wrongly!
> [13:35:34] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Sports Plane moved wrongly!
> [13:35:34] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Sports Plane moved wrongly!
> [13:35:34] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Sports Plane moved wrongly!
> [13:35:34] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Sports Plane moved wrongly!
> [13:35:34] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Sports Plane moved wrongly!
> [13:35:34] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Sports Plane moved wrongly!
> [13:35:35] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Nataschaa moved too quickly! 19.483183438545893,-0.7239764116066567,5.6987102857165155

**Comment by MrCrayfish** [comment]
Sports Planes travel fast and in general, Minecraft doesn't like fast entities. On server, depending on your connection, they can behave strangely compared to singleplayer. Turning on allow-flying in your server.properties might help. Otherwise this can't be fixed.
