### ISSUE TITLE
dependencies for the mod saying i dont have obduscate

### ISSUE THREAD

**Issue by xXBigRigXx** [MrCrayfish/MrCrayfishVehicleMod#111]
I have been trying to download this mod and the furniture mod for 3 days now can i was happy to finally get it but when i opened the game it says "You must include the right dependencies for MrCrayfish's Vehicle mod: requires obfuscate 0.2.5 or above (missing)" even though i have 0.3.0 version downloaded. is there anyone that perhaps can help me?
![Uploading help please.
![Uploading help please.
![help please](https://user-images.githubusercontent.com/48845979/54876124-764a8b80-4e5e-11e9-99e8-7f8ecdd66a1e.PNG)

**Comment by MrCrayfish** [comment]
If it says that, you clearly don't have the correct version. Check your mods folder!
