### ISSUE TITLE
Placing Crate then Breaking It Removes NBT

### ISSUE THREAD

**Issue by TwilightPSN** [MrCrayfish/MrCrayfishVehicleMod#112]
Had a Golf Cart get made then broke the Vehicle Crate to move it and it removed the NBT of the crate and basically making it useless and unopenable.

**Comment by MrCrayfish** [comment]
Thanks. Fixed in https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/10a359d6ee90fa29822d6407670e5baecda0705a
