### ISSUE TITLE
Can't open crate on servers

### ISSUE THREAD

**Issue by evanlegamer** [MrCrayfish/MrCrayfishVehicleMod#115]
Hi, we are on a server : 
- minecraft : 1.12.2
- Forge : 14.23.5.2768
- Vehicle mod : 0.39
- Obfuscate : 0.2.6

Our problem is that we can't open a crate picked in creative mode, we can pick it, put it in our inventory, place it on the map but first, the box do not open and secondly it does not open even with a wrench.

Then we have tried other things : 

- We have crafted vehicles in survival mode and then placed it on the map, It Works.
- We have crafted vehicles in creative mode and then placed it on the map, It Works.
- We have crafted vehicles in survival mode, then re-opened inventory and then placed it on the map, It does NOT Work, the vehicle didn't appear.
- We have crafted vehicles in creative mode, then re-opened inventory and then placed it on the map, It does NOT Work, the vehicle didn't appear.

Can you tell me if this is a common problem or if we did not understand something?
Thank you in advance.

**Comment by HanatakeYurii** [comment]
I got something similar, though it was not really annoying, and I finally got that sometimes the crates are simply empty, with no vehicle registered inside (no NBT).

Don't know if intended or not...

**Comment by evanlegamer** [comment]
Yeah but it's quite annoying because we wanted to create a shop where we could sell vehicles, but we can't because the crate looses his NBT when we put it in a chest or something like that.

**Comment by MrCrayfish** [comment]
I'm looking into the issue however I can't seen to replicate it. Can you provide your mod list in case it's actually another mods wrong doing? If you have some video, that will be cool.

**Comment by evanlegamer** [comment]
This is our list of mod : 

Mod Name | Version | Dependency
SecurityCraft | 1.8.12 | None
BetterBuildersWands | 0.11 | None
Chisel | 0.2.1.35 | CTM-MC 0.3.3.22
Device Mod | 0.4.1 | Obfuscate 0.2.6
Furniture Mod | 6.2.0 | Obfuscate 0.2.6
Currency | 1.12.0 | None
DecoCraft | 2.6.2 | PTRlib 1.0.4
Malisisdoors | 7.3.0 | malisiscore 6.4.0
OnlinePicFrame | 1.4.24 | CreativeCore  1.9.44
Optifine | 1.12.2 | None
RandomThings | 4.2.7.1 | None
Schematica | 1.8.0 | None
Thuttech | 6.1.5 | thutcore 5.19.10
TimeUHD | 7.3.0 | None
VehicleMod | 0.39.0 | Obfuscate 0.2.6
gliby's voice chat | 1.0.1 | None
WebDisplays | 1.0.0 | mcef 0.9
Working Gun | 1.0.0 | Obfuscate 0.2.6

Here is an example of our bug : 
https://youtu.be/gAWLQc4EmGk

The bug only happen on Server, Not in solo.

Thanks in advance :)

**Comment by wanou067** [comment]
up

**Comment by evanlegamer** [comment]
Still experiencing the issue :/. I have tested the mod on a server with only MrCrayfishVehicleMod, no other mod except obfuscated and no plugins. The problem is still there.
Thank you in advance for your help.

**Comment by wanou067** [comment]
MrCrayFish, the problem is still here, we can only have vehicles by crafting them, if we take them in creative menu, they loose their nbt

**Comment by MrCrayfish** [comment]
I still can't reproduce this problem. Please open a new issue if this still exists in the latest version of the mod.
