### ISSUE TITLE
Vehicle Json models with MrCrayFish's model Creator Texture error 

### ISSUE THREAD

**Issue by evanlegamer** [MrCrayfish/MrCrayfishVehicleMod#118]
Hi, I have opened a vehicle json model with MrCrayfish model creator and I have a problem with texture, the vehicle does not have any texture :/

![Capture](https://user-images.githubusercontent.com/18480367/57484973-c6fd3300-72aa-11e9-9efb-d703732c8b4b.PNG)

How can I get textures because they are in the json file 

Thanks in advance for your help ;)

**Comment by MrCrayfish** [comment]
If you are opening the JSON file, if you don't have assets path directory configured in your settings (File -> Settings -> General -> Assets Path), it won't be able to find the textures. This not a bug.
