### ISSUE TITLE
[BUG] Fuel your vehicles with anything.

### ISSUE THREAD

**Issue by maldiablo** [MrCrayfish/MrCrayfishVehicleMod#119]
Playing on a modded server I setup for a lan party.  My players accidentally filled a fuel drum with lava but then realized they can still drain it with the industrial jerry can.  They then proceeded to fill up their vehicles and drive them around.  Then they realized they could do this with water too.

There a possibility of adding a check to the jerry can to make sure it's pulling fuelium?

**Comment by HanatakeYurii** [comment]
> There a possibility of adding a check to the jerry can to make sure it's pulling fuelium?

Giving the config file that allows to select some fluids as vehicles, there should more be a check that allowed fluids are put in jerry can or directly in vehicles.

**Comment by maldiablo** [comment]
Wait - why was this closed?  Is this going to be fixed?

Is it not considered a bug?  Did I miss something?

Easy way to reproduce:
Fill fuel drum with water
Pull water out with Jerry can (I tested with the industrial one)
fuel vehicle with water
profit.

**Comment by HanatakeYurii** [comment]
MrCrayfish closed it because he did patch the mod for the next release to fix this.

As you can see:
> MrCrayfish closed this in a17de47 2 days ago
"a17de47" refer the patch (github commit), and give more details (code included) about it if you click the link.

**Comment by maldiablo** [comment]
Not fixed in 0.40.0.  I re-opened it and attached a video here that reproduces it:

https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/123

**Comment by HanatakeYurii** [comment]
I said in the NEXT version! Not the 0.40.0

**Comment by maldiablo** [comment]
Oh lol - sorry about that.  I get it now.  Thanks!  Awesome mod btw.
