### ISSUE TITLE
[Bug] I can't control click to automatically attach a trailer

### ISSUE THREAD

**Issue by Macintosh-Fan** [MrCrayfish/MrCrayfishVehicleMod#121]
When I want to attach a trailer to my vehicle, it does not work with the control click feature. Is there a bug to this issue @MrCrayfish ?

**Comment by MrCrayfish** [comment]
Video? Screenshots? I don't understand the issue sorry.

**Comment by HanatakeYurii** [comment]
I don't understand either, what do you mean by "control click" and "automatically"?
Manually attaching a trailer is working fine with me.

**Comment by Macintosh-Fan** [comment]
-> @HanatakeYurii Manual click works fine for me too
-> @MrCrayfish This is what I mean, that feature does not work for me, go to 5:41 of this video https://www.youtube.com/watch?v=IfmrbiEFRCY&t=343s

**Comment by HanatakeYurii** [comment]
Ah, I see, also working fine by me.
How are you trying to do this? Do you press the proper key when you're at the right distance?

**Comment by Macintosh-Fan** [comment]
My trailer hooker at the back of the vehicle is nearly touching it, and I press the control key, and it does not attach. Do I have to shift right click and click control? Or are there steps I am missing to hook the trailer to the vehicle?

**Comment by HanatakeYurii** [comment]
For me pressing the key once is enough. Mouse click is not involved.
Are you sure the key is properly bind in game configs?

**Comment by Macintosh-Fan** [comment]
@HanatakeYurii The keyboard settings are fine, I am on the vehicle, and I press control and it does not work. It might not be compatible on macOS, can you fix that @MrCrayfish?

**Comment by Macintosh-Fan** [comment]
Bug fixed?

**Comment by MrCrayfish** [comment]
Yes. Now it uses your sprint key to attach trailer while on a vehicle.

**Comment by HanatakeYurii** [comment]
Well done
