### ISSUE TITLE
Is it possible to create Vehicules Addon ?

### ISSUE THREAD

**Issue by evanlegamer** [MrCrayfish/MrCrayfishVehicleMod#124]
I created some new vehicles and added them in the mod, but when you upgrade your mod, my modifications are erased... Do you know how can I create addons to do not have to add them each time you upgrade your mod?
Thank you in advance.

**Comment by MrCrayfish** [comment]
The mod is not designed for addons yet. So yes, each update will keep breaking your mod until I make it addon friendly. Good example, look at Minecraft.
