### ISSUE TITLE
[BUG] Mini Bike Stuck

### ISSUE THREAD

**Issue by kvinno** [MrCrayfish/MrCrayfishVehicleMod#125]
I was filling fuel through the gas pump for the mini bike and I accidentally pressed LSHIFT. The mini bike then disappeared and I found out that I was carrying it with both hands, but I can't seem to put it down. Please help. Thanks in advance.
![Screenshot (102)_LI](https://user-images.githubusercontent.com/51320991/58796013-4ff75800-8626-11e9-86aa-8129d320f833.jpg)
![Minecraft 1 12 2 6_3_2019 5_38_51 PM_LI](https://user-images.githubusercontent.com/51320991/58796253-fd6a6b80-8626-11e9-9e02-5b89e09d1de3.jpg)

**Comment by MrCrayfish** [comment]
Crouch and right click the ground. This is not a bug. This is a core feature of the Vehicle Mod that allow you to pick up vehicles.

**Comment by kvinno** [comment]
> Crouch and right click the ground. This is not a bug. This is a core feature of the Vehicle Mod that allow you to pick up vehicles.

It worked. Thank you!
