### ISSUE TITLE
Traktorrr key hole is inside engine compartment

### ISSUE THREAD

**Issue by Methlon** [MrCrayfish/MrCrayfishVehicleMod#127]
Minecraft 1.12 of course, mod version 0.4.1.0, forge version 2773 (I think.)

Tractor's key hole is located inside the engine compartment..
Had to pull the block out, put the key in, then replace the engine.

Not the most economical way to turn a vehicle on and off, but whatever works lol.

**Comment by djdanby** [comment]
I have the same bug. 

MC 1.12.2
Forge: 2838

Screenshot: [https://ibb.co/vwBYhc9](url)

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/9b6dda0785d3ebe973a99753eab33a73aaec6431
