### ISSUE TITLE
(Suggestion) Plow and Combine

### ISSUE THREAD

**Issue by OneSharpAce** [MrCrayfish/MrCrayfishVehicleMod#129]
I would like to suggest the idea of a plow/disk trailer. Its function would be that when driven over normal dirt or grass it would convert it into farmland. Also a combine (short for combination harvester) would be a nice addition for harvesting crops as it is the most common vehicle used when harvest crops in the real world. It could include an internal storage (such as in real life) to remedy the not allowing storage trailers being towed.

**Comment by znaxcy** [comment]
Seconded. Perhaps a bailer that the combine can tow, as well? A trailer that places hay bales behind for every 8 wheat harvested by the combine?
