### ISSUE TITLE
(Bug) put this mod (or its dependence) causes frequently disconnetion when playing multiplayer

### ISSUE THREAD

**Issue by tyker1** [MrCrayfish/MrCrayfishVehicleMod#130]
Put this mod (or maybe it comes from its dependence Obfuscate) causes fatal errors when plaing on server, no matter wether the mods are installed on server side or not. (It causes fatal error so client side get frequently disconnected due to it, even the mod is only installed at client side)
As the log file not really point out which mod causes that, it tooks me about whole day to figure our.
the error are basicly: **unknown serializer type**, **entityspawnhandler error**, **package larger than expected**. where all pointed out as "networkdispatcher error". this things happens and only happens when trying to play on server with these mods installed.
for details check the attached log file, since it's too long. 
[latest.log](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/3289824/latest.log)

also theres an other bug, the fuel mixer sometimes not fulling up with blaze juice or ender juice, the juice pumped in just got lost.

**Comment by MrCrayfish** [comment]
If you're playing on a server that doesn't have the mod installed, you're going to face problems. In the programming there is a feature called DataParameters will allow for server -> client syncing on entity data. The vehicle mod adds extra data for the player entity. If the registered deserializers don't match the server you will run into the crash you posted. Only have the mods that are installed on the server on your client.
