### ISSUE TITLE
(Bug) Install VehicleMod on server(with newst Forge) causes client to disconnet frequently

### ISSUE THREAD

**Issue by tyker1** [MrCrayfish/MrCrayfishVehicleMod#131]
Sry for posted the same issue again, maybe i didn't figured it out clearly. It causes the client to disconnect due to fatal error, **unknow serializer type**. **Wether with or without the mod installed on the server side**. 

I tried to use it on server with forge Version 14.23.5.2838 on both client and server side. but it caused the client to disconnet frequently. As attachment i put the old log from both server and client side, hope u can figure out something.
As for the log might be too long, here are a time point where u can check:

Client side: at _**[21:26:10]**_ u can see i was attempted to conncet to server with some mods missing (**but do have the vehicle mod**, and i figured out that custom npcs aren't the source of causing this issue just as i put it in my mods folder and connect to server without any issue yesterday)
Client side at _**[21:27:16]**_ u can see that i start to have the issue and got disconnected due to it, the details are there

Server side: at _**[21:25:41]**_ proves that _**vehicleMod do got installed on the server side**_. as it registered EntityDataManager

Serverside: at _**[21:26:10]**_ is the time when i connected, with all mods listed.

Serverside: at _**[21:27:16]**_ u can see that i got disconnected, where the time client side said DataDispatcher got exceptions
[server.log](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/3291532/server.log)
[client.log](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/3291534/client.log)

**Comment by MrCrayfish** [comment]
This is most likely because you have an extra mods installed client side. Do you happen to have any mods installed client side that add extra entities but the mod is not installed on the server? Data serializers won't work correctly because they won't match the server if the client regeisters more than it should.

**Comment by tyker1** [comment]
For that i have no idea, what i did was use the binary search to figure out which mod makes the issue. Since all mods are on both server and client side (expect the JEI mods and minimap mod) and as i deleted other mods from both server and client side, it wasn't fixed, it was fixed only when i deleted the VehicleMod from server and client. That's why i thought this mod might be the source of disconnection.

But yes, i haven't tried to start the server with only VehicleMod installed

**Comment by MrCrayfish** [comment]
Try recommended Forge 2768

**Comment by MrCrayfish** [comment]
I should have a solution for this problem soon. I know it's still present in the current version of the mod.

**Comment by MrCrayfish** [comment]
Fixed in a5340ec
I should have an update published soon!
