### ISSUE TITLE
Successful installation on the server, but problems occurred.

### ISSUE THREAD

**Issue by RyuProject** [MrCrayfish/MrCrayfishVehicleMod#132]
in server v1.12.2 CatServer 4749966
Get the container, but it can't open automatically.And no plug-ins are installed.
I only installed this mod and obfuscate.
I like this mod very much. Hope to be resolved.

**Comment by wanou067** [comment]
Hello, i have the same problem, I'm also on CatServer 1.12.2. An admin of my server created an issue on the github before: https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/115
but MrCrayFish didn't find the solution yet
