### ISSUE TITLE
(Bug) Fuel still drains when vehicle is too damaged to actually run.

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/MrCrayfishVehicleMod#135]
If it's intentional (acting as if the gas tank is broken) then maybe make it leak slower and when the player isn't in the vehicle?
Otherwise if this isn't intentional, here's some attention towards it

Steps to reproduce:
1- Create any vehicle, and damage it to the point of being unusable, but not exploding into parts.
2- Fill the gas tank with fuel if you used creative.
3- Mount the vehicle and watch the gas counter go down as if it were running.

**Comment by MrCrayfish** [comment]
Fixed in recent versions
