### ISSUE TITLE
[Help] Fuel Pump does not pump up

### ISSUE THREAD

**Issue by djdanby** [MrCrayfish/MrCrayfishVehicleMod#136]
I tried to build a system that pumps the fuel up. Only somehow it does not work? What am I doing wrong?
The pumps are all on. The fuel runs into the barrel, but not from the barrel in the fuel trailer. Why?

<a href="https://ibb.co/z6F953H"><img src="https://i.ibb.co/z6F953H/Pump-Power.png" alt="Pump-Power" border="0"></a>

**Comment by trollsdottir** [comment]
I have the same problem

**Comment by MrCrayfish** [comment]
Your pipes are facing in the wrong direction. The black line indicates the output of the pipe.
