### ISSUE TITLE
Issue on server

### ISSUE THREAD

**Issue by Kewin05c** [MrCrayfish/MrCrayfishVehicleMod#14]
When i try to pick up any vehicle and place it back down the game stops and crashes

**Comment by MrCrayfish** [comment]
Send crash log smh

**Comment by Kewin05c** [comment]
This is what just pops up and I try to find it on %appdata%/.minecraft/crash-reports. And there is nothing.

**Comment by MrCrayfish** [comment]
This has been fixed in the latest update :)
