### ISSUE TITLE
Some vehicle can't craft in workstation

### ISSUE THREAD

**Issue by ztllllll** [MrCrayfish/MrCrayfishVehicleMod#141]
Version: 1.12.2
Mod Version: Vehicle Mod 0.41.0 - 1.12.2
Forge Version: 1.12.2 - 14.23.5.2838

Can't craft Bath and Shopping cart in vehicle workstation, l'm pretty sure l have prepared enough recipe required items. Can still get crate in Jei.

BTW,a little advice.
Maybe add one amount of Fuel consumption rate in config file is a good idea?

**Comment by jacobholden** [comment]
I'm having the same issue, any details for why this ticket was closed @MrCrayfish ?

**Comment by xpringle** [comment]
Same issue. I can't craft the shopping cart, even tho it says I have all the needed ingredients. 
I'm on 1.16.1 though.

**Comment by 10xTheFoxy** [comment]
i have the same exact issue, but in 1.16.4
