### ISSUE TITLE
Suggestion: More options for config file

### ISSUE THREAD

**Issue by Kirin92** [MrCrayfish/MrCrayfishVehicleMod#142]
Hey :D 

Is there a way to implement more stuff into the config file? It would be awesome if I could change the following in the config:

-change items I need for making the fuel
-change the speed of the different engines for the vehicles.
-change the amount of fuel I get with one glowstone dust

Would that be possible?

**Comment by MrCrayfish** [comment]
Most of this is now possible with the latest version of the mod using datapacks.
