### ISSUE TITLE
(Suggestion) Fuel compatibility(?) and lock for smart car

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/MrCrayfishVehicleMod#143]
Okay, so the way fuel compatibility _could_ work is when a world is started, the mod would scan all valid fluids, and make a list of them in the config.
Then, the user could go into the config and enable or disable liquids being used as fuel, similar to Immersive Vehicles system.

As for the smart car, I'm a bit curious as to why you can't link a key to the smart car.
Is this intended, and if so, how come?

**Comment by MrCrayfish** [comment]
Duplicate request https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/64
Feature is coming in 1.16 though
