### ISSUE TITLE
Bug with Chest Trailer

### ISSUE THREAD

**Issue by evanlegamer** [MrCrayfish/MrCrayfishVehicleMod#148]
Hi, just to say that there is a bug with chest trailer, the hook at the bottom of the trailer is very far from the trailer, i show you in screen the problem.

![2019-08-13_20 15 34](https://user-images.githubusercontent.com/18480367/62944558-24070880-be07-11e9-80a2-32f42fae9c8e.png)
![2019-08-13_20 08 50](https://user-images.githubusercontent.com/18480367/62944436-e4d8b780-be06-11e9-958c-3081599574f8.png)
![2019-08-13_20 09 10](https://user-images.githubusercontent.com/18480367/62944437-e4d8b780-be06-11e9-9dd8-761fb982ec1e.png)
![2019-08-13_20 09 16](https://user-images.githubusercontent.com/18480367/62944438-e4d8b780-be06-11e9-9e8c-370150c0d0c3.png)

My Version, 0.41.1
Minecraft version 1.12.2

**Comment by MrCrayfish** [comment]
Hmm I thought I fixed this. I will look into the issue.
