### ISSUE TITLE
/summon vehicle:off_roader

### ISSUE THREAD

**Issue by Lawkk69** [MrCrayfish/MrCrayfishVehicleMod#149]
When i summon a vehicule with a command /summon, i can't drive with him, you can help me ?
i use the command what i wrote in the title

**Comment by JacksonPlayz** [comment]
Don't use /summon, use the vehicle crates. /summon summons the vehicle without an engine, which you need to drive the vehicle. The crates spawn the vehicle with an engine.

**Comment by MrCrayfish** [comment]
Use Vehicle Crates as @JacksonPlayz mentioned.
