### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by axin0452** [MrCrayfish/MrCrayfishVehicleMod#151]
When the mower passes through botania, it triples the flowers.
Sorry, my English is not good.

vehicle-mod-0.41.0-1.12.2
Botania r1.10-361
spongeforge-1.12.2-2825-7.1.6-RC3755

**Comment by MrCrayfish** [comment]
The lawn mower has a looting effect on things it mows. This encourages players to use it, compared to harvesting it by hand.
