### ISSUE TITLE
[Suggestion] Add more options in config

### ISSUE THREAD

**Issue by gleybergood** [MrCrayfish/MrCrayfishVehicleMod#152]
I love the mod but there should be more options in the config to control how much fuel gets produced in the mixer because in survival, it's really expensive to get all the ingredients for the machines. Creating an efficient fuel farm is nearly impossible due to the mixer block being difficult to work with with all the pipes and the output of fuel in the mixer is so much slower than the output of blaze juice or ender sap. I've spent hours in my creative testing world trying to figure out an efficient way to produce fuel and there really is no good way.

**Comment by MrCrayfish** [comment]
This has been improved in recent versions. There is also support to change the recipes using datapacks.
