### ISSUE TITLE
(Suggestion) Fuel transfer rates/volume increase

### ISSUE THREAD

**Issue by FireheartIndustries** [MrCrayfish/MrCrayfishVehicleMod#155]
First off, I LOVE this mod! I just have a couple of suggestions for the fuel.

Speed it up! Seriously, the fluid transfer rate is WAY too slow! I made one of the fluid trailers and sat there waiting for it to fill. My first thought was "wow, this is taking...a LONG time! Must have a huge capacity!" only to discover that it only holds a couple of buckets worth of fluid.

In my opinion, the tank should hold significantly more fuel for the amount of time needed to transfer. Either the capacity needs a huge increase, or the pipes need better rates.

Then again, why not both? Triple (at least) the capacity of the trailer tank and the mb/t of the pipes and it wouldn't be a "molasses pouring simulator: winter edition"

**Comment by MrCrayfish** [comment]
I've added some config options to change this. Download the latest update 😀
