### ISSUE TITLE
(Suggestion,really important)Fuel advanced features in config

### ISSUE THREAD

**Issue by Alex34fggh** [MrCrayfish/MrCrayfishVehicleMod#156]
It is best if you would be adding if the vehicles in your mod can use different fluids as fuels (configurable,default:false),and an advanced scannning/blacklist and whitelist fluid compatibility.
(Note:I can use IC2,IndustrialCraft 2 and this has a fluid named biogas,which is cycled with different machines,NBT-tagged as ic2:biogas.There are other mods using this principle like Ender IO, Immersive Engineering,TiC ,etc.,etc.)

**Comment by MrCrayfish** [comment]
Duplicate request https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/64
Feature is coming in 1.16 though
