### ISSUE TITLE
Vehicles do not work 1.12.2

### ISSUE THREAD

**Issue by Puriificador** [MrCrayfish/MrCrayfishVehicleMod#158]
I have a problem, I downloaded this mod with the other **2 mods** that are necessary for its operation but when I enter the game and place the vehicles, I put **gasoline** and when I get on it I get that I have **full gasoline** but when **I give it to the W the vehicle does not move but if I give the A or D the wheels move to the sides**, someone who tells me what else I have to do, this happens in all vehicles of the mod and **I download several versions but none works**
Here is a link of the mods I have to tell me if any are needed: **https://prnt.sc/p9j9gv**

**Comment by JacksonPlayz** [comment]
Looks like you downloaded it from 9minecraft. GG

_You probably don't have an engine in the vehicle_
