### ISSUE TITLE
Weird Seeder Glitch

### ISSUE THREAD

**Issue by DoorKarma** [MrCrayfish/MrCrayfishVehicleMod#159]
So my friend and I we're playing a server on minecraft and we both wanted to make a farm with tractors. We both crafted seeders and for my friend the texture was working but for me is glitched. 

mod version : 0.41.0
game version : 1.12.2
![2019-09-30_19 29 49](https://user-images.githubusercontent.com/55994606/65898326-f3c8f880-e3b9-11e9-8ada-cebd472bfeab.png)

**Comment by MrCrayfish** [comment]
Please repoen this issue if it is still present on the latest version of the mod
