### ISSUE TITLE
Rave Couch Car does not have a Fuel Port

### ISSUE THREAD

**Issue by Drachehofen** [MrCrayfish/MrCrayfishVehicleMod#160]
As the title points out, the Rave Couch car lacks a fuel port with which to fuel the vehicle itself in survival.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/7c98c1ef5dcfc9502eebd18db68dc014f307cebd
