### ISSUE TITLE
Cant attach anything to storage trailer's hitch 0.41.1

### ISSUE THREAD

**Issue by Pleune** [MrCrayfish/MrCrayfishVehicleMod#162]
When trying to attach any trailer onto the back of a storage trailer, it instead opens the storage trailer's inventory. I can't seem to find any way around this, when shift clicking with carrying turned off.

**Comment by yeeeeeeeeeeeeeeeeeeeeeeee** [comment]
you have to click further than the hook, towards the chest and it works. I had the same problem then figured it out!

**Comment by yeeeeeeeeeeeeeeeeeeeeeeee** [comment]
@Pleune you have to click further than the hook, towards the chest and it works. I had the same problem then figured it out!

**Comment by MrCrayfish** [comment]
Duplicate of https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/154
