### ISSUE TITLE
Fuel mixer wont make fuel

### ISSUE THREAD

**Issue by KeyMasterX294** [MrCrayfish/MrCrayfishVehicleMod#165]
I have already extracted the fluids for the mixer and put in coal and glowstone into their respective slots but the mixer will not work. i am using >80 other mods as well with the vehicle mod. are there any mods that the vehicle mod wont work with? is there a new recipe that i am not aware of? please help.

**Comment by MrCrayfish** [comment]
https://www.youtube.com/watch?v=0eZbCc2UH2s

**Comment by KeyMasterX294** [comment]
![2019-11-17_17 57 24](https://user-images.githubusercontent.com/39683374/69015640-dea52a80-0963-11ea-86e5-530358e57ed7.png)
i originally followed that but the block wont make any fuelium.
