### ISSUE TITLE
Please help! fluid mixer wont make fuel! check attached image! issue resolved! (sort of... dont know what caused it)

### ISSUE THREAD

**Issue by KeyMasterX294** [MrCrayfish/MrCrayfishVehicleMod#166]
![2019-11-17_17 57 24](https://user-images.githubusercontent.com/39683374/69015671-32b00f00-0964-11ea-9454-56d167671c9d.png)
i followed the instructions video but the fluid mixer does not work. everything is there but it will not mix. the progress bar does not animate nor does the machine make the fuel. is there any incompatibilities with any other mod that could cause this?

**Comment by KeyMasterX294** [comment]
i would also like to say that i previously posted this same issue and MrCrayfish replied with a link to the same video from which i obtained  the recipe that i am using and that thread was closed without actually attempting to solve the problem that i originally posted so i added a picture of the gui to prove that i am following the original tutorial video posted by MrCrayfish himself. i just want to use the vehicle mod w/out having to cheat the fuel in on my survival world. i am using 90 different mods that i installed into my minecraft client (i am not using a modpack or a modpack launcher)

**Comment by MrCrayfish** [comment]
Can you try installing the Vehicle Mod by itself and see if the Fluid Mixer works?

**Comment by KeyMasterX294** [comment]
the mod works on its own

**Comment by MrCrayfish** [comment]
Must be a mod you have installed breaking it

**Comment by KeyMasterX294** [comment]
i am testing to find the problem now

**Comment by KeyMasterX294** [comment]
its only affecting the world save that i am using. when i go to a different world to test it the block works just fine

**Comment by KeyMasterX294** [comment]
i just tried moving it from my base to ground level and it finally worked

**Comment by eskimo-exe** [comment]
I have this exact same problem and have tried moving my fluid mixer up and down many different Y levels and it still won't work!
