### ISSUE TITLE
1.15.1 crash on loading bug

### ISSUE THREAD

**Issue by 5kedone** [MrCrayfish/MrCrayfishVehicleMod#175]
using the 1.15.1 version of mod on forge .35 the game fails to load with a entity id error 

here is the crash log 

https://pastebin.com/2WqPzWje

hope it helps

**Comment by yeeeeeeeeeeeeeeeeeeeeeeee** [comment]
@5kedone Download the newest Vehicle Mod. it works

**Comment by 5kedone** [comment]
this is with Vehicle Mod 0.42.1 which is the latest

**Comment by yeeeeeeeeeeeeeeeeeeeeeeee** [comment]
@5kedone get the 0.42.2 released today! Works
