### ISSUE TITLE
Losing connection to server when logging in. EncoderException

### ISSUE THREAD

**Issue by CaptainBob81** [MrCrayfish/MrCrayfishVehicleMod#179]
Trying to set up a private forge 1.15.1 server using a schmutz-ton of mods. Server starts Ok, client starts ok. Able to play singleplayer. But when logging in to server i get "lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException"
When i remove vehiclemod everything works fine. I have the furniture mod installed and that works fine. But when i add the vehicle mod i cannot log in to the server. Tried to spawn new world. Did not work. Tried to copy over configfiles from server to client. No dice. 
Using forge 30.0.35
Have tried vehiclemod 0.42.0 through 0.42.2 and all 1.15 obfuscate mods.
Relevant information in files. Not much is logged. Just the Exception from Java. 

[latestClient2.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4049678/latestClient2.txt)
 
[latest2.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4049675/latest2.txt)

**Comment by sunnyguan** [comment]
Also have the same issue. My server works every time except when vehicle mod (2.0.12) and obfuscate (0.3.4) are added into both server and client.
