### ISSUE TITLE
Uh This Is Broken

### ISSUE THREAD

**Issue by Stuethekid** [MrCrayfish/MrCrayfishVehicleMod#18]
![uh this is broken](https://user-images.githubusercontent.com/40968360/42425044-b16fcd24-82e4-11e8-90bd-c3ce59677624.png)

**Comment by Stuethekid** [comment]
![xd](https://user-images.githubusercontent.com/40968360/42425112-f80f0ec4-82e5-11e8-88a2-015380828e21.png)
Found Another Error XD

**Comment by Sqaaakoi** [comment]
What?

**Comment by MrCrayfish** [comment]
Already reported.
