### ISSUE TITLE
[Suggestion] Add support for more passengers in plane

### ISSUE THREAD

**Issue by Macintosh-Fan** [MrCrayfish/MrCrayfishVehicleMod#180]
The plane in the game is currently great, but I want it to hold at least two people. Is that possible? if so, can you please add support in 1.12.2?

Thanks

**Comment by Macintosh-Fan** [comment]
@MrCrayfish What do you think?

**Comment by Macintosh-Fan** [comment]
Why close?

**Comment by MrCrayfish** [comment]
This would be a new vehicle, not modifying the sports plane. Also it's clutter because its not an issue.
