### ISSUE TITLE
[BUGS] Fluid Drums (multiple issues)

### ISSUE THREAD

**Issue by Nachtflame** [MrCrayfish/MrCrayfishVehicleMod#181]
vehicle-mod-0.42.4-1.15.1
obfuscate-0.3.4-1.15.1
forge-30.0.36

1) When broken both fluid drum types drop themselves (containing any fluids) _and_ an empty copy.

2) The standard _Fuel Drum_ collects fluids flowing through adjacent blocks, but _only as the fluid levels in the adjacent block-space changes_
![2020-01-16_16 13 47](https://user-images.githubusercontent.com/27873876/72573645-3c2df880-387b-11ea-9c72-145d2c429cf1.png)
_

**Comment by MrCrayfish** [comment]
Both these issue have been fixed in the latest version :)
