### ISSUE TITLE
Seeder Issue

### ISSUE THREAD

**Issue by MestariSamuli** [MrCrayfish/MrCrayfishVehicleMod#182]
Seeder inventory works again, thanks about that. Anyway i founded new issue. When I drive tractor with seeder over farmland nothing happens. So basically seeder doesn't plant seeds.

**Comment by edusmrs** [comment]
same here

**Comment by Starz143** [comment]
Yup, me and a friend of mine have the same issue.

**Comment by Cyybert** [comment]
Yes,I have the same problem,I cant sow seeds with ATV,tractor and smart car. MrCrayfish pls fix it!

**Comment by aadit98** [comment]
Seeder won't plant anything for me 1.15.2

**Comment by MrCrayfish** [comment]
Fixed in recent versions
