### ISSUE TITLE
Mod crashes on startup in Minecraft 1.15.2

### ISSUE THREAD

**Issue by Tsoccerguy3** [MrCrayfish/MrCrayfishVehicleMod#186]
Here is the crash log with 2 mods
obfuscate-0.3.4-1.15.2.jar
vehicle-mod-0.42.4-1.15.2.jar
https://pastebin.com/pPSa3VL6

**Comment by ProsperCraft** [comment]
![2020-02-01_22 53 45](https://user-images.githubusercontent.com/4427684/73603930-8c2ce080-4546-11ea-83ab-b4ca234484b7.png)

Stacktrace-
https://gist.github.com/ProsperCraft/36b61ee10914fb4e5287e9e3c8a9eec7

log-
[latest.log](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4143588/latest.log)

**Comment by Tsoccerguy3** [comment]
Fixed
