### ISSUE TITLE
Forge 31.0.14 "Render Issue Crash"

### ISSUE THREAD

**Issue by MLMII** [MrCrayfish/MrCrayfishVehicleMod#187]
[latest.log](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4140637/latest.log)

I think one of the Forge updates broke your mod; I'm using 1.15.2  Forge 31.0.14 and during startup I get the following error; "MrCrayfish's Vehicle Mod (vehicle) encountered an error during the sided_setup event phase  …
net/minecraftforge/client/event/RenderSpecificHandEvent"

**Comment by Tsoccerguy3** [comment]
same issue with log https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/186

**Comment by Tsoccerguy3** [comment]
issue fixed , I closed Ticket 186

**Comment by MrCrayfish** [comment]
Download latest version. I have fixed the crash
