### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by Camawama** [MrCrayfish/MrCrayfishVehicleMod#189]
When mining the fuel drum, fluid extractor, and fluid mixer with a pickaxe it drops two tile entities instead of one

**Comment by Camawama** [comment]
Also happens with the Fluid Extractors

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/9b82245d1680c68423b9ee7a845b81a53ce11e1e
Download 0.42.6
