### ISSUE TITLE
[Vehicle 0.17.1] Server crash when summoning the bath vehicle

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishVehicleMod#19]
When I tried to summon the "bath" vehicle it crashed my SMP server.

Here's the crash report:

Time: 7/11/18 6:13 PM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.world.World.func_175682_a(Lnet/minecraft/util/EnumParticleTypes;ZDDDDDD[I)V
	at com.mrcrayfish.vehicle.entity.vehicle.EntityBath.updateVehicle(EntityBath.java:45)
	at com.mrcrayfish.vehicle.entity.EntityVehicle.func_70071_h_(EntityVehicle.java:198)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.mrcrayfish.vehicle.entity.vehicle.EntityBath.updateVehicle(EntityBath.java:45)
	at com.mrcrayfish.vehicle.entity.EntityVehicle.func_70071_h_(EntityVehicle.java:198)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: vehicle:bath (com.mrcrayfish.vehicle.entity.vehicle.EntityBath)
	Entity ID: 8469
	Entity Name: entity.bath.name
	Entity's Exact location: 35.58, 63.00, -271.03
	Entity's Block location: World: (35,63,-272), Chunk: (at 3,3,0 in 2,-17; contains blocks 32,0,-272 to 47,255,-257), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world2018
	All players: 1 total; [EntityPlayerMP['fandomaniac'/486, l='world2018', x=35.58, y=63.00, z=-271.03]]
	Chunk stats: ServerChunkCache: 486 Drop: 0
	Level seed: -844651155053912060
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (192,64,256), Chunk: (at 0,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 310541635 game time, 181201808 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 66697 (now: false), thunder time: 96214 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.11.0-26-generic
	Java Version: 1.8.0_152, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2644703176 bytes (2522 MB) / 4172283904 bytes (3979 MB) up to 4172283904 bytes (3979 MB)
	JVM Flags: 3 total; -Xmx4096M -Xms4096M -Xss2M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.4.2732 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version              | Source                                         | Signature                                |
	|:--------- |:-------------------- |:-------------------- |:---------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2               | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | mcp                  | 9.42                 | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99            | forge-1.12.2-14.23.4.2732-universal.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.4.2732         | forge-1.12.2-14.23.4.2732-universal.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | openmodscore         | 0.11.5               | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | foamfixcore          | 7.7.4                | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | obfuscate            | 0.2.4                | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | quark                | r1.4-125             | Quark-r1.4-125.jar                             | None                                     |
	| UCHIJAAAA | autoreglib           | 1.3-18               | AutoRegLib-1.3-18.jar                          | None                                     |
	| UCHIJAAAA | backpacks16840       | 3.5.2                | backpacks 1.12.2 - 3.5.2.jar                   | None                                     |
	| UCHIJAAAA | bibliocraft          | 2.4.5                | BiblioCraft[v2.4.5][MC1.12.2].jar              | None                                     |
	| UCHIJAAAA | cfm                  | 5.1.0                | cfm-5.1.0-mc1.12.2.jar                         | None                                     |
	| UCHIJAAAA | chameleon            | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                       | None                                     |
	| UCHIJAAAA | chesttransporter     | 2.8.8                | ChestTransporter-1.12.2-2.8.8.jar              | None                                     |
	| UCHIJAAAA | cjcm                 | 1.0                  | cjcm-1.0.jar                                   | None                                     |
	| UCHIJAAAA | codechickenlib       | 3.2.0.345            | CodeChickenLib-1.12.2-3.2.0.345-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | cookingforblockheads | 6.4.40               | CookingForBlockheads_1.12.2-6.4.40.jar         | None                                     |
	| UCHIJAAAA | craftablesaddles     | 1.3                  | Craftable+Saddles[1.12]-1.3.jar                | None                                     |
	| UCHIJAAAA | customnpcs           | 1.12                 | CustomNPCs_1.12.2(09jul18).jar                 | None                                     |
	| UCHIJAAAA | ptrmodellib          | 1.0.2                | PTRLib-1.0.2.jar                               | None                                     |
	| UCHIJAAAA | props                | 2.6.0                | Decocraft-2.6.0_1.12.2.jar                     | None                                     |
	| UCHIJAAAA | cdm                  | 0.4.1                | device-mod-0.4.1-1.12.2.jar                    | None                                     |
	| UCHIJAAAA | gottschcore          | 1.3.5                | GottschCore-mc1.12-f14.21.1.2387-v1.3.5.jar    | None                                     |
	| UCHIJAAAA | dungeons2            | 1.3.3                | Dungeons2-mc1.12-f14.21.1.2387-v1.3.3.jar      | None                                     |
	| UCHIJAAAA | dungeontactics       | DT-0.14.2            | DungeonTactics-1.12.2-0.14.2.jar               | None                                     |
	| UCHIJAAAA | ebwizardry           | 4.1.2                | Electroblob's Wizardry - 4.1.2 - MC 1.12.2.jar | None                                     |
	| UCHIJAAAA | fastleafdecay        | v14                  | FastLeafDecay-v14.jar                          | None                                     |
	| UCHIJAAAA | foamfix              | 0.9.9.1-1.12.2       | foamfix-0.9.9.1-1.12.2-anarchy.jar             | None                                     |
	| UCHIJAAAA | foamflower           | 1.12.2-1.0.0.0-beta1 | foamflower-1.12.2-1.0.0.0-beta1.jar            | None                                     |
	| UCHIJAAAA | gravestone           | 1.10.1               | gravestone-1.10.1.jar                          | None                                     |
	| UCHIJAAAA | infernalmobs         | 1.7.5                | InfernalMobs-1.12.2.jar                        | None                                     |
	| UCHIJAAAA | ironchest            | 1.12.2-7.0.40.824    | ironchest-1.12.2-7.0.40.824.jar                | None                                     |
	| UCHIJAAAA | jei                  | 4.11.0.202           | jei_1.12.2-4.11.0.202.jar                      | None                                     |
	| UCHIJAAAA | jrftl                | 1.1                  | JRFTL[1.12.2]-1.1.jar                          | None                                     |
	| UCHIJAAAA | lootbags             | 2.5.6                | LootBags-1.12.2-2.5.6.jar                      | None                                     |
	| UCHIJAAAA | lunatriuscore        | 1.2.0.42             | LunatriusCore-1.12.2-1.2.0.42-universal.jar    | None                                     |
	| UCHIJAAAA | lycanitesmobs        | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJAAAA | arcticmobs           | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJAAAA | demonmobs            | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJAAAA | desertmobs           | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJAAAA | elementalmobs        | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJAAAA | forestmobs           | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJAAAA | freshwatermobs       | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJAAAA | infernomobs          | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJAAAA | junglemobs           | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJAAAA | mountainmobs         | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJAAAA | plainsmobs           | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJAAAA | saltwatermobs        | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJAAAA | shadowmobs           | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJAAAA | swampmobs            | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJAAAA | malisiscore          | 1.12.2-6.4.0         | malisiscore-1.12.2-6.4.0.jar                   | None                                     |
	| UCHIJAAAA | malisisblocks        | 1.12.2-6.1.0         | malisisblocks-1.12.2-6.1.0.jar                 | None                                     |
	| UCHIJAAAA | malisisdoors         | 1.12.2-7.3.0         | malisisdoors-1.12.2-7.3.0.jar                  | None                                     |
	| UCHIJAAAA | mantle               | 1.12-1.3.2.24        | Mantle-1.12-1.3.2.24.jar                       | None                                     |
	| UCHIJAAAA | natura               | 1.12.2-4.3.2.49      | natura-1.12.2-4.3.2.49.jar                     | None                                     |
	| UCHIJAAAA | nex                  | 2.1.14.15            | NetherEx-1.12-2.1.14.15.jar                    | None                                     |
	| UCHIJAAAA | recipehandler        | 0.11                 | NoMoreRecipeConflict-0.11(1.12.2).jar          | None                                     |
	| UCHIJAAAA | nei                  | 2.4.1                | NotEnoughItems-1.12.2-2.4.1.233-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | openmods             | 0.11.5               | OpenModsLib-1.12.2-0.11.5.jar                  | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | openblocks           | 1.7.6                | OpenBlocks-1.12.2-1.7.6.jar                    | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | guilib               | $version             | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar  | None                                     |
	| UCHIJAAAA | paintingselgui       | $version             | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar  | None                                     |
	| UCHIJAAAA | harvestcraft         | 1.12.2u              | Pam's HarvestCraft 1.12.2u.jar                 | None                                     |
	| UCHIJAAAA | roguelike            | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar             | None                                     |
	| UCHIJAAAA | simplecore           | 1.6.0.6              | simplecore-1.12.2-1.6.0.6.jar                  | None                                     |
	| UCHIJAAAA | simpleores           | 1.11.1.9             | simpleores-1.12.2-1.11.1.9.jar                 | None                                     |
	| UCHIJAAAA | simplyenchanting     | 1.0.3                | SimplyEnchanting-1.12-1.0.3.jar                | None                                     |
	| UCHIJAAAA | soccer               | 1.0                  | soccer-mod-1.0-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | storagedrawers       | 1.12-5.3.5           | StorageDrawers-1.12.2-5.3.7.jar                | None                                     |
	| UCHIJAAAA | tconstruct           | 1.12.2-2.10.1.87     | TConstruct-1.12.2-2.10.1.87.jar                | None                                     |
	| UCHIJAAAA | treechopper          | 1.2.4                | TreeChopper-1.12.2-1.2.4.jar                   | None                                     |
	| UCHIJAAAA | variedcommodities    | 1.12.2               | VariedCommodities_1.12.2(15may18.jar           | None                                     |
	| UCHIJAAAA | varodd               | 4.0                  | varodd-1.12.2-4.0.jar                          | None                                     |
	| UCHIJAAAA | vehicle              | 0.17.1               | vehicle-0.17.1-mc1.12.2.jar                    | None                                     |
	| UCHIJAAAA | vending              | 1.12.2-3.0.1.1       | vending-1.12.2-3.0.1.1.jar                     | None                                     |
	| UCHIJAAAA | waystones            | 4.0.43               | Waystones_1.12.2-4.0.43.jar                    | None                                     |
	| UCHIJAAAA | worldutils           | 0.4.2                | worldutils-1.12.2-0.4.2.jar                    | 2b03e1423915a189b8094816baa18f239d576dff |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
BCModPlugin (backpacks 1.12.2 - 3.5.2.jar)
  brad16840.core.ClassTransformer
LoadingPlugin (Quark-r1.4-125.jar)
  vazkii.quark.base.asm.ClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ObfuscatePlugin (obfuscate-0.2.4-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 80; [EntityPlayerMP['fandomaniac'/486, l='world2018', x=35.58, y=63.00, z=-271.03]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by fandomaniac** [comment]
The summoned bath corrupted the chunk. so I rolled-back the server to a previous backup. I didn't get a chance to summon a plane, so I'm not sure if it has the same issue for SMP servers,

**Comment by MrCrayfish** [comment]
I pushed a new update. It should fix the issue!
