### ISSUE TITLE
Missing Vehicles

### ISSUE THREAD

**Issue by rebklebold** [MrCrayfish/MrCrayfishVehicleMod#191]
I've recently installed the Vehicle mod for 1.15.2
I have the latest forge,
latest vehicle mod and obfuscate library mod.
I am missing all vehicles besides the aluminum boat; as well as the entire childhood toy section (which i have downloaded as well) are there any fixes for this, or maybe I'm doing something wrong?

any help would be appreciated, thanks.

**Comment by MrCrayfish** [comment]
Are they showing up in the creative tab?

**Comment by rebklebold** [comment]
Oh! yes they are, wondering why they wouldn't show up anywhere else. Thank you!
