### ISSUE TITLE
[BUG] Duplication bug using Storage Trailer or Seeder

### ISSUE THREAD

**Issue by DevTimur** [MrCrayfish/MrCrayfishVehicleMod#194]
Version **vehicle-mod-0.41.1-1.12.2**
If you pick up Storage Trailer you can see inventory, take items out, and then put trailer back, items will be duplicated.

https://i.gyazo.com/d60b1422ff5032d3cd8d6e147b04dfb7.gif
Same thing works with Seeder.

Important, you need to aim at Chest, but throught wheel. It register as i pick up and check inventory at same time. Will not work if you aproach from front or back, only from side.

**Comment by DevTimur** [comment]
Not fixed yet?

**Comment by MrCrayfish** [comment]
I will get to this soon...

**Comment by DevTimur** [comment]
By the way, dude... I'm thinking...
What if I open chest on trailer, and someone else will pick it up while I take stuff out of it.
Would that duplicate stuff too?
I know easy sollution, it would also make more sence.
Make so if ANYTHING in chest, disallow picking up, and say something like "Chest not empty, you not strong enough to pick it up". That would deffenitely solve this issue.
Also, I can pickup Moped with chest aswell, I couldn't replicate same dupe as Storage Trailer got, but issue with 2 players dupe is still possible.

**Comment by mxnmnm** [comment]
Is this still an issue for the storage trailer? I'm trying to do it but it won't let me because I can't carry it when looking at the chest and I can't open it when I'm not looking directly at the chest. Where were you looking when you did it?

**Comment by DevTimur** [comment]
You must look at side of trailer. Try looking a frame above wheel. Iso kinda chest but kinda wheel as well. Not front or behind. But "sideways".
