### ISSUE TITLE
Copy & Paste mod structures with WorldEdit

### ISSUE THREAD

**Issue by sideliner16** [MrCrayfish/MrCrayfishVehicleMod#197]
Our world got crashed when I copied a fuel mechanism from one world and pasted it to another world. Here is a crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 2/28/20 5:13 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=thuttech:lift, properties=[called, current, variant]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at com.mrcrayfish.vehicle.tileentity.TileEntityFluidPipe.func_73660_a(TileEntityFluidPipe.java:76)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at com.mrcrayfish.vehicle.tileentity.TileEntityFluidPipe.func_73660_a(TileEntityFluidPipe.java:76)

-- Block entity being ticked --
Details:
	Name: vehicle:fluid_pipe // com.mrcrayfish.vehicle.tileentity.TileEntityFluidPipe
	Block type: ID #479 (tile.lift // thut.tech.common.blocks.lift.BlockLift // thuttech:lift)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (411,71,298), Chunk: (at 11,4,10 in 25,18; contains blocks 400,0,288 to 415,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #479 (tile.lift // thut.tech.common.blocks.lift.BlockLift // thuttech:lift)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New Yeet!
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 1373598053
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (373,65,256), Chunk: (at 5,4,0 in 23,16; contains blocks 368,0,256 to 383,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 488592 game time, 10387 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 89302 (now: false), thunder time: 50618 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 86912208 bytes (82 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_C8 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                    | Version         | Source                                            | Signature                                |
	|:--------- |:--------------------- |:--------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft             | 1.12.2          | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | mcp                   | 9.42            | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | FML                   | 8.0.99.99       | forge-1.12.2-14.23.5.2768.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                 | 14.23.5.2768    | forge-1.12.2-14.23.5.2768.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | obfuscate             | 0.2.6           | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | cfm                   | 6.2.0           | cfm-6.2.0-mc1.12.2.jar                            | None                                     |
	| UCHIJAAAA | cgm                   | 0.9.2           | cgm-0.9.2-mc1.12.2.jar                            | None                                     |
	| UCHIJAAAA | ichunutil             | 7.2.0           | iChunUtil-1.12.2-7.2.0.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| UCHIJAAAA | jei                   | 4.15.0.268      | jei_1.12.2-4.15.0.268.jar                         | None                                     |
	| UCHIJAAAA | much_better_minecraft | 1.0.0           | much-better-minecraft-1-2-1-12-2.jar              | None                                     |
	| UCHIJAAAA | simplecore            | 1.7.3.4         | simplecore-1.12.2-1.7.3.4.jar                     | None                                     |
	| UCHIJAAAA | simpleores            | 1.11.2.2        | simpleores-1.12.2-1.11.2.2.jar                    | None                                     |
	| UCHIJAAAA | thutcore              | 5.21.0          | thutcore-1.12.2-5.21.0.jar                        | None                                     |
	| UCHIJAAAA | thutcore_compat       | 1.0             | thutcore-1.12.2-5.21.0.jar                        | None                                     |
	| UCHIJAAAA | thuttech              | 6.1.6           | thuttech-1.12.2-6.1.6.jar                         | None                                     |
	| UCHIJAAAA | torohealthmod         | 1.12.2-11       | torohealth-1.12.2-11.jar                          | None                                     |
	| UCHIJAAAA | treechopper           | 1.2.4           | TreeChopper-1.12.2-1.2.4.jar                      | None                                     |
	| UCHIJAAAA | vehicle               | 0.41.0          | vehicle-0.41.0-mc1.12.2.jar                       | None                                     |
	| UCHIJAAAA | waystones             | 4.1.0           | Waystones_1.12.2-4.1.0.jar                        | None                                     |
	| UCHIJAAAA | worldedit             | 6.1.10-SNAPSHOT | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |

	Loaded coremods (and transformers): 
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by MrCrayfish** [comment]
I will no longer be supporting 1.12.2
