### ISSUE TITLE
[VehicleMod 0.6.0] Server thread/WARN [FML]: Registry Item: Object did not get ID it asked for.

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishVehicleMod#2]
I'm running a multiplayer server with the latest Forge release for 1.12.2 and I'm getting the following warnings in the Server Console:

25.04 13:08:39 [Server] Server thread/WARN [FML]: Registry Item: Object did not get ID it asked for. Name: vehicle:go_kart Expected: 5376 Got: 4298
25.04 13:08:39 [Server] Server thread/WARN [FML]: Registry Item: Object did not get ID it asked for. Name: vehicle:go_kart_steering_wheel Expected: 5377 Got: 4299
25.04 13:08:39 [Server] Server thread/WARN [FML]: Registry Item: Object did not get ID it asked for. Name: vehicle:shopping_cart_body Expected: 5378 Got: 4300
25.04 13:08:39 [Server] Server thread/WARN [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: vehicle:go_kart_engine_stereo Expected: 732 Got: 511
25.04 13:08:39 [Server] Server thread/WARN [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: vehicle:go_kart_engine_mono Expected: 731 Got: 566
25.04 13:08:39 [Server] Server thread/WARN [FML]: Registry EntityEntry: Object did not get ID it asked for. Name: vehicle:go_kart Expected: 174 Got: 171
25.04 13:08:39 [Server] Server thread/WARN [FML]: Registry EntityEntry: Object did not get ID it asked for. Name: vehicle:shopping_cart Expected: 175 Got: 184

**Comment by MrCrayfish** [comment]
Does this happen everytime or just once off? I re-arranged some of the registering code so that might be the issue.

**Comment by fandomaniac** [comment]
I just restarted and didn't get the warnings again, so I'm guessing it only happened once. I'll close this report.
