### ISSUE TITLE
can you add chinese(zh_cn.lang) translate to this mod?

### ISSUE THREAD

**Issue by mengdiao** [MrCrayfish/MrCrayfishVehicleMod#200]
{
    "itemGroup.tabVehicle": "MrCrayfish's 载具 Mod",

    "vehicle.engine_type.small.name": "小型发动机",
    "vehicle.engine_type.large.name": "大型发动机",
    "vehicle.engine_type.electric.name": "电力发动机",

    "vehicle.engine_tier.wood.name": "木制等级",
    "vehicle.engine_tier.stone.name": "石制等级",
    "vehicle.engine_tier.iron.name": "铁质等级",
    "vehicle.engine_tier.gold.name": "金制等级",
    "vehicle.engine_tier.diamond.name": "钻石等级",
    "vehicle.engine_info.acceleration": "加速度",
    "vehicle.engine_info.additional_max_speed": "附加最大加速度",
    "vehicle.engine_info.fuel_consumption": "油耗",

    "vehicle.wheel_type.stock.name": "原始",
    "vehicle.wheel_type.sports.name": "运动",
    "vehicle.wheel_type.racing.name": "竞速",
    "vehicle.wheel_type.off_road.name": "越野",
    "vehicle.wheel_type.snow.name": "雪",
    "vehicle.wheel_type.all_terrain.name": "全地形",
    "vehicle.wheel_type.plastic.name": "塑料",

    "item.vehicle.wood_small_engine": "小型发动机[木]",
    "item.vehicle.stone_small_engine": "小型发动机[石]",
    "item.vehicle.iron_small_engine": "小型发动机[铁]",
    "item.vehicle.gold_small_engine": "小型发动机[金]",
    "item.vehicle.diamond_small_engine": "小型发动机[钻]",
    "item.vehicle.wood_large_engine": "大型发动机[木]",
    "item.vehicle.stone_large_engine": "大型发动机[石]",
    "item.vehicle.iron_large_engine": "大型发动机[铁]",
    "item.vehicle.gold_large_engine": "大型发动机[金]",
    "item.vehicle.diamond_large_engine": "大型发动机[钻]",
    "item.vehicle.wood_electric_engine": "电力发动机[木]",
    "item.vehicle.stone_electric_engine": "电力发动机[石]",
    "item.vehicle.iron_electric_engine": "电力发动机[铁]",
    "item.vehicle.gold_electric_engine": "电力发动机[金]",
    "item.vehicle.diamond_electric_engine": "电力发动机[钻]",
    "item.vehicle.spray_can": "喷漆罐",
    "item.vehicle.spray_can.info": "使用这个喷漆罐给车车喷涂哦。在合成台中与一至多个染料进行合成来添加颜色。在合成台中与无色喷漆罐合成可以进行重装。",
    "item.vehicle.spray_can.empty": "无色",
    "item.vehicle.jerry_can": "简便油桶",
    "item.vehicle.jerry_can.info": "使用简便油桶能够为车车装填燃料元素。它能够存储 5 桶燃料元素。",
    "item.vehicle.jerry_can.fuel": "燃料: %s",
    "item.vehicle.industrial_jerry_can": "工业简便油桶",
    "item.vehicle.industrial_jerry_can.info": "使用工业简便油桶，可以为车车填充燃料元素。它能够存储 15 桶燃料元素。",
    "item.vehicle.industrial_jerry_can.fuel": "燃料: %s",
    "item.vehicle.wrench": "扳手",
    "item.vehicle.key": "钥匙",
    "item.vehicle.panel": "面板",
    "item.vehicle.standard_wheel": "轮子",
    "item.vehicle.sports_wheel": "轮子",
    "item.vehicle.racing_wheel": "轮子",
    "item.vehicle.off_road_wheel": "轮子",
    "item.vehicle.snow_wheel": "轮子",
    "item.vehicle.all_terrain_wheel": "轮子",
    "item.vehicle.plastic_wheel": "轮子",
    "item.vehicle.tow_bar": "牵引杆",
    "item.vehicle.go_kart_steering_wheel": "方向盘",
    "item.vehicle.handle_bar": "手柄杆",
    "item.vehicle.hammer": "锤子",
    "item.vehicle.fuelium_bucket": "燃料元素桶",
    "item.vehicle.ender_sap_bucket": "末影之液桶",
    "item.vehicle.blaze_juice_bucket": "烈焰橙汁桶",

    "block.vehicle.traffic_cone": "交通锥",
    "block.vehicle.boost_pad": "加速道",
    "block.vehicle.boost_ramp": "加速斜坡",
    "block.vehicle.steep_boost_ramp": "陡峭加速斜坡",
    "block.vehicle.gas_pump": "加油站",
    "block.vehicle.fluid_extractor": "流体提取机",
    "block.vehicle.fluid_mixer": "流体混合器",
    "block.vehicle.fluid_pipe": "流体管道",
    "block.vehicle.fluid_pump": "液泵",
    "block.vehicle.fuel_drum": "油桶",
    "block.vehicle.industrial_fuel_drum": "工业油桶",
    "block.vehicle.vehicle_crate": "载具板条箱",
    "block.vehicle.workstation": "工作站",
    "block.vehicle.jack": "千斤顶",

    "fluid.vehicle.fuelium": "燃料元素",
    "fluid.vehicle.ender_sap": "末影之液",
    "fluid.vehicle.blaze_juice": "烈焰橙汁",

    "container.fluid_extractor": "流体提取机",
    "container.fluid_mixer": "流体混合器",
    "container.workstation": "车车合成站",
    "container.edit_vehicle.window_help": "单击使移动或旋转哦~",

    "vehicle.info_help": "按下shift获取更多信息哦",
    "tile.vehicle.boost_pad.info": "在加速道上的车车能加速哦!",
    "tile.vehicle.boost_ramp.info": "在加速斜坡上的车车能够加速，进而飙到天上的呢~~！!",
    "tile.vehicle.steep_boost_ramp.info": "在陡峭的加速斜坡上的车车能够加速，进而飙到天上的呢~~！!",
    "tile.vehicle.traffic_cone.info": "交通锥魁梧的高度能够阻止载具前进。当然，你可当做帽子戴上！",
    "tile.vehicle.fluid_pipe.info": "使用此管道输送流体。管道上的灰线表示行进方向。必须首先使用流体泵或任何其他兼容的泵将流体泵入，以使其工作。可以直接使用红石信号禁用管道。",
    "tile.vehicle.fluid_pump.info": "使用此泵将任何兼容的流体存储器中的流体抽取到管道或其他流体存储器中。为使泵工作，它必须使用红石信号启用",
    "tile.vehicle.fuel_drum.info": " 该油桶可用于储存燃料元素或任何其他液体。它具有很强的爆炸性，因此请远离火源。",
    "tile.vehicle.vehicle_crate.info": "一个 %s板条箱. 想要打开板条箱, 只需要用扳手右击顶部.",

    "entity.vehicle.lawn_mower": "割草机",
    "entity.vehicle.mini_bike": "迷你自行车",
    "entity.vehicle.shopping_cart": "购物车",
    "entity.vehicle.speed_boat": "快艇",
    "entity.vehicle.bath": "水上摩托",
    "entity.vehicle.bumper_car": "碰碰车",
    "entity.vehicle.aluminum_boat": "铝合金船",
    "entity.vehicle.dune_buggy": "沙滩车",
    "entity.vehicle.sofacopter": "沙发直升机",
    "entity.vehicle.smart_car": " 小汽车",
    "entity.vehicle.couch": "沙发",
    "entity.vehicle.moped": "助力车",
    "entity.vehicle.off_roader": "越野车",
    "entity.vehicle.sports_plane": "运动飞机",
    "entity.vehicle.golf_cart": "高尔夫球车",
    "entity.vehicle.go_kart": "卡丁车",
    "entity.vehicle.jet_ski": "摩托艇",
    "entity.vehicle.vehicle_trailer": "拖车[载具]",
    "entity.vehicle.atv": "全地形交通工具[越野型沙滩车]",
    "entity.vehicle.storage_trailer": "拖车[物品]",
    "entity.vehicle.seeder": "播种机",
    "entity.vehicle.fertilizer": "施肥机",
    "entity.vehicle.fluid_trailer": "拖车[流体]",
    "entity.vehicle.tractor": "拖拉机",

    "vehicle.config.title": "MrCrayfish's 载具 Mod配置",
    "vehicle.config.client": "客户端",
    "vehicle.config.client.tooltip": "客户端方面配置文件",
    "vehicle.config.client.debug": "调试",
    "vehicle.config.client.debug.tooltip": "用于调试载具模组的配置",
    "vehicle.config.client.debug.render_outlines": "渲染载具边线",
    "vehicle.config.client.debug.render_outlines.tooltip": "设置为 true，将会渲染载具模型所有元素的边线。极为实用的交互调试功能。",
    "vehicle.config.client.debug.raytracer.continuous_reload": "重新加载每个Tick的raytracer",
    "vehicle.config.client.debug.raytracer.continuous_reload.tooltip": "如果为true则每个tick都会重新加载raytracer.\t",
    "vehicle.config.client.interaction": "交互",
    "vehicle.config.client.interaction.tooltip": "载具交互的配置选项",
    "vehicle.config.client.interaction.left_click": "启用左击",
    "vehicle.config.client.interaction.left_click.tooltip": "If true, raytraces will be performed on nearby vehicles when left-clicking the mouse, rather than just right-clicking it. This allows one to be damaged/broken when clicking anywhere on it, rather than just on its bounding box.",
    "vehicle.config.client.display": "显示",
    "vehicle.config.client.display.tooltip": "配置 HUD 元素",
    "vehicle.config.client.display.speedometer": "显示速度仪",
    "vehicle.config.client.display.speedometer.tooltip": "设置为 true，将会在驾驶载具时，在屏幕上显示一个 HUD 速度仪",
    "vehicle.config.client.display.auto_perspective": "自动视角",
    "vehicle.config.client.display.auto_perspective.tooltip": "如果为true，将会在使用载具时自动切换为第三人称",
    "vehicle.config.client.display.workstation_animation": "工作站动画",
    "vehicle.config.client.display.workstation_animation.tooltip": "如果为true，则在工作站中显示载具工作时的动画",
    "vehicle.config.client.controller": "控制",
    "vehicle.config.client.controller.tooltip": "控制支持的配置选项(必须具有可控制的install)",
    "vehicle.config.client.controller.use_triggers": "使用 Triggers",
    "vehicle.config.client.controller.use_triggers.tooltip": "如果为 true, 将会使用controller上的triggers来控制车车加速度.",

    "vehicle.config.server": "服务端",
    "vehicle.config.server.tooltip": "用于服务端方面的配置文件",
    "vehicle.config.server.fuel_enabled": "启用燃料",
    "vehicle.config.server.fuel_enabled.tooltip": "如果为true, 车车需要燃料才能开哦",
    "vehicle.config.server.vehicle_damage": "车车损坏",
    "vehicle.config.server.vehicle_damage.tooltip": "如果为true, 车车会受伤哦.",
    "vehicle.config.server.trailer_detach_threshold": "跟踪脱离阈值",
    "vehicle.config.server.trailer_detach_threshold.tooltip": "拖车会从车上脱离的距离",
    "vehicle.config.server.trailer_sync_cooldown": "拖车同步冷却",
    "vehicle.config.server.trailer_sync_cooldown.tooltip":"将详细信息同步到连接的客户端的tick.这对客户端顺利对拖车移动非常重要.",
    "vehicle.config.server.trailer_inventory_sync_cooldown": "拖车内的物品同步冷却",
    "vehicle.config.server.trailer_inventory_sync_cooldown.tooltip": ".追踪详细信息到连接的客户端需等待的Tick  如果将此值设置为0或更小, inventory不会同时同步,将会更加节约network usage.",
    "vehicle.config.server.pick_up_vehicles": "捡起车",
    "vehicle.config.server.pick_up_vehicles.tooltip": "允许玩家蹲下并右击来捡起车车",
    "vehicle.config.server.max_hose_distance": "最大软管距离",
    "vehicle.config.server.max_hose_distance.tooltip": "软管气泵流体软管断开时的最大距离",

    "vehicle.chat.pump.power": "§b能量模式:§r %s",
    "vehicle.chat.pump.power.off": "人家不想要信号了嘛(需要关闭信号)",
    "vehicle.chat.pump.power.on": "请务必给我信号QAQ(需要信号开启)",
    "vehicle.chat.pump.power.always": "保持激活",

    "vehicle.status.invalid_owner": "你才不是本车的主人呢~~~",
    "vehicle.status.key_added": "啊，车车被这把钥匙上锁了",
    "vehicle.status.key_created": "这把钥匙与本车建立血脉联系了呢",
    "vehicle.status.not_lockable": "车车无法被上锁哦",
    "vehicle.status.key_invalid": "这把钥匙不能用于这辆车    ",
    "vehicle.status.key_removed": "此车没有上锁",

    "vehicle.tooltip.optional": "随意选择",
    "vehicle.tooltip.required": "必需的",
    "vehicle.tooltip.not_applicable": "没有合适的",
    "vehicle.tooltip.paint_color": "上漆",
    "vehicle.tooltip.engine": "发动机",
    "vehicle.tooltip.wheels": "轮子"
}

**Comment by EnterFor** [comment]
我已经在拉去请求上提交了一份。

**Comment by mengdiao** [comment]
哦

**Comment by EnterFor** [comment]
秒回可还行。牛批

**Comment by mengdiao** [comment]
看到邮件了

**Comment by MrCrayfish** [comment]
Merged in https://github.com/MrCrayfish/MrCrayfishVehicleMod/pull/208

**Comment by mengdiao** [comment]
ok,I know------------------ 原始邮件 ------------------
发件人: "MrCrayfish"<notifications@github.com>
发送时间: 2020年3月19日(星期四) 下午2:01
收件人: "MrCrayfish/MrCrayfishVehicleMod"<MrCrayfishVehicleMod@noreply.github.com>;
抄送: "mengdiao"<2507457629@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [MrCrayfish/MrCrayfishVehicleMod] can you add chinese(zh_cn.lang)translate to this mod? (#200)




 
Closed #200.
 
&mdash;
