### ISSUE TITLE
Panel Item Missing

### ISSUE THREAD

**Issue by Pengu-Hunter** [MrCrayfish/MrCrayfishVehicleMod#209]
I don't know if someone else has found this or not but I don't have all the details since I just found it but there is 1.12.2 compatibility problem on the most recent version of the Vehicle mod with another mod that makes the panel item go missing, it still shows up in recipes but doesn't appear in JEI, I'll update if I find the cause.

**Comment by MrCrayfish** [comment]
It could be a recipe conflict. Can you confirm that for me?

**Comment by Halbouny** [comment]
Hey there @MrCrayfish , first of all i love your mods, keep up the great work!
Secondly, i also have the exact problem. I have a custom modpack including 100+mods, couldn't track anything on logs etc.

Can anybody tell me what the original recipe was for the panels? Maybe i can reverse track the issue and find it.

Cheers.

**Comment by Pengu-Hunter** [comment]
Sorry it took so long to come back with a response I just finished testing and Just Enough Vehicles seems to be the cause.
