### ISSUE TITLE
[BUG] Incompatibility with world generation mod

### ISSUE THREAD

**Issue by Akulav** [MrCrayfish/MrCrayfishVehicleMod#218]
Using simple mod like biomes of plenty or in my case "TerraForged" [https://github.com/TerraForged/TerraForged](url), the vehicle mod causes the other mod to fail.

Removing the vehicle mod, solves the issue. 

The issue is not present in singleplayer, but rather only in multiplayer which is odd.
Here is a debug archive which contains: level.dat from both, same world in singleplayer and on a server + the server log.

[Debugs.zip](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4334496/Debugs.zip)

**Comment by MrCrayfish** [comment]
I believe this was a bug in Forge and has been fixed since. https://github.com/MinecraftForge/MinecraftForge/commit/c4b148b84b813db12a0f92334ffd49a03c648236
