### ISSUE TITLE
1.14.4 Spray Cans Randomly Stop Working

### ISSUE THREAD

**Issue by stop-x13** [MrCrayfish/MrCrayfishVehicleMod#219]
It's really hard to tell how to reproduce this bug. 
Potential way to reproduce the bug:
1. Enter a creative world
2. Put down any vehicle
3. Craft a spray can, with any single color
4. Right click the vehicle to change the color
5. If you right click the vehicle with the same spray can, it will do nothing (as expected)
6. But if you do 5 and craft a new spray can (with different color) and try to apply a new color, it stops working (sometimes)
7. Other unknown acts can also randomly make sprays not working. 
8. Doing random things can sometimes make spray cans work once or twice (probably)
Note:
Reopen the world does not help. Relaunch Minecraft sometimes work.
I inspected the log file and debug file and there was no indication of anything wrong happened.
Nothing to do with other mods, because the bug exist even if only this mod and the library are installed.

**Comment by MrCrayfish** [comment]
I can't reproduce. I've tested this myself and it's working as normal.

**Comment by stop-x13** [comment]
> I can't reproduce. I've tested this myself and it's working as normal.
I just tested it again and I couldn't see this bug again. Don't know what really happened yesterday, but it's good to see it works.
