### ISSUE TITLE
[1.12.2 + 0.43.0] Bath is missing a model.

### ISSUE THREAD

**Issue by reepotah** [MrCrayfish/MrCrayfishVehicleMod#220]
Hello. After recent 1.12.2 mod update Bath is missing a model or for some other reason appears as pink-black cube.
In mod version 0.41.1 it was fine.

**Comment by reepotah** [comment]
Upd. Actually every Furniture vehicle has a broken model now.
[That's](https://i.imgur.com/3ZlhcO7.png) bath, couch and sofacopter on my side.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/0fd242d4cda27ea829b7679145af0ef766836178
