### ISSUE TITLE
1.12.2 [version 043.0] Heldvehicle - Client Crash

### ISSUE THREAD

**Issue by Pdan4** [MrCrayfish/MrCrayfishVehicleMod#221]
See log [here](https://paste.dimdev.org/seturinadu.mccrash).

Shortly:

`java.lang.ClassCastException: java.lang.Integer cannot be cast to net.minecraft.nbt.NBTTagCompound
    at com.mrcrayfish.vehicle.client.HeldVehicleEvents.onSetupAngles(HeldVehicleEvents.java:60)`

Just joined our dedicated server and crashed out.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/a5340ec4fe6c5544e16b350c522da41ed332ab8b
I should have an update published soon!

**Comment by Pdan4** [comment]
Thank you! :D
