### ISSUE TITLE
1.12.2 0.43.4 contains wrong model files

### ISSUE THREAD

**Issue by seancrain** [MrCrayfish/MrCrayfishVehicleMod#222]
The texture files contained within the 1.12.2 version of the mod uses 1.13 block names and addresses.

**Comment by MrCrayfish** [comment]
What?

**Comment by seancrain** [comment]
When I downloaded the file earlier, it contained many files from both directory structures. They appear to have been corrected.

This is the reason why: MrCrayFish/MrCrayFishFurnitureMod#253
