### ISSUE TITLE
I found a bug/glitch

### ISSUE THREAD

**Issue by Zjories** [MrCrayfish/MrCrayfishVehicleMod#224]
so i found this bug/glitch where you can see through wals with a Fluid Extractor.
[MRcrayfish mod bug.zip](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4361711/MRcrayfish.mod.bug.zip)

**Comment by MrCrayfish** [comment]
Duplicate of https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/198
