### ISSUE TITLE
Vehicle Crate not opening: vehicle1.12.2-0.43.3 forge1.12.2-14.23.5.2846

### ISSUE THREAD

**Issue by velocityraptor-real** [MrCrayfish/MrCrayfishVehicleMod#226]
I was Playing on a LAN world with my friend, and we weren't able to open a offroader vehicle crate. We did it as the instructions told us (right clicking on top of the crate with a wrench), and also just tried right clicking it. But the vehicle crate did not open.
In Creative the vehicle crate opens automatically and works.
[2020-03-21-7.log.gz](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4362771/2020-03-21-7.log.gz)

[latest.log.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4362775/latest.log.txt)

**Comment by MrCrayfish** [comment]
I will a need detailed method to replicate the issue. Also when you hover the crate in your inventory, does it say the vehicle name?

**Comment by velocityraptor-real** [comment]
Yes, the vehicle contains the offroader inside it. I was able to open the vehicle crate in survival, but not when my LAN world was opened

**Comment by velocityraptor-real** [comment]
Ok.
I now have more of an idea why this issue appeared:
The Modpack I am playing on has several wrenches and my friend right clicked the crate with a industrialcraft2:electric_wrench before I right clicked it with a vehiclemod wrench. The industrialcraft 2 wrench rotated the crate and the crate lost its information, so I wasn't able to open the crate.
I picked the crate up now, and it does not contain a offroader inside it.

I guess this is enough of a solution to the problem and I will just be careful and not use a non-vehiclemod wrench on the crate before opening it in the future.
Thank you for your time!
