### ISSUE TITLE
1.14.4- 0.43.5 not able to pickup vehicles

### ISSUE THREAD

**Issue by LoyaltyGamer72** [MrCrayfish/MrCrayfishVehicleMod#229]
I updated to the new version of your vehicle mod. But now nobody in my server is able to pickup vehicles, they have it updated on client too.

**Comment by KittenKoder** [comment]
The same thing happens in singleplayer as well. I hope this gets fixed before I start my server so I can include this mod.

**Comment by juan-90s** [comment]
yeah, i met the same problem both in multiplayer and singleplayer. Another things I found was that there is not the same problem in 1.15.2.

**Comment by MrCrayfish** [comment]
Fixed in 0.43.6
