### ISSUE TITLE
You take fall damage when landing the plane properly

### ISSUE THREAD

**Issue by CammiePone** [MrCrayfish/MrCrayfishVehicleMod#23]
Yep. Fall damage is taken, as the game still registers the player as falling from whatever height they were at when landing.

Barely in the air:
![image](https://user-images.githubusercontent.com/16853086/42781415-17c6eece-8914-11e8-85a5-03d770c5cde1.png)

Immediate landing:
![image](https://user-images.githubusercontent.com/16853086/42781425-1c6c1d78-8914-11e8-8fc9-0d47334c9333.png)

I know the mod isn't really meant for being played in survival yet, but when you do get around to it, this may prove to be an issue later on, with the plane, and other air vehicles. Keep up the good, though ^-^

**Comment by MrCrayfish** [comment]
This has been fixed in the latest update :)
