### ISSUE TITLE
sofacopter model bug.

### ISSUE THREAD

**Issue by WahlmanPiper** [MrCrayfish/MrCrayfishVehicleMod#231]
I found that the sofacopter in vehicle mod for 1.14.4 (the latest as of 27th march 2020) has the  aluminium boat model as rotor blades instead of the actual rotorblades.

**Comment by MrCrayfish** [comment]
Furniture Mod simply doesn't have the ceiling fan yet for 1.14.4

**Comment by WahlmanPiper** [comment]
Okay, rought it was a import error or a bug (im new to coding so im a total
noob sorry for the inconveniance)

Den fre 27 mars 2020 12:57MrCrayfish <notifications@github.com> skrev:
