### ISSUE TITLE
Can't put fuel in any of the vehicles

### ISSUE THREAD

**Issue by privateVolcano** [MrCrayfish/MrCrayfishVehicleMod#236]
I have tried switching different modes and tried crafting each block and I still cannot of the life of me put fuel in the vehicles. the only way I can get them to move is to be in creative mode. unless I am missing some other step?

**Comment by MrCrayfish** [comment]
Use a Jerry Can or Gas Pump and right click the fuel port on the vehicles

**Comment by privateVolcano** [comment]
I have tried that but I can only get on the vehicle
