### ISSUE TITLE
Jerry Can or gas pump not working! 

### ISSUE THREAD

**Issue by privateVolcano** [MrCrayfish/MrCrayfishVehicleMod#237]
I have right clicked so many times to fuel the vehicles but it is not working at all

**Comment by MrCrayfish** [comment]
Which version of the mod are you using?

**Comment by privateVolcano** [comment]
version 0.43.5 MC version 1.15

**Comment by MrCrayfish** [comment]
Follow this tutorial (https://www.youtube.com/watch?v=0eZbCc2UH2s) otherwise I'm not sure what the problem is because it's worked perfectly for myself and everyone. This issue would be super common if it was actually a problem in the mod.
