### ISSUE TITLE
Cannot place or use items in game.

### ISSUE THREAD

**Issue by Conriocht** [MrCrayfish/MrCrayfishVehicleMod#238]
I've disabled all mods except for the Vehicle Mod and Obfuscate, and even removed all of my resource packs, BUT, I'm not able to use any of the items, like the workstation, etc. If I try to place a workstation down, it immediately disappears. The mod itself loads fine, all the items are there (wheels, engines, crates, etc) but I just can't get going. What am I doing wrong? Am I missing something?

**Comment by MrCrayfish** [comment]
Are you playing singleplayer or on a server?

**Comment by Conriocht** [comment]
I’m playing on Realms.

**Comment by MrCrayfish** [comment]
Yeah realms won't work. You need to run a Forge server
