### ISSUE TITLE
The chest on the MOPED doesn't display well:)

### ISSUE THREAD

**Issue by juan-90s** [MrCrayfish/MrCrayfishVehicleMod#241]
<img width="966" alt="Xnip2020-04-05_22-21-07" src="https://user-images.githubusercontent.com/59337205/78500999-61504a00-778c-11ea-9cdc-a404617db7a3.png">
The current version is 0.43.6-1.14.4, the issue is that the chest doesn't display well. But Players could store items in it.

**Comment by MrCrayfish** [comment]
1.14.4 version will no longer be supported. Sorry
