### ISSUE TITLE
Failed to load on startup

### ISSUE THREAD

**Issue by crescendo12** [MrCrayfish/MrCrayfishVehicleMod#243]
With all the requirements in 1.14.4 (obfuscate, one extra files), it came up with the error message :

MrCrayfish's Vehicle Mod (vehicle) has failed to load correctly
net.minecraft.block.Block.makeCuboidShape(DDDDDD)Lnet/minecraft/util/math/shapes/VoxelShape;

thank you if there is any fix!

**Comment by MrCrayfish** [comment]
I need mod version and forge version

**Comment by crescendo12** [comment]
Obfuscate 0.4.1 for 1.14.4 (with the deobf), tried both 0.43.5 and 0.43.6 with  deobf also installed, and forge 28.2.0

**Comment by alyssaaaaaaaaa** [comment]
I have this problem with 12.2

**Comment by Gando420** [comment]
> With all the requirements in 1.14.4 (obfuscate, one extra files), it came up with the error message :
> 
> MrCrayfish's Vehicle Mod (vehicle) has failed to load correctly
> net.minecraft.block.Block.makeCuboidShape(DDDDDD)Lnet/minecraft/util/math/shapes/VoxelShape;
> 
> thank you if there is any fix!

yes, I have the same issue in forge 1.15.2.
I have obfuscate 0.4.1 and obfuscate 0.4.1 - deobf 
The mod version I'm using is 0.43.5 with 0.43.5- deobf
I would be very grateful for a fix 
thank you

**Comment by alyssaaaaaaaaa** [comment]
is there a fix?

**Comment by MrCrayfish** [comment]
No because no one wants to send a full crash log

**Comment by crescendo12** [comment]
[latest.log](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4491468/latest.log)

**Comment by Gando420** [comment]
Hello Mrcrayfish
I would like to start of by saying I love your videos and mods.

You are asking for a full log and I am happy to give one but I am playing
on my dad's MAC and hes name and other details may be on there so I am
unsure what to do.

Please help
Thank you

**Comment by alyssaaaaaaaaa** [comment]
thank you for replying Mr Crayfish I am a big fan, and it's great to have the honor of talking to you and in my next comment i will give you the log.

**Comment by alyssaaaaaaaaa** [comment]
[fml-client-latest.log](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4495075/fml-client-latest.log)

**Comment by zhilinli1** [comment]
it keep error code 225/255/whatsoever on 1.12.2, on Obfuscate 0.44.1 with any versions of vehicle mod that contains minibus, funny enough that the update log of Obfuscate says "fixed crash while loading world"

**Comment by MrCrayfish** [comment]
1.12.2 and 1.14.4 will no longer be supported.
