### ISSUE TITLE
Cant Steer while driving

### ISSUE THREAD

**Issue by Minecraft2p0** [MrCrayfish/MrCrayfishVehicleMod#245]
The minibus has become really great. Thanks for that. Unfortunately, since the update in 1.12.2, I can no longer steer while driving forward. It works in reverse. Could you fix that? Thank you and hopefully many more vehicles for 1.12.2.

**Comment by Minecraft2p0** [comment]
I tried the mod individually. The problem is still there. It occurs on all tires and engines. But not with the ATV. The steering does not work when driving the lawnmower and tractor.

**Comment by MrCrayfish** [comment]
Going to close because I don't know how to reproduce. Also with such an obvious bug, I feel this is more an issue on your end. Do you have another computer you can test this on? Or even try a different keyboard? Does this happen on 1.16.5?
