### ISSUE TITLE
Vehicles not hitching together

### ISSUE THREAD

**Issue by Liana-Walter** [MrCrayfish/MrCrayfishVehicleMod#247]
So I'm playing on 1.12.2 of this mod and I can't seem to hitch any of the vehicles together.  I've clicked literally everywhere on every vehicle with a hitch and all that happens is I end up either : 

a) accessing the inventory
b) getting on the vehicle
c) picking up the vehicle

I know this is an issue that has been discussed before, and I tried clicking towards the middle of the vehicles with no change in result.  I even reset my keybinds to default hoping to fix the problem.  Nope.  Even spawned in vehicles have the same result.  Not sure what I'm doing wrong and what I need to provide to see if its a bug or me being dumb.  I appreciate any advice and thank you for your time.

Edit : using version 0.43.5, and have also noticed that the Storage vehicle no longer has an inventory.

**Comment by MrCrayfish** [comment]
Only trailers can be hitched to vehicles with a tow bar
