### ISSUE TITLE
[1.12.2]  Sports Plane being pulled down when used in a server

### ISSUE THREAD

**Issue by AtomicLugia** [MrCrayfish/MrCrayfishVehicleMod#248]
When I use a sports plane in my server, it seems that lags pulls my plane down when I try to ascend with it. This doesn't happen when I use my plane in singleplayer. I didn't test this in LAN. The sports plane is equipped with cyan dye and gold-tier engine.

My server has 2 GB RAM allocation and uses the following mods:
BiomesOPlenty-1.12.2-7.0.1.2444-universal
cfm-6.3.0-mc1.12.2
coroutil-1.12.1-1.2.37
CustomNPCs_1.12.2-(01Oct19)
obfuscate-0.4.2-1.12.2
VariedCommodities_1.12.2(21nov19)
vehicle-0.43.4-mc1.12.2
weather2-1.12.1-2.6.12
worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist
Xaeros_Minimap_20.7.1_Forge_1.12

Forge is 1.12.2-14.23.5.2768.

**Comment by Swirren** [comment]
Can confirm. Happens to me as well.

**Comment by ByJumperX4** [comment]
To me as well in 1.16.5, my friend can ascend but not me

**Comment by MrCrayfish** [comment]
No longer maintaining the 1.12,2 version, sorry.
