### ISSUE TITLE
Lawn Mower compatibility with BoP Grass

### ISSUE THREAD

**Issue by shields42** [MrCrayfish/MrCrayfishVehicleMod#250]
The language in my last issue was a little forward. I apologize if I came on a bit too strong.

What I meant to ask was this - would it be difficult to create a list of blocks/entities affected by the Lawn Mower's cutting action in an external config file?

My community loves the vehicles mod and we're huge Crayfish fans. This really is he first vehicles mod that we haven't completely abandoned. The models are flawless (par for the course with Crayfish work) and the implementation is damn near perfect. If you add a donate button to your site, we'd be glad to send a few cups of coffee your way.

**Comment by MrCrayfish** [comment]
Yes, I can look into it!
