### ISSUE TITLE
Fail on opening vehicle crate (server)

### ISSUE THREAD

**Issue by oriolgombau** [MrCrayfish/MrCrayfishVehicleMod#252]
Im in magma server (1.12.2). I got ofuscated and vehicle mod updated to the last version. And I always have the same problem when i'm in server. [IN SOLO works perfectly!]

When I equip the crate of the specific car, it automatically remove his NBT tag. This happends when i try to take a vehicle crate from creative inventory.
If I craft the crate and I open my inventory, the crate's NBT information dissappears. (a nil crate without information in NBT data tag)

What's the problem? Because I have all the mods updated.

I got a video with the problem!

![2020-04-22_19 56 14](https://user-images.githubusercontent.com/45495378/80016728-cbc6f100-84d3-11ea-8470-709160f03e2c.png)
![2020-04-22_19 56 17](https://user-images.githubusercontent.com/45495378/80016738-d1bcd200-84d3-11ea-85b3-9b9d791b5a6b.png)
![2020-04-22_19 56 23](https://user-images.githubusercontent.com/45495378/80016742-d2edff00-84d3-11ea-8073-91390086aba1.png)

**Comment by Sorax5** [comment]
I would have liked to help you but the same thing happens to me but on the CatServer version so we already know that it's not coming from the server version.

**Comment by MrCrayfish** [comment]
Any additional mods? What server software are you using?

**Comment by Sorax5** [comment]
Here is the list of mods I use:
![mod 1](https://user-images.githubusercontent.com/52173496/83965114-89a21500-a8b1-11ea-8947-919bda3b3d48.PNG)

![mod 2](https://user-images.githubusercontent.com/52173496/83965143-cb32c000-a8b1-11ea-90ef-3f4c2c5d1798.PNG)

![mod 3](https://user-images.githubusercontent.com/52173496/83965148-d0900a80-a8b1-11ea-808a-7aced1adc96b.PNG)

And I use the CatServ software mixing plugin and mods.
maybe you want to get the list of plugins too?

**Comment by MrCrayfish** [comment]
Turns out there is nothing I can do. The crates work fine on a normal Forge server. Report to the server software developers that NBT is erased in creative inventory

**Comment by MrCrayfish** [comment]
The same issue happens on Magma https://github.com/magmafoundation/Magma/issues/119

**Comment by LeStegii** [comment]
Just wanted to note that the issue was fixed on magma's side.
It should work in the newest version.
