### ISSUE TITLE
Unintentionally mounting when right-clicking with a vehicle directly behind you [0.20.0]

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishVehicleMod#26]
There is a bug that causes you to automatically mount a vehicle when right-clicking with the vehicle directly behind you. This is happening on my multiplayer server.

**Comment by fandomaniac** [comment]
The bug still exist in version 0.20. It only happens when you are looking up, while right-clicking with the vehicle directly behind you.

**Comment by MrCrayfish** [comment]
Pinging @Phylogeny for this as he knows the raytracing system the best.

**Comment by Phylogeny** [comment]
It actually happens regardless of looking direction. Turns out I screwed up the triangle raytrace algorithm; it was actually doing a trace of the infinite line parallel to the player's eye-centered looking ray. It now actually traces the ray.
