### ISSUE TITLE
[BUG] The boat doesnt work.

### ISSUE THREAD

**Issue by starplatinumzawarudoo** [MrCrayfish/MrCrayfishVehicleMod#264]
So, i spawned the boat and put it in water. I try both front seats and it dont go. Like, if i press W it stays there. I tried with the original motor and still didnt work. I put some oil in the boat, still doesnt work. PS: Sorry for bad english

**Comment by MrCrayfish** [comment]
You need to be in the right seat. If aluminum boat, back left. If jetski, make sure you're right at the front. You can cycle seats by pressing C

**Comment by starplatinumzawarudoo** [comment]
ok i'll try
