### ISSUE TITLE
1.12.2 Shift-Right clicking the Shopping Cart does not push it.

### ISSUE THREAD

**Issue by Vulant** [MrCrayfish/MrCrayfishVehicleMod#265]
I have disabled the server config so that you can't pick up vehicles as I saw in MrCrayfish's youtube comments that this is what would fix the problem. 

It's not working for me though, when I shift-right click the cart, nothing happens. Not sure if the feature was implemented in 1.12.2 but I thought I'd ask anyways.

**Comment by MrCrayfish** [comment]
Not a bug. I removed the feature
