### ISSUE TITLE
Conduits / Pipes / Tubes - Connection

### ISSUE THREAD

**Issue by DaRcCrysys** [MrCrayfish/MrCrayfishVehicleMod#266]
Minecraft Version: 1.12.2
Forge Version: forge-14.23.5.2854
Vehicle Mod Version: vehicle-mod-0.43.5-1.12.2
Obfuscate Version: obfuscate-0.4.2-1.12.2
Environment: Single Player (non LAN & LAN Enabled)

Greetings!  I started toying around with the Vehicle mod today after a friend was showing off all the fun, neat and silly antiques he had been doing around his world.  He was messing around in create move so fuel was not a requirement to his madness, but wanted to take this into a normal survival world and asked could I teach him how to make fuel, and automate it.  I watched your video tutorial and went to work... unfortunately... I have found a slight problem or maybe... just an inconvenience.

Ender IO Item Conduits
Mekanism Logistrical Transporter (Basic, Advanced, Elite and Ultimate have been tested)

The above two (and there maybe more but these are the only ones I have in my pack right now) item based transport tubes do not seem to connect to the Fuel Extractors or the Fuel Mixers.  I can however use Itemduct from Thermal Dynamics.  Mechanic and other liquid pipes seem to interface fine with these blocks to be able to transport the fluids faster... should I choose NOT to use the pumps and fluid pipes.

I have been through the configuration file for the Vehicle mod and didn't see anything in regards to control over this aspect.  I even verified there wasn't a "Compat" API/Library that fixed this.

Is this a bug? Glitch? Maybe there just isn't support?

Any help is appreciated.  Thanks for your time in reading over this, looking forward to more amazing mods and updates.  Hope you and yours are safe!  Take care.

**Comment by MrCrayfish** [comment]
I will no longer be maintaining the 1.12.2 verison of this mod.
