### ISSUE TITLE
the tilting animation is not working

### ISSUE THREAD

**Issue by Pingubot420** [MrCrayfish/MrCrayfishVehicleMod#267]
![problen](https://user-images.githubusercontent.com/65819706/82733435-5e012580-9d1c-11ea-96c9-ce2cbefb9194.png)

**Comment by MrCrayfish** [comment]
You got any additonal mods installed that might be related to the player model?

**Comment by Pingubot420** [comment]
no

**Comment by MrCrayfish** [comment]
Do you literally have any other mods installed? I can notice Optifine/BetterGrass

**Comment by MrCrayfish** [comment]
You're ultimately delaying finding a fix for this because you give little to no details about this issue...

**Comment by Pingubot420** [comment]
yes i have optifine
