### ISSUE TITLE
[MC 1.15.2] Wrong rendering of sofacopter

### ISSUE THREAD

**Issue by winnetrie83** [MrCrayfish/MrCrayfishVehicleMod#268]
The rendering of the sofacopter is rendered wrong.

[Picture](http://g2f.nl/0t1gtta)

The funny part of this is, the boat on the sofacopter also makes a spinning animation when you fly with the sofacopter

Edit: I saw this is already mentioned in https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/231

That issue has been closed, that usually means it has been fixed. It clearly has not.
Please do not close non fixed issues as you may forget to fix them.

**Comment by MrCrayfish** [comment]
I know about the issue because I'm literally notified every day. It can't be fixed until the ceiling fan is added back into the furniture mod.
