### ISSUE TITLE
Is the amount of the drums per data pack changeable?

### ISSUE THREAD

**Issue by cyberpunkbln** [MrCrayfish/MrCrayfishVehicleMod#269]
Hello,

is the amount of the drums per data pack changeable? And when yes, how?

thx

ps: i know it is possible per world/server-config.

**Comment by MrCrayfish** [comment]
Only server config

**Comment by cyberpunkbln** [comment]
thx
is it possible to put the server config in the common-config?

**Comment by cyberpunkbln** [comment]
Since ExtraUtilities2-Drums don't come to 1.15.2 i use tanks, but i love your drums. I try to make your recipe for the drums very expensive and set the amount high. I a modpack server config are a bit impracticable.

Your drums are very cool, when you have time you can make a own drum mod with many drums;)

**Comment by MrCrayfish** [comment]
No, server config is only for the world folder or dedicated server directory.
