### ISSUE TITLE
Server shutdown by putting gas on the new bike and order for servers!

### ISSUE THREAD

**Issue by Smader10** [MrCrayfish/MrCrayfishVehicleMod#270]
Hello, I will be somewhat direct, I do not know much English and therefore it may be poorly translated. I hope you understand:

I was testing the update that you took out of the vehicles in version 44.0, and when filling gasoline to the new vehicle, the game was put on a screen of a light blue color or something and then crashed, this does not happen to me with other vehicles.

And one more thing, I hope it is easy for the next update to put in the (config) of the mod a permission so that **only the owners** of the vehicle can load the car or also that all the cars have their own key, since on a server There may be people who can do bad things, or maybe they can, but I'm not sure how it is done, it would be wonderful if I put it in the answers! Thanks so much for the great mod!

**Comment by PecenyZemiak** [comment]
Same error for me, when trying to refuel new bike

**Comment by MrCrayfish** [comment]
I need a crash log...

**Comment by Smader10** [comment]
I don't know much about programs and I had to translate his comment, I don't know if he was referring exactly to this part of the blocking record:

The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Rendering entity in world

(Very apart from the problem of the motorcycle, I hope you can see your email and can help me with what I put in it, I love it very much)



Crash report notepad:

[crash-2020-05-25_23.30.34-client.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4679907/crash-2020-05-25_23.30.34-client.txt)

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/24ef814f2168a63305884e3851ed37676ef99cea
