### ISSUE TITLE
Dirt Bike will only work accessing it from the front and on the sides near the front.

### ISSUE THREAD

**Issue by UnclassifiedX** [MrCrayfish/MrCrayfishVehicleMod#275]
Tested both 1.12.2 and 1.15.2 versions, both cause the same issue.

Mod Version 1.12: Vehicle Mod v0.44.1 with obfuscate 5.2 (no extra mods alongside it)
Mod Version 1.15: Vehicle Mod v0.44.0 with obfuscate 5.3 (no extra mods alongside it)

You are able to sit on the dirt bike however only if you access it from the front and on the sides near the front will the bike actually work.

Video recorded on the 1.15.2 version (near the end where no smoke was coming out I was holding down W trying to move)
https://youtu.be/ZNBgLkdkOJI

**Comment by MrCrayfish** [comment]
You're sitting in the second seat... Press C to cycle

**Comment by UnclassifiedX** [comment]
Pressing C on 1.12.2 has no effect, 1.15.2 does work with C
