### ISSUE TITLE
Error with Holoinventory

### ISSUE THREAD

**Issue by mxnmnm** [MrCrayfish/MrCrayfishVehicleMod#276]
I was placing down several vehicles to test and I ended up getting kicked
Here's the log
[latest.log](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4699898/latest.log)

**Comment by mxnmnm** [comment]
Also this didn't happen with older versions just so you know

**Comment by MrCrayfish** [comment]
I will no longer be supporting the 1.12.2 version of this mod
