### ISSUE TITLE
 Animation problems occur when installing Vehicle Mod with OptiFine

### ISSUE THREAD

**Issue by FaroukLoubaki** [MrCrayfish/MrCrayfishVehicleMod#277]
I have seen this problem for some people, but it has not been solved yet.
I don't know what the problem is but it is shown in the picture below 
![2020-05-31_10 06 01](https://user-images.githubusercontent.com/66198387/83349242-3ec15400-a32b-11ea-96d7-2e75e8d411ad.png)
![2020-05-31_10 11 46](https://user-images.githubusercontent.com/66198387/83349248-4d0f7000-a32b-11ea-890a-3a2ec05cbc51.png)
![2020-05-31_10 07 29](https://user-images.githubusercontent.com/66198387/83349252-56004180-a32b-11ea-8a54-3d03631e373d.png)
![2020-05-31_10 07 50](https://user-images.githubusercontent.com/66198387/83349257-5ac4f580-a32b-11ea-92b1-1e01ecebc228.png)
When the mod is installed, several problems occur in the game animation
the details :
VehicleMod 0.44
0.4.3 Obfuscate
Minecraft 1.15.2
With OptiFine
Please help me with this problem because this mod is amazing
Even with this problem I will not delete it

**Comment by FaroukLoubaki** [comment]
please MrCrayFish can  you help me !!!!!
or any one

**Comment by FaroukLoubaki** [comment]
Sorry if the writing is not understood, because I am not good at English

**Comment by FaroukLoubaki** [comment]
Sorry if the writing is not understood, because I am not good at English

**Comment by MrCrayfish** [comment]
Can't fix, Optifine overrides code.
