### ISSUE TITLE
 Infinite loop Loading window

### ISSUE THREAD

**Issue by Veijar** [MrCrayfish/MrCrayfishVehicleMod#280]
I am testing version 0.44.0 for 1.15.2, I use forge 31.1.74 and Optifine G1 pre19, it is curious that when starting the game for the first time everything loads without problem, the bad thing happens when I activate or deactivate any shader package (in my case I use SEUS Renewed 1.0.1). when activating or deactivating a shader it stays trying to load the textures, specifically "atlas stitching minecraft textures / atlas / shulker_boxes.png" the game does not crash but never loads again, it only fixes by closing and opening the game again. this only happens with MrCrayfishVehicleMod 0.44.0, I don't report it as crashing but it is a curious bug to mention

**Comment by MrCrayfish** [comment]
Optifine is not 100% compatible with Forge.
