### ISSUE TITLE
Craches when changing perspective with F5.( I don't know if it is in combination with Flans mod.)

### ISSUE THREAD

**Issue by Drsang** [MrCrayfish/MrCrayfishVehicleMod#281]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 6/2/20 1:25 PM
Description: Rendering entity in world

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.getPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.patchPlayerRender(HeldVehicleEvents.java:46)
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.onRenderPlayer(HeldVehicleEvents.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_HeldVehicleEvents_onRenderPlayer_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.patchPlayerRender(HeldVehicleEvents.java:46)
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.onRenderPlayer(HeldVehicleEvents.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_HeldVehicleEvents_onRenderPlayer_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)

-- Entity being rendered --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 321
	Entity Name: DR_Sang
	Entity's Exact location: -137.67, 68.20, 266.12
	Entity's Block location: World: (-138,68,266), Chunk: (at 6,4,10 in -9,16; contains blocks -144,0,256 to -129,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderPlayer@6421d9dc
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 2.1518514
	Delta: 0.14000905
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DR_Sang'/321, l='MpServer', x=-137.67, y=68.20, z=266.12]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-136,64,248), Chunk: (at 8,4,8 in -9,15; contains blocks -144,0,240 to -129,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 7531 game time, 7531 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 70 total; [EntityBat['Bat'/258, l='MpServer', x=-57.24, y=19.06, z=313.86], EntityEnderman['Enderman'/131, l='MpServer', x=-207.27, y=20.00, z=208.49], EntityCreeper['Creeper'/132, l='MpServer', x=-205.54, y=24.00, z=242.44], EntityCreeper['Creeper'/133, l='MpServer', x=-196.50, y=24.00, z=234.50], EntitySkeleton['Skeleton'/134, l='MpServer', x=-199.50, y=24.00, z=233.50], EntitySkeleton['Skeleton'/135, l='MpServer', x=-196.79, y=24.00, z=237.44], EntitySheep['Sheep'/136, l='MpServer', x=-196.19, y=70.00, z=241.53], EntityZombie['Zombie'/137, l='MpServer', x=-197.50, y=35.00, z=299.50], EntitySheep['Sheep'/138, l='MpServer', x=-202.50, y=67.00, z=299.50], EntityCreeper['Creeper'/139, l='MpServer', x=-207.50, y=28.00, z=313.50], EntityPig['Pig'/141, l='MpServer', x=-198.45, y=69.00, z=304.51], EntitySheep['Sheep'/142, l='MpServer', x=-193.73, y=71.00, z=309.49], EntityZombie['Zombie'/146, l='MpServer', x=-194.53, y=49.00, z=333.74], EntitySkeleton['Skeleton'/153, l='MpServer', x=-184.45, y=50.00, z=216.05], EntitySpider['Spider'/154, l='MpServer', x=-183.00, y=50.00, z=212.03], EntitySpider['Spider'/155, l='MpServer', x=-181.07, y=53.00, z=216.71], EntityZombie['Zombie'/156, l='MpServer', x=-179.50, y=53.00, z=211.50], EntitySkeleton['Skeleton'/157, l='MpServer', x=-187.50, y=51.00, z=224.50], EntitySkeleton['Skeleton'/158, l='MpServer', x=-190.33, y=51.00, z=225.50], EntitySheep['Sheep'/159, l='MpServer', x=-181.77, y=74.00, z=227.52], EntitySheep['Sheep'/160, l='MpServer', x=-189.18, y=73.00, z=233.45], EntitySheep['Sheep'/161, l='MpServer', x=-177.75, y=72.00, z=230.52], EntitySkeleton['Skeleton'/167, l='MpServer', x=-166.50, y=12.00, z=191.50], EntityCreeper['Creeper'/168, l='MpServer', x=-170.22, y=57.00, z=196.58], EntitySkeleton['Skeleton'/169, l='MpServer', x=-160.50, y=40.00, z=215.50], EntitySkeleton['Skeleton'/170, l='MpServer', x=-171.28, y=55.00, z=219.47], EntitySheep['Sheep'/171, l='MpServer', x=-163.38, y=75.97, z=318.46], EntityBat['Bat'/172, l='MpServer', x=-157.98, y=33.74, z=343.17], EntityCreeper['Creeper'/181, l='MpServer', x=-145.50, y=55.00, z=200.50], EntityZombie['Zombie'/182, l='MpServer', x=-158.50, y=40.00, z=211.50], EntitySheep['Sheep'/183, l='MpServer', x=-157.83, y=74.00, z=316.55], EntityBat['Bat'/184, l='MpServer', x=-146.65, y=36.58, z=321.11], EntitySheep['Sheep'/185, l='MpServer', x=-153.92, y=79.00, z=326.05], EntitySheep['Sheep'/186, l='MpServer', x=-157.50, y=79.00, z=320.27], EntityZombie['Zombie'/188, l='MpServer', x=-136.50, y=55.00, z=203.50], EntityZombie['Zombie'/189, l='MpServer', x=-134.50, y=55.00, z=206.50], EntityBat['Bat'/190, l='MpServer', x=-138.39, y=15.32, z=253.60], EntityBat['Bat'/191, l='MpServer', x=-132.42, y=37.15, z=324.89], EntityPlayerSP['DR_Sang'/321, l='MpServer', x=-137.67, y=68.20, z=266.12], EntityCreeper['Creeper'/208, l='MpServer', x=-125.50, y=16.00, z=251.50], EntityZombie['Zombie'/217, l='MpServer', x=-98.50, y=19.00, z=211.50], EntityCreeper['Creeper'/218, l='MpServer', x=-104.50, y=9.00, z=242.50], EntityCreeper['Creeper'/219, l='MpServer', x=-102.50, y=9.00, z=242.50], EntityCreeper['Creeper'/220, l='MpServer', x=-104.50, y=9.00, z=243.50], EntityZombie['Zombie'/221, l='MpServer', x=-98.51, y=23.00, z=282.30], EntityZombie['Zombie'/222, l='MpServer', x=-100.50, y=23.00, z=276.50], EntityChicken['Chicken'/223, l='MpServer', x=-102.42, y=67.00, z=289.86], EntitySheep['Sheep'/229, l='MpServer', x=-84.26, y=67.00, z=256.37], EntitySheep['Sheep'/230, l='MpServer', x=-79.75, y=67.00, z=254.91], EntityChicken['Chicken'/231, l='MpServer', x=-94.18, y=69.00, z=284.72], EntityBat['Bat'/232, l='MpServer', x=-91.44, y=21.36, z=289.65], EntityChicken['Chicken'/233, l='MpServer', x=-89.29, y=68.00, z=290.82], EntityItem['item.item.egg'/234, l='MpServer', x=-89.27, y=67.00, z=291.72], EntityZombie['Zombie'/111, l='MpServer', x=-208.50, y=27.00, z=249.50], EntitySheep['Sheep'/240, l='MpServer', x=-65.45, y=64.00, z=196.26], EntityBat['Bat'/113, l='MpServer', x=-202.54, y=32.71, z=279.39], EntitySkeleton['Skeleton'/241, l='MpServer', x=-75.50, y=15.00, z=243.50], EntityCreeper['Creeper'/242, l='MpServer', x=-69.85, y=15.00, z=248.50], EntityChicken['Chicken'/243, l='MpServer', x=-72.62, y=67.00, z=293.17], EntitySkeleton['Skeleton'/244, l='MpServer', x=-79.50, y=31.00, z=305.50], EntityBat['Bat'/116, l='MpServer', x=-217.34, y=39.87, z=274.81], EntitySkeleton['Skeleton'/245, l='MpServer', x=-77.50, y=45.00, z=320.50], EntityCreeper['Creeper'/118, l='MpServer', x=-217.44, y=35.00, z=293.15], EntitySpider['Spider'/246, l='MpServer', x=-69.61, y=44.00, z=328.30], EntitySheep['Sheep'/120, l='MpServer', x=-212.50, y=68.00, z=285.44], EntitySheep['Sheep'/121, l='MpServer', x=-213.44, y=68.00, z=294.86], EntityZombieVillager['Zombie Villager'/122, l='MpServer', x=-211.50, y=28.00, z=316.50], EntitySpider['Spider'/123, l='MpServer', x=-209.18, y=27.00, z=309.70], EntityCreeper['Creeper'/124, l='MpServer', x=-211.06, y=28.00, z=315.38], EntityCreeper['Creeper'/125, l='MpServer', x=-209.50, y=46.00, z=337.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1382668120 bytes (1318 MB) / 2717908992 bytes (2592 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 7 total; -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                 | Version      | Source                        | Signature                                |
	|:--------- |:------------------ |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft          | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJAAAA | mcp                | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJAAAA | FML                | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge              | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | obfuscate          | 0.4.2        | minecraft.jar                 | None                                     |
	| UCHIJAAAA | flansmod           | 5.5.2        | Flan's Mod-1.12.2-5.5.2.jar   | None                                     |
	| UCHIJAAAA | flansmodapocalypse | 1.0          | Flan's Mod-1.12.2-5.5.2.jar   | None                                     |
	| UCHIJAAAA | vehicle            | 0.44.1       | vehicle-0.44.1-mc1.12.2.jar   | None                                     |

	Loaded coremods (and transformers): 
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-12.4.7' Renderer: 'Intel(R) Iris(TM) Graphics 650'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.2
	OpenGL: Intel(R) Iris(TM) Graphics 650 GL version 2.1 INTEL-12.4.7, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz

**Comment by UnclassifiedX** [comment]
Tested your forge version and mods. It crashes on your forge version, you need to update forge to the latest version and this perspective issue will be fixed.

**Comment by MrCrayfish** [comment]
I will no longer be maintaining the 1.12.2 verison of this mod
