### ISSUE TITLE
[Suggestion] Buildcraft fuel implementation

### ISSUE THREAD

**Issue by husky2331** [MrCrayfish/MrCrayfishVehicleMod#284]
Hey, I'm wondering if it's possible to implement fuel from Buildcraft to your vehicle mod, I know fuel is already in the mod, but it would have been very nice if it could be done. Also when I first saw the fuel update I was absolutely blown away by how amazing it is.

**Comment by StormbringerGTX** [comment]
Would like to add my support for this.
Immersive Petroleum and Immersive engineering add Diesel, Gasoline and Bio-Diesel. Allowing us to add those via configuration would be amazing!

**Comment by MrCrayfish** [comment]
Duplicate of https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/64
Feature is coming in 1.16 though

**Comment by TheLionWithATie** [comment]
I believe this feature is not working in 1.16.5.
In both the server and general config the entry for the "customFuels" is missing and in-game, the immersive petroleum diesel doesn't seem to work.

**Comment by MrCrayfish** [comment]
"Feature is coming". It's coming in the next update. Development can be followed at https://discord.gg/mrcrayfish
