### ISSUE TITLE
{PLEASE HELP} every time i try to get in a vehicle my game makes a sound and crashes immediately 

### ISSUE THREAD

**Issue by Limberr** [MrCrayfish/MrCrayfishVehicleMod#285]
every time i try to get in a vehicle my game makes a sound and crashes immediately. I do not know what to do. I am running modern warfare mod, obfuscate, and furniture mod along side it.
here's the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  weaponlib (mw_2.0-0.4.4.6_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 6/13/20 11:31 PM
Description: Rendering entity in world

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.getPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.patchPlayerRender(HeldVehicleEvents.java:46)
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.onRenderPlayer(HeldVehicleEvents.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_98_HeldVehicleEvents_onRenderPlayer_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.patchPlayerRender(HeldVehicleEvents.java:46)
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.onRenderPlayer(HeldVehicleEvents.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_98_HeldVehicleEvents_onRenderPlayer_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)

-- Entity being rendered --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 224
	Entity Name: Limberbarkk
	Entity's Exact location: -123.27, 70.00, -449.34
	Entity's Block location: World: (-124,70,-450), Chunk: (at 4,4,14 in -8,-29; contains blocks -128,0,-464 to -113,255,-449), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: EntityGoKart['Go Kart'/225, l='MpServer', x=-124.50, y=70.00, z=-449.50]

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderPlayer@564d66e6
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 107.550125
	Delta: 0.6599914
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Limberbarkk'/224, l='MpServer', x=-123.27, y=70.00, z=-449.34]]
	Chunk stats: MultiplayerChunkCache: 961, 961
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (228,64,140), Chunk: (at 4,4,12 in 14,8; contains blocks 224,0,128 to 239,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 15421 game time, 15421 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 104 total; [EntityZombie['Zombie'/547, l='MpServer', x=-141.64, y=72.00, z=-529.34], EntityZombie['Zombie'/548, l='MpServer', x=-138.52, y=72.00, z=-522.81], EntitySkeleton['Skeleton'/549, l='MpServer', x=-161.70, y=74.67, z=-498.51], EntityBat['Bat'/550, l='MpServer', x=-138.75, y=48.95, z=-513.80], EntityBat['Bat'/551, l='MpServer', x=-140.50, y=50.02, z=-499.75], EntityPig['Pig'/552, l='MpServer', x=-131.75, y=70.00, z=-509.44], EntityZombie['Zombie'/553, l='MpServer', x=-145.50, y=71.00, z=-477.50], EntityPig['Pig'/554, l='MpServer', x=-159.74, y=84.00, z=-475.56], EntityPig['Pig'/555, l='MpServer', x=-145.62, y=71.17, z=-454.62], EntitySkeleton['Skeleton'/556, l='MpServer', x=-148.83, y=67.15, z=-438.54], EntityPig['Pig'/557, l='MpServer', x=-140.49, y=70.02, z=-459.71], EntityCow['Cow'/583, l='MpServer', x=-141.19, y=69.00, z=-384.48], EntityCreeper['Creeper'/584, l='MpServer', x=-137.50, y=69.00, z=-396.50], EntityCow['Cow'/585, l='MpServer', x=-139.84, y=69.00, z=-378.36], EntityCow['Cow'/586, l='MpServer', x=-140.50, y=67.00, z=-371.50], EntityPig['Pig'/592, l='MpServer', x=-121.28, y=70.00, z=-498.50], EntityCreeper['Creeper'/610, l='MpServer', x=-107.22, y=71.00, z=-478.14], EntityZombie['Zombie'/628, l='MpServer', x=-124.50, y=68.00, z=-405.50], EntityItem['item.item.seeds'/629, l='MpServer', x=-91.54, y=69.00, z=-434.68], EntityBat['Bat'/631, l='MpServer', x=-92.25, y=21.76, z=-415.87], EntityCreeper['Creeper'/632, l='MpServer', x=-80.50, y=69.00, z=-420.50], EntityZombie['Zombie'/633, l='MpServer', x=-106.50, y=66.00, z=-410.50], EntitySkeleton['Skeleton'/636, l='MpServer', x=-82.50, y=69.00, z=-415.50], EntitySkeleton['Skeleton'/637, l='MpServer', x=-96.79, y=68.00, z=-384.59], EntityPig['Pig'/893, l='MpServer', x=-53.23, y=67.00, z=-415.31], EntityPig['Pig'/895, l='MpServer', x=-46.87, y=65.00, z=-407.41], EntityZombie['Zombie'/652, l='MpServer', x=-111.50, y=23.00, z=-528.50], EntityBat['Bat'/654, l='MpServer', x=-100.91, y=27.00, z=-510.48], EntitySkeleton['Skeleton'/656, l='MpServer', x=-109.50, y=26.00, z=-511.50], EntityPig['Pig'/657, l='MpServer', x=-102.26, y=68.00, z=-506.46], EntitySkeleton['Skeleton'/658, l='MpServer', x=-78.49, y=70.00, z=-525.73], EntityBat['Bat'/915, l='MpServer', x=-47.29, y=53.56, z=-377.53], EntityBat['Bat'/660, l='MpServer', x=-87.35, y=21.09, z=-513.41], EntitySkeleton['Skeleton'/661, l='MpServer', x=-95.52, y=33.00, z=-512.32], EntityZombie['Zombie'/662, l='MpServer', x=-86.50, y=27.00, z=-497.50], EntityPig['Pig'/407, l='MpServer', x=-178.50, y=85.00, z=-484.50], EntityItem['item.item.seeds'/663, l='MpServer', x=-89.13, y=68.00, z=-511.13], EntityPig['Pig'/408, l='MpServer', x=-176.23, y=89.00, z=-488.49], EntityPig['Pig'/664, l='MpServer', x=-93.50, y=67.00, z=-513.34], EntitySkeleton['Skeleton'/665, l='MpServer', x=-107.50, y=54.00, z=-494.50], EntityCreeper['Creeper'/666, l='MpServer', x=-102.50, y=51.00, z=-493.50], EntityPig['Pig'/667, l='MpServer', x=-101.84, y=69.00, z=-460.32], EntityPig['Pig'/412, l='MpServer', x=-176.45, y=82.00, z=-471.47], EntityBat['Bat'/668, l='MpServer', x=-75.73, y=23.02, z=-478.90], EntityPig['Pig'/413, l='MpServer', x=-177.64, y=82.00, z=-476.26], EntityCreeper['Creeper'/669, l='MpServer', x=-77.83, y=40.00, z=-472.53], EntityPig['Pig'/414, l='MpServer', x=-181.51, y=80.00, z=-466.72], EntityPig['Pig'/670, l='MpServer', x=-78.60, y=70.00, z=-473.51], EntityPig['Pig'/671, l='MpServer', x=-70.78, y=69.00, z=-477.82], EntityPig['Pig'/672, l='MpServer', x=-77.51, y=69.00, z=-482.78], EntityPig['Pig'/673, l='MpServer', x=-79.22, y=70.00, z=-481.49], EntityBat['Bat'/420, l='MpServer', x=-197.30, y=55.08, z=-407.47], EntityCow['Cow'/423, l='MpServer', x=-197.20, y=73.00, z=-413.47], EntityCow['Cow'/435, l='MpServer', x=-182.23, y=72.00, z=-407.53], EntityCow['Cow'/436, l='MpServer', x=-183.60, y=70.00, z=-404.09], EntityZombie['Zombie'/441, l='MpServer', x=-192.56, y=68.00, z=-395.26], EntitySkeleton['Skeleton'/697, l='MpServer', x=-65.50, y=67.00, z=-461.50], EntitySkeleton['Skeleton'/442, l='MpServer', x=-194.50, y=68.00, z=-380.50], EntitySkeleton['Skeleton'/698, l='MpServer', x=-55.50, y=69.00, z=-487.50], EntityZombie['Zombie'/443, l='MpServer', x=-180.50, y=74.00, z=-377.50], EntityCreeper['Creeper'/699, l='MpServer', x=-60.44, y=69.00, z=-478.83], EntityBat['Bat'/700, l='MpServer', x=-50.44, y=34.10, z=-456.76], EntityBat['Bat'/701, l='MpServer', x=-49.68, y=33.61, z=-454.92], EntityPig['Pig'/702, l='MpServer', x=-64.50, y=68.00, z=-434.50], EntityPig['Pig'/703, l='MpServer', x=-64.50, y=67.00, z=-435.50], EntityPig['Pig'/704, l='MpServer', x=-58.68, y=66.00, z=-432.48], EntityChicken['Chicken'/705, l='MpServer', x=-69.54, y=70.00, z=-445.23], EntityChicken['Chicken'/706, l='MpServer', x=-75.16, y=70.00, z=-435.44], EntityChicken['Chicken'/707, l='MpServer', x=-66.50, y=68.00, z=-439.50], EntityChicken['Chicken'/708, l='MpServer', x=-71.60, y=70.00, z=-433.07], EntityPig['Pig'/453, l='MpServer', x=-203.50, y=73.00, z=-520.75], EntityPig['Pig'/709, l='MpServer', x=-65.22, y=68.00, z=-419.51], EntityPig['Pig'/454, l='MpServer', x=-198.94, y=78.00, z=-515.52], EntityZombie['Zombie'/710, l='MpServer', x=-79.53, y=69.36, z=-424.32], EntityCreeper['Creeper'/711, l='MpServer', x=-69.47, y=16.00, z=-403.81], EntityCreeper['Creeper'/712, l='MpServer', x=-67.99, y=18.00, z=-407.33], EntitySpider['Spider'/713, l='MpServer', x=-68.29, y=18.00, z=-393.71], EntitySkeleton['Skeleton'/714, l='MpServer', x=-66.50, y=16.00, z=-402.50], EntitySkeleton['Skeleton'/715, l='MpServer', x=-70.75, y=69.00, z=-412.61], EntityPig['Pig'/460, l='MpServer', x=-203.50, y=74.00, z=-480.50], EntityPig['Pig'/716, l='MpServer', x=-52.30, y=67.00, z=-408.24], EntityZombie['Zombie'/461, l='MpServer', x=-202.50, y=64.00, z=-489.50], EntitySkeleton['Skeleton'/717, l='MpServer', x=-69.27, y=16.00, z=-398.49], EntityCreeper['Creeper'/718, l='MpServer', x=-62.87, y=18.00, z=-389.83], EntitySkeleton['Skeleton'/719, l='MpServer', x=-51.35, y=64.00, z=-387.79], EntityGoKart['Go Kart'/225, l='MpServer', x=-124.50, y=70.00, z=-449.50], EntityZombie['Zombie'/738, l='MpServer', x=-49.29, y=33.92, z=-520.50], EntityBat['Bat'/741, l='MpServer', x=-48.42, y=32.58, z=-498.66], EntityCreeper['Creeper'/746, l='MpServer', x=-172.50, y=69.00, z=-391.50], EntityCreeper['Creeper'/747, l='MpServer', x=-169.84, y=68.00, z=-395.52], EntityPig['Pig'/498, l='MpServer', x=-171.70, y=88.00, z=-486.47], EntityPig['Pig'/499, l='MpServer', x=-175.45, y=83.00, z=-480.55], EntityPig['Pig'/500, l='MpServer', x=-175.24, y=89.00, z=-488.49], EntityPig['Pig'/501, l='MpServer', x=-170.49, y=87.00, z=-484.03], EntityPig['Pig'/502, l='MpServer', x=-165.53, y=86.00, z=-480.25], EntityPig['Pig'/503, l='MpServer', x=-172.67, y=83.00, z=-479.50], EntityZombie['Zombie'/504, l='MpServer', x=-170.45, y=83.00, z=-472.49], EntityCreeper['Creeper'/505, l='MpServer', x=-172.50, y=14.00, z=-443.50], EntityEnderman['Enderman'/506, l='MpServer', x=-170.50, y=14.00, z=-442.50], EntityPlayerSP['Limberbarkk'/224, l='MpServer', x=-123.27, y=70.00, z=-449.34], EntityBat['Bat'/507, l='MpServer', x=-156.55, y=17.87, z=-419.95], EntityBat['Bat'/508, l='MpServer', x=-153.24, y=17.02, z=-415.57], EntityCow['Cow'/509, l='MpServer', x=-169.78, y=66.00, z=-403.57], EntityCreeper['Creeper'/510, l='MpServer', x=-160.83, y=65.00, z=-399.72]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 815381040 bytes (777 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID        | Version      | Source                        | Signature                                |
	|:--------- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJAAAA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJAAAA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2772.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge     | 14.23.5.2772 | forge-1.12.2-14.23.5.2772.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | obfuscate | 0.2.6        | minecraft.jar                 | None                                     |
	| UCHIJAAAA | cfm       | 6.3.1        | furniture-6.3.1-1.12.2.jar    | None                                     |
	| UCHIJAAAA | mw        | 0.4.4.6      | mw_2.0-0.4.4.6_mc1.12.2.jar   | None                                     |
	| UCHIJAAAA | vehicle   | 0.44.1       | vehicle-0.44.1-mc1.12.2.jar   | None                                     |

	Loaded coremods (and transformers): 
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
weaponlib (mw_2.0-0.4.4.6_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.5018' Renderer: 'Intel(R) UHD Graphics 630'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2772
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 630 GL version 4.5.0 - Build 23.20.16.5018, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

**Comment by UnclassifiedX** [comment]
Update your forge and obfuscate version and try again.

**Comment by 5UP3RTH30B4G** [comment]
le meme
