### ISSUE TITLE
Camera view change while entering vehicles messes up vivecraft

### ISSUE THREAD

**Issue by LordPensington** [MrCrayfish/MrCrayfishVehicleMod#286]
I am using this mod with vivecraft 1.12.2 
as soon as I enter a vehicle, the forced camera view change is messing up the view in VR. Even after leaving the vehicle, it seems not to be possible to revert that state.
Is there a way to deactivate the forced view change?

**Comment by LordPensington** [comment]
NVM. I found the setting. Still this mod unfortunately does not support VR very well. Even though that would be awesome.

**Comment by MrCrayfish** [comment]
Why do you expect it to support VR? Nobody designs their mods for VR.
