### ISSUE TITLE
Bath and shopping cart not working without fuel

### ISSUE THREAD

**Issue by mxnmnm** [MrCrayfish/MrCrayfishVehicleMod#289]
I know you mentioned previously that the bath doesn't need fuel but it doesn't work in survival and the only thing I can think of is it needing fuel. It also shows the fuel numbers 0/15000.

Same thing with the shopping cart (I doubt it needs fuel because well it's a shopping cart lol) although that one shows 0/0 fuel

This is for 1.12.2

**Comment by andersonarc** [comment]
This would be a nice feature. However, since it is not implemented, I suggest you to use a workaround with commands and NBT tags. For example, to create a Bath vehicle without fuel required, you can type "/summon vehicle:bath ~ ~ ~ {requiresFuel:0b}"

**Comment by Swirren** [comment]
Can confirm. This happens to me as well.

**Comment by MrCrayfish** [comment]
I will no longer be maintaining the 1.12.2 version of this mod. Unfortunately said vehicles are actually be removed from the mod in an upcoming update and moved to a seperate addon. This is becuase they don't fit into the mod. More information can be found on my discord: https://discord.gg/mrcrayfish
