### ISSUE TITLE
Vehicle throwing crash

### ISSUE THREAD

**Issue by OstenTV** [MrCrayfish/MrCrayfishVehicleMod#29]
When you pick up a vehicle and throw it again, you crash.
https://file.ostentv.dk/GitHub/Vehicle-Mod/%2329/Desktop%202018.07.28%20-%2021.29.54.02.mp4
There is no crash report.

Edit: You also can't pick up the trailer on a server.

**Comment by Kewin05c** [comment]
Same and i still have this problem

**Comment by MrCrayfish** [comment]
Fixed and fixed. Coming in v0.20.0
