### ISSUE TITLE
car texture glitch

### ISSUE THREAD

**Issue by lpshoneyheart** [MrCrayfish/MrCrayfishVehicleMod#290]
I half to restart my entire game every now and then bc the texture breaks for me.
rejoining the game does nothing without a restart

**Comment by MrCrayfish** [comment]
Provide a screenshot or I am closing the issue

**Comment by Saunokki** [comment]
![2020-08-10_21 18 18](https://user-images.githubusercontent.com/69479251/89816327-0d48de00-db4f-11ea-84ef-c78be798cfd5.png)

**Comment by MrCrayfish** [comment]
Optifine...
