### ISSUE TITLE
Cars and Portals

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/MrCrayfishVehicleMod#292]
Forge: x.2854
Vehicle mod: 0.44.1
Draconic Evolution: 2.3.25.351

Issue: When riding a vehicle through a DE portal between dimensions either it will work as expected or the following happens:
-you get put at a location that isn't the intended destnation
-your camera becomes glitched out ~30 blocks or so up
-you cannot exit the vehicle
A relog fixes 2 and 3

I can ride entities from other mods (such as a sheep from the animalbikes mod) through just fine, so it's not riding entities in general making things wig out.

The only thing in logs is the following:
[00:58:35] [Server thread/WARN] [net.minecraft.network.NetHandlerPlayServer]: Smart Car moved wrongly!
checked debug too, same thing.

**Comment by MrCrayfish** [comment]
I will no longer be supporting 1.12.2
