### ISSUE TITLE
Pickup events

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/MrCrayfishVehicleMod#294]
Using latest versions of forge and the affected mods from curseforge as of this posting.

When this mod is used with carryon (lets you pick up most all entities) and the default key of shift is used for carryon, when a vehicle is picked up you end up with weird things happening including:
-ghost vehicles
-duplicated fake vehicles
-REAL duplication of head armor (when placing down a block from the hotbar it will be replaced with a duplicate of whatever was on your head, which can be very cheaty in a pack with project e).

Possible fixes:
-Cancel the event from carryon when a vehicle is targeted
-use a different key

**Comment by MrCrayfish** [comment]
Turn off "pickUpVehicles" in vehicle-server.toml to fix the issue. I can't make my mod 100% compatible with every single mod.
