### ISSUE TITLE
Crashing when trying to create a world

### ISSUE THREAD

**Issue by neoner-KRZG** [MrCrayfish/MrCrayfishVehicleMod#297]
[crash-2020-06-26_18.13.58-client.txt]
(https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4837724/crash-2020-06-26_18.13.58-client.txt)

Downloaded from Curse, tried to reinstall Obfuscate and Vehicle mod

Version: 1.12.2

**Comment by neoner-KRZG** [comment]
[crash-2020-06-26_18.13.58-client.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4837721/crash-2020-06-26_18.13.58-client.txt)

**Comment by zhilinli1** [comment]
Same, need help!

**Comment by lazytspo** [comment]
Same thing. Please Help!~!

**Comment by seanyih** [comment]
Same!! Need help~~~~

**Comment by MrCrayfish** [comment]
No longer supporting 1.12.2
