### ISSUE TITLE
Ender sap not pumping

### ISSUE THREAD

**Issue by CommissarSalty** [MrCrayfish/MrCrayfishVehicleMod#299]
1.15.2
Pipes are going into the right hole.
Pipes are facing the right direction.
Pump is powered and facing proper direction
Only mods that might be causing a problem are Silent's mechanisms and iron jetpacks.
![bug](https://user-images.githubusercontent.com/67489948/85911347-9099b480-b7d9-11ea-84f0-ad780273155a.jpg)
![bug2](https://user-images.githubusercontent.com/67489948/85911365-a7d8a200-b7d9-11ea-8cb2-169e687b7411.jpg)

**Comment by MrCrayfish** [comment]
I've tested with the exact setup and it's working on my end. Maybe you changed the mode of the pump by right clicking it with a wrench. Can you try an isolated test by only installing the vehicle mod?

**Comment by CommissarSalty** [comment]
> I've tested with the exact setup and it's working on my end. Maybe you changed the mode of the pump by right clicking it with a wrench. Can you try an isolated test by only installing the vehicle mod?

I've done multiple tests on superflats. I've come to the conclusion that its probably the world itself.

**Comment by MrCrayfish** [comment]
Strange. That shouldn't be the case. Will close this for now. Let me know if this happens on newer version of the mod (1.16 or above).
