### ISSUE TITLE
Galacticraft [Animation with the character and vehicles]

### ISSUE THREAD

**Issue by VictorAlonsoo** [MrCrayfish/MrCrayfishVehicleMod#301]
Forge: 14.23.5.2854 
Vehicle: vehicle-mod-0.44.1-1.12.2.jar
Galacticraft: GalacticraftCore-1.12.2-4.0.2.280.jar +  accessories

**When loading a vehicle or going up, animations are lost.**

**Comment by MrCrayfish** [comment]
I can't do anything. Galacticraft overrides the player rendering system.
