### ISSUE TITLE
No configuration file or command for settings on server

### ISSUE THREAD

**Issue by lululombard** [MrCrayfish/MrCrayfishVehicleMod#302]
Hey guys, I might sound dumb but I can't find how to disable vehicle damage on my forge-1.15.2-31.2.27 server. I even tried to read the source code, I know the parameter is `vehicleDamage` and it's a boolean, but I can't find how to update that value to false. I can't find any config file related to the vehicle mod in my `config` folder, and I can't find any command related to the mod. Can someone help me? Thanks.

**Comment by MrCrayfish** [comment]
It should be in ```config/vehicle-common.toml``` or ```server-config/vehicle-server.toml```

**Comment by lululombard** [comment]
I just checked, the `config` directory is populated with other mods configs but there's no `vehicle-common.toml` file, and there's no `server-config` directory at all :/

**Comment by lululombard** [comment]
Nevermind, someone told me on Discord, it's in `world/serverconfig/vehicle-server.toml`
