### ISSUE TITLE
vehicles look strange

### ISSUE THREAD

**Issue by Maksu2738** [MrCrayfish/MrCrayfishVehicleMod#303]
Vehicle mod, obfuscate and forge latest versions installed but the tools look weird can you help me? (I am sorry for my English)

a few photos
![Adsız](https://user-images.githubusercontent.com/67859498/86530550-45129500-bec2-11ea-8dd6-d14598e1beab.png)
![Adsız1](https://user-images.githubusercontent.com/67859498/86530553-46dc5880-bec2-11ea-93ca-7d90cfcd1a88.png)
![Adsız 2](https://user-images.githubusercontent.com/67859498/86530578-87d46d00-bec2-11ea-8a8f-7b254c3afcd0.png)

**Comment by MrCrayfish** [comment]
Optifine

**Comment by Maksu2738** [comment]
Do I need to install optifine?

**Comment by Maksu2738** [comment]
Thx mrcrayfisch

**Comment by mapl-e** [comment]
> Optifine

Can u Fix that error is that I want to have Shaders and well...
If u can fix the Problem with Optifine or Something pls.. If u cannot do anything don't worry!

![image](https://user-images.githubusercontent.com/70176410/91191355-4ab67b00-e6ba-11ea-9ace-794683f3b11a.png)

**Comment by GrugMann** [comment]
Yeah, will there ever be an optifine compatible version of vehicle mod?

**Comment by MrCrayfish** [comment]
No. The real question is, will Optifine ever not break Forge?
