### ISSUE TITLE
Wrench not working on Pumps

### ISSUE THREAD

**Issue by azpha** [MrCrayfish/MrCrayfishVehicleMod#304]
For some reason on the 1.14.4 update of the Vehicle mod, I just cannot right click the pumps with the wrench to change the power status. Sometimes the Ender Sap and Blaze Juice also just disappears, not going into the mixer at all. It's very hit or miss, I've followed the video and everything however it's just refusing to work.

**Comment by Scwestbrook** [comment]
Same on MC forge 1.16.4, except the mixers/extractors work fine. If you install IE and generate RF, with command blocks to set the block above them to fuel, and then RF powered fluid pumps 2 blocks above them, it should work fine Note: Will **NOT** work without cheats, as it involves command blocks.

I'll give you a run through below:

1.  Obtain a command block by typing `/give @s command_block` in the chat
2.Obtain a fluid pump, engineer's hammer, 16 blocks of choice, fluid pies, and an RF source. I'm using the Creative Capacitor for my RF source. You can use windmills or waterwheels to and connect them to a kinetic dynamo. For more info on this, look at the in game `Engineer's Manual`
3. Create a donut pillar 2 blocks high, and 3 blocks long and wide, on every side, making sure to leave the middle open
4. Place a command block in the bottom of the pillar
5. Right-click the command block and enter the following command: `setblock ~ ~1 ~ vehicle:fuelium`
6. Select `repeating` and `Always active` in the command block's GUI
7. Place your fluid pump 2 blocks above the command block
8. Take the engineer's hammer, and right-click the side you want to attach to the rest of your fluid pipes, until it displays an orange dot, and place a fluid pump like you would when connecting a fluid extractor to a pipe
9. Provide RF power to the top of the fluid pump. For more info, visit the `wires and connectors` section of the engineer's manual

Hope this helps. It's a large amount of steps, but it also produces infinite fuelium. DO NOT use this UNLESS you cannot obtain fuelium by any other means, as it defeats the purpose of the fuel-making proscess.

**Comment by MrCrayfish** [comment]
Pipes in this mod have been confusing. The most common problem that I see is pipes being placed in the wrong direction. It may look like it's connected properly but it's actually a blockage in your pipes. With that said, pipes are changing in an upcoming update and will work like most tech mods (1.16 and above). Going to close this issue since I no longer support 1.14.4
