### ISSUE TITLE
Please add a Config setting to hide BPS display

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishVehicleMod#31]
Please add a setting in the config file to hide the BPS display and/or a way to move it, so it doesn't over/underlay other mod displays.

**Comment by MrCrayfish** [comment]
Added a config option ready for the next udpate :) https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/352a3bc8128e94ba5625a42d5f95a63c4567144f
