### ISSUE TITLE
Bugs de Voiture (conduite)

### ISSUE THREAD

**Issue by 5UP3RTH30B4G** [MrCrayfish/MrCrayfishVehicleMod#311]
Fr:

Quand je monte sur un véhicule je crache

voici le rapport de crash

En : 

When I get on a vehicle I spit

here is the crash report

-----------------------------------------------------------------------------------------------------------------------------------

Error: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.getPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;

Ou : 

[crash-2020-07-24_20.19.31-client.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4973820/crash-2020-07-24_20.19.31-client.txt)

**Comment by MrCrayfish** [comment]
Upgrade to latest Forge for 1.12.2
