### ISSUE TITLE
Vehicle Mod crashes Minecraft Launcher [1.12.2]

### ISSUE THREAD

**Issue by EspadaEsteban** [MrCrayfish/MrCrayfishVehicleMod#312]

**Comment by EspadaEsteban** [comment]
Crash Report: https://pastebin.com/GGix8VEF
vehicle mod ver0.44.1-1.12.2

**Comment by MrCrayfish** [comment]
Pollution of the Realms is the reason the game is crashing. Upgrade to the latest version of that mod.
