### ISSUE TITLE
Something wrong with the model

### ISSUE THREAD

**Issue by OlegVolgin** [MrCrayfish/MrCrayfishVehicleMod#315]
![2020-07-31_17 37 55](https://user-images.githubusercontent.com/69046786/89045967-081caf80-d355-11ea-9930-c40df7132573.png)
 Sofachopter and Bath...is it normal? Tried with and w/o Optifine. With and w/o shaders.

**Comment by MrCrayfish** [comment]
Can't be fixed until the Furniture Mod has the Bath and Ceiling Fan reimplemented -.-
