### ISSUE TITLE
Why won't The Textures Work? And I Have Optifine! and Jarfix! And Java!!

### ISSUE THREAD

**Issue by Saunokki** [MrCrayfish/MrCrayfishVehicleMod#323]
![2020-08-10_21 18 18](https://user-images.githubusercontent.com/69479251/89816518-644eb300-db4f-11ea-9210-481a9e50bde3.png)

**Comment by Saunokki** [comment]
And Its 1.16.1

**Comment by MrCrayfish** [comment]
Optifine...
