### ISSUE TITLE
I'm not able to pick up the Gas Pump after I've placed it down.

### ISSUE THREAD

**Issue by xpringle** [MrCrayfish/MrCrayfishVehicleMod#324]
Every time I try to mine/pick up a gas pump after I've placed it in survival, it just disappears instantly and doesn't give me the gas pump. This is really annoying, as the gas pumps are pretty expensive to make.

**Comment by astocky** [comment]
This also happens with the fluid extractors and fluid mixer.

**Comment by MrCrayfish** [comment]
Which version? The latest version is for 1.12.2, 1.14.4, 1.15.2,  and 1.16.1

**Comment by xpringle** [comment]
1.16.1, sorry for not mentioning that earlier.

**Comment by MrCrayfish** [comment]
It's working fine for me. I'm going to need detailed steps to reproduce the bug. Closing the bug for now.
