### ISSUE TITLE
Unable to pipe Blaze Juice into the fluid mixer

### ISSUE THREAD

**Issue by astocky** [MrCrayfish/MrCrayfishVehicleMod#326]
Unable to pipe Blaze Juice into the fluid mixer.

When I set up 2 fluid extractors and 1 fluid mixer the ender liquid goes into the mixer but the blaze juice does not. The pipes take the liquid out of the extractor, but the amount in the mixer does not go up. I can bucket it in manually and then the mixer works, but the pipes just seem to void the liquid blaze juice.

Once I manually put it in it processes into fuel-ium normally and then the pipes work to extract normally.

**Comment by MrCrayfish** [comment]
It may be that your pipes are not set up correctly. Place pipes in the direction you want the fluid to go to.
