### ISSUE TITLE
animation bug

### ISSUE THREAD

**Issue by thecreeez** [MrCrayfish/MrCrayfishVehicleMod#328]
the error appeared after the optifine and vic's modern warfare mod. ver 1.12.2
![image](https://user-images.githubusercontent.com/69771466/90344421-a3d33e80-e02a-11ea-9fea-46118bf1d538.png)

**Comment by thecreeez** [comment]
if i delete optifine, when i tap f5 game crashing
[crash-2020-08-17_20.25.08-client.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/5085443/crash-2020-08-17_20.25.08-client.txt)

**Comment by MrCrayfish** [comment]
Upgrade your Forge version, you're using an old version.
