### ISSUE TITLE
Bathtub Vehicle Incorrect Rendering

### ISSUE THREAD

**Issue by Mytholigist** [MrCrayfish/MrCrayfishVehicleMod#33]
You can see through the bathtub when you look into it, but this is not the case when looking at it from the outside. You also can't control the vehicle properly, meaning it doesn't go backward and it spins out of control all the time. The bathtub also doesn't have any sounds applied to it. (this is for the latest version, not tested in any other version)
![2018-08-15_21 09 51](https://user-images.githubusercontent.com/40723949/44183214-d1015500-a0cf-11e8-954b-cd949fa9f7c0.png)

**Comment by MrCrayfish** [comment]
It's a flying vehicle, not a land vehicle. Flying vehicles can't reverse. Try pressing Space while going forward.
