### ISSUE TITLE
My Vehicles look weird, and I have optifine on. What do i do?

### ISSUE THREAD

**Issue by sukoshiotokonoko** [MrCrayfish/MrCrayfishVehicleMod#330]
![Screenshot (1)](https://user-images.githubusercontent.com/69873721/90564704-cb81ee00-e173-11ea-9bc3-f5b6232d0893.png)
![Screenshot (2)](https://user-images.githubusercontent.com/69873721/90564722-d046a200-e173-11ea-9831-06b51910cb10.png)

**Comment by MrCrayfish** [comment]
Remove optifine...

**Comment by sukoshiotokonoko** [comment]
Thx!
