### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by mapl-e** [MrCrayfish/MrCrayfishVehicleMod#331]
Hi im having an Issue with the textures
 that I don't understand... Can u pls help me and fix the error?

![image](https://user-images.githubusercontent.com/70176410/91100797-6de61980-e62b-11ea-8619-637460c6280c.png)

**Comment by awbuckst11181999** [comment]
I am also having this problem, 1.16.1

**Comment by mapl-e** [comment]
> I am also having this problem, 1.16.1

Yes they need to fix it :( 
Oh and before it was working well...

**Comment by mapl-e** [comment]
> I am also having this problem, 1.16.1

Hey I think I resolved the problem u need to delete the OpTifine Mod if u using it! thats the problem just keep ObFuscate!
😉
