### ISSUE TITLE
Vehicles don’t work on survival and texture is messed up/like has a purple and black checked cube

### ISSUE THREAD

**Issue by jillv46** [MrCrayfish/MrCrayfishVehicleMod#332]
I have the 1.16.1 one and I crafted the atv in survival and I placed the create down but the textures are messed up and it didn’t spawn the atv. Am I doing something wrong or? Like why isn’t it working?

**Comment by Sahil-MC** [comment]
I am having exactly the same problem and I play in creative mode, but it seems that with the furniture mod the couch car works.
There r strange things happening.

Conclusion: Glitch, not your fault.

**Comment by MrCrayfish** [comment]
Uninstall Optifine

**Comment by Sahil-MC** [comment]
Thank's cray I will try that now.

Edit: it worked
