### ISSUE TITLE
Minecraft crashing after trying to install obfuscate/vehicle mod 1.12.2

### ISSUE THREAD

**Issue by xtsukuy0mii** [MrCrayfish/MrCrayfishVehicleMod#338]
Hey my friend runs a minecraft server, we have built a town in our own server. We would love to have vehicles in it and when we tried to install the obfuscate and vehicle mod, our minecraft clients all crashed every time we would try and load into the server again. I noticed I have Optifine which I have heard can be an issue, but the server host himself doesn't have it - nor is it on the server itself and we all got the right versions of the three mr.crayfish mods., so we're not sure what's wrong. even the device mod was causing crashes despite removing obfuscate and vehicle mod.
can anyone help us fix this please? c:

futhermore, would me having optifine cause other people to have their clients to crash if it interfered with the obfuscate and vehicle mod?
[crash-2020-09-05_15.54.13-client.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/5177591/crash-2020-09-05_15.54.13-client.txt)

**Comment by MrCrayfish** [comment]
Updated to the absolute latest Forge for 1.12.2

**Comment by xtsukuy0mii** [comment]
Thank you!  :)
