### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by Bruno-Marley** [MrCrayfish/MrCrayfishVehicleMod#342]
Today I installed the "Vehicle Mod 0.45.0" version of the mod and the "Obfuscate 0.5.0" version of Obfuscate and when I enter the game the textures of the vehicles and some other items do not load.
![2020-09-12_13 37 39](https://user-images.githubusercontent.com/42249835/92995712-adeb3e80-f4fd-11ea-889b-177f23814a39.png)

**Comment by josue1256** [comment]
I've
![2020-09-12_14 18 59](https://user-images.githubusercontent.com/63634485/93003315-3f10e400-f503-11ea-9d76-e1793ccb8ca4.png)
 had that issue too and hopefully, it gets fixed

**Comment by Bruno-Marley** [comment]
I did some tests and found that it is "OptiFine 1.16.1 HD U G2" that bugs the texture, if you remove it from the mods folder and start everything works.

**Comment by MrCrayfish** [comment]
Remove Optifine
