### ISSUE TITLE
No textures

### ISSUE THREAD

**Issue by ThR4z0r** [MrCrayfish/MrCrayfishVehicleMod#343]
When i spawn a car in creative mode from the boxes, nor the cars or the boxes have textures, version 1.16.1

**Comment by Wirmaple73** [comment]
I'm having this problem too. the Models and textures are Missing (Black/Purple) but the cars work.
Should be fixed. Version 1.16.1

**Comment by ThatTonybo** [comment]
Remove optifine if you're playing with it, I believe it's been mentioned multiple times that optifine breaks the textures.

**Comment by ThR4z0r** [comment]
i was just about to comment that, removing optifine fixed it lol
