### ISSUE TITLE
Vehicles models/textures messed up (no optifine)

### ISSUE THREAD

**Issue by GameBurrow** [MrCrayfish/MrCrayfishVehicleMod#345]
All vehicles look like this to me.

![java_OLyEKnosHM](https://user-images.githubusercontent.com/4341091/93671989-f1bae680-faaf-11ea-8be5-18bde12f3c10.png)
![java_XyX7XUMjtf](https://user-images.githubusercontent.com/4341091/93672017-29299300-fab0-11ea-8fc4-d42f9ec3dc23.png)

**I do not have optifine installed.**

Version 0.44.0, MC 1.14 (can't go to later MC versions due to other mods I'm using not updated to later ones yet).

Link to my modpack so you can test and look at what mods we have: https://gitlab.com/thesociety/transportcraft-lite/-/releases
(Under packages you find client package, that is package which you can import into GDLauncher, Twitch and I think even MultiMC and AT Launcher)

**Comment by MrCrayfish** [comment]
I'm not bug fixing 1.14.4 anymore.
