### ISSUE TITLE
Dirt Bike Causing Crashes

### ISSUE THREAD

**Issue by 09explorer** [MrCrayfish/MrCrayfishVehicleMod#347]
I recently updated my forge 1.12.2 server to the latest vehicle mod release, which adds the dirt bike. Whenever I try to fuel it, it freezes and crashes my client. I log back in and it works, but when I try to ride the dirk bike it completely stuck my client in a crash loop. Every time I log in now, the screen goes light blue, then closes. Other clients work on the server but not mine. I already tried updating the Obfuscate library and my forge 1.12.2 version. I have the full crash log here: 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 9/25/20 10:43 AM
Description: Rendering entity in world

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.getPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.patchPlayerRender(HeldVehicleEvents.java:46)
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.onRenderPlayer(HeldVehicleEvents.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_225_HeldVehicleEvents_onRenderPlayer_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.patchPlayerRender(HeldVehicleEvents.java:46)
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.onRenderPlayer(HeldVehicleEvents.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_225_HeldVehicleEvents_onRenderPlayer_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)

-- Entity being rendered --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 27324
	Entity Name: D4_Minecr4fter
	Entity's Exact location: 201.47, 68.50, 155.04
	Entity's Block location: World: (201,68,155), Chunk: (at 9,4,11 in 12,9; contains blocks 192,0,144 to 207,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: EntityDirtBike['entity.vehicle.dirt_bike.name'/27325, l='MpServer', x=201.46, y=68.00, z=154.91]

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderPlayer@4ca78790
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -305.38223
	Delta: 0.7600155
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['D4_Minecr4fter'/27324, l='MpServer', x=201.47, y=68.50, z=155.04]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (188,64,192), Chunk: (at 12,4,0 in 11,12; contains blocks 176,0,192 to 191,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 40116067 game time, 1669634 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 127 total; [EntityBat['Bat'/19208, l='MpServer', x=245.75, y=26.10, z=139.75], EntityPlayerSP['D4_Minecr4fter'/27324, l='MpServer', x=201.47, y=68.50, z=155.04], EntitySquid['Squid'/22290, l='MpServer', x=260.97, y=51.76, z=193.96], EntitySquid['Squid'/22291, l='MpServer', x=260.76, y=56.73, z=191.83], EntitySquid['Squid'/22292, l='MpServer', x=249.57, y=53.27, z=195.33], EntitySquid['Squid'/22293, l='MpServer', x=229.59, y=52.58, z=218.99], EntitySquid['Squid'/22295, l='MpServer', x=225.04, y=55.83, z=215.50], EntityBat['Bat'/23831, l='MpServer', x=281.34, y=20.05, z=125.87], EntityBat['Bat'/23832, l='MpServer', x=274.25, y=18.10, z=120.70], EntityLawnMower['Lawn Mower'/42, l='MpServer', x=67.78, y=64.00, z=159.21], EntityATV['ATV'/43, l='MpServer', x=69.11, y=64.00, z=159.76], EntityBat['Bat'/26419, l='MpServer', x=229.43, y=23.50, z=87.98], EntityBat['Bat'/26420, l='MpServer', x=221.28, y=23.05, z=78.59], EntitySheep['Sheep'/56, l='MpServer', x=131.29, y=81.00, z=125.50], EntitySheep['Sheep'/58, l='MpServer', x=125.67, y=82.00, z=126.80], EntityBat['Bat'/22848, l='MpServer', x=121.74, y=24.00, z=201.42], EntitySheep['Sheep'/74, l='MpServer', x=159.75, y=73.00, z=87.56], EntitySheep['Sheep'/75, l='MpServer', x=147.54, y=71.00, z=94.72], EntitySheep['Sheep'/76, l='MpServer', x=155.81, y=74.00, z=131.52], EntitySheep['Sheep'/77, l='MpServer', x=157.50, y=76.00, z=128.81], EntityPainting['Painting'/122, l='MpServer', x=191.03, y=72.00, z=184.00], EntityPainting['Painting'/123, l='MpServer', x=195.00, y=72.00, z=186.97], EntitySheep['Sheep'/85, l='MpServer', x=175.52, y=83.00, z=78.77], EntitySheep['Sheep'/86, l='MpServer', x=162.50, y=77.00, z=89.27], EntityChicken['Chicken'/87, l='MpServer', x=167.50, y=87.00, z=91.41], EntitySheep['Sheep'/88, l='MpServer', x=166.04, y=84.00, z=90.55], EntitySheep['Sheep'/89, l='MpServer', x=173.69, y=86.00, z=90.45], EntitySheep['Sheep'/90, l='MpServer', x=160.27, y=79.00, z=110.49], EntitySheep['Sheep'/91, l='MpServer', x=163.50, y=86.00, z=98.52], EntitySheep['Sheep'/92, l='MpServer', x=165.47, y=86.00, z=105.44], EntitySheep['Sheep'/93, l='MpServer', x=164.49, y=86.00, z=106.30], EntitySheep['Sheep'/94, l='MpServer', x=173.50, y=85.00, z=105.20], EntitySheep['Sheep'/95, l='MpServer', x=163.52, y=86.00, z=97.45], EntitySheep['Sheep'/96, l='MpServer', x=172.39, y=85.00, z=100.77], EntitySheep['Sheep'/97, l='MpServer', x=167.43, y=84.00, z=112.90], EntitySheep['Sheep'/98, l='MpServer', x=162.51, y=81.00, z=111.81], EntitySheep['Sheep'/99, l='MpServer', x=167.54, y=78.00, z=117.19], EntitySheep['Sheep'/100, l='MpServer', x=166.73, y=79.00, z=115.54], EntityBat['Bat'/11108, l='MpServer', x=204.41, y=40.10, z=183.25], EntitySheep['Sheep'/101, l='MpServer', x=167.52, y=86.00, z=107.73], EntityBat['Bat'/9577, l='MpServer', x=164.75, y=33.10, z=170.25], EntitySheep['Sheep'/114, l='MpServer', x=182.45, y=79.00, z=83.30], EntitySheep['Sheep'/115, l='MpServer', x=183.23, y=79.00, z=84.50], EntitySheep['Sheep'/116, l='MpServer', x=177.73, y=85.00, z=92.49], EntitySheep['Sheep'/117, l='MpServer', x=180.45, y=83.00, z=93.48], EntitySheep['Sheep'/118, l='MpServer', x=186.49, y=79.00, z=110.74], EntitySheep['Sheep'/119, l='MpServer', x=178.48, y=84.00, z=96.77], EntitySheep['Sheep'/120, l='MpServer', x=183.27, y=81.00, z=107.55], EntitySheep['Sheep'/121, l='MpServer', x=172.54, y=85.00, z=107.79], EntityPainting['Painting'/122, l='MpServer', x=191.03, y=72.00, z=184.00], EntityPainting['Painting'/123, l='MpServer', x=195.00, y=72.00, z=186.97], EntityItemFrame['entity.ItemFrame.name'/124, l='MpServer', x=191.03, y=69.50, z=198.50], EntitySheep['Sheep'/126, l='MpServer', x=194.87, y=79.00, z=96.49], EntityFluidTrailer['Fluid Trailer'/127, l='MpServer', x=199.17, y=68.00, z=158.51], EntityOffRoader['Off Roader'/129, l='MpServer', x=196.52, y=68.00, z=203.93], EntityTractor['Tractor'/130, l='MpServer', x=196.73, y=67.00, z=205.08], EntityBumperCar['Bumper Car'/131, l='MpServer', x=198.36, y=68.00, z=201.85], EntityJack['entity.vehicle.jack.name'/132, l='MpServer', x=195.50, y=69.04, z=198.50], EntityOffRoader['Off Roader'/133, l='MpServer', x=195.50, y=69.06, z=198.50], EntityJack['entity.vehicle.jack.name'/134, l='MpServer', x=194.50, y=69.04, z=194.50], EntityGolfCart['Golf Cart'/135, l='MpServer', x=194.59, y=69.06, z=194.52], EntityVehicleTrailer['Vehicle Trailer'/136, l='MpServer', x=200.42, y=68.00, z=202.00], EntityMiniBike['Mini Bike'/137, l='MpServer', x=202.89, y=68.00, z=202.19], EntityBat['Bat'/21642, l='MpServer', x=150.83, y=29.09, z=168.44], EntityMiniBus['Mini Bus'/138, l='MpServer', x=203.12, y=68.00, z=194.29], EntityMiniBike['Mini Bike'/140, l='MpServer', x=220.50, y=73.00, z=95.26], EntityGolfCart['Golf Cart'/143, l='MpServer', x=239.79, y=68.00, z=86.40], EntityGolfCart['Golf Cart'/144, l='MpServer', x=239.82, y=68.00, z=83.55], EntitySmartCar['Smart Car'/145, l='MpServer', x=234.50, y=68.00, z=106.40], EntitySmartCar['Smart Car'/146, l='MpServer', x=236.50, y=68.00, z=106.42], EntitySmartCar['Smart Car'/147, l='MpServer', x=238.50, y=68.00, z=106.44], EntityBat['Bat'/28307, l='MpServer', x=262.75, y=28.00, z=158.25], EntityOffRoader['Off Roader'/148, l='MpServer', x=238.50, y=68.00, z=119.53], EntityOffRoader['Off Roader'/149, l='MpServer', x=235.50, y=68.00, z=119.54], EntityLawnMower['Lawn Mower'/150, l='MpServer', x=225.59, y=68.00, z=153.40], EntityMiniBus['Mini Bus'/151, l='MpServer', x=231.03, y=68.00, z=161.35], EntityBat['Bat'/152, l='MpServer', x=230.75, y=37.10, z=206.32], EntitySmartCar['Smart Car'/159, l='MpServer', x=251.64, y=68.00, z=91.53], EntityGolfCart['Golf Cart'/160, l='MpServer', x=240.21, y=68.00, z=80.86], EntitySmartCar['Smart Car'/161, l='MpServer', x=240.50, y=68.00, z=106.43], EntitySmartCar['Smart Car'/162, l='MpServer', x=242.50, y=68.00, z=106.46], EntityMoped['Moped'/163, l='MpServer', x=244.50, y=68.00, z=106.04], EntityMoped['Moped'/164, l='MpServer', x=246.50, y=68.00, z=106.00], EntityGolfCart['Golf Cart'/165, l='MpServer', x=255.16, y=68.00, z=111.50], EntityGolfCart['Golf Cart'/166, l='MpServer', x=255.14, y=68.00, z=108.50], EntityMoped['Moped'/167, l='MpServer', x=248.50, y=68.00, z=105.95], EntityOffRoader['Off Roader'/168, l='MpServer', x=244.50, y=68.00, z=119.38], EntityOffRoader['Off Roader'/169, l='MpServer', x=241.50, y=68.00, z=119.53], EntityGolfCart['Golf Cart'/170, l='MpServer', x=255.33, y=68.00, z=120.50], EntityGolfCart['Golf Cart'/171, l='MpServer', x=255.23, y=68.00, z=117.50], EntityGolfCart['Golf Cart'/172, l='MpServer', x=255.14, y=68.00, z=114.50], MagicEntity['unknown'/-31415, l='MpServer', x=200.39, y=68.55, z=155.81], EntityItemFrame['entity.ItemFrame.name'/184, l='MpServer', x=268.03, y=69.50, z=88.50], EntityJack['entity.vehicle.jack.name'/185, l='MpServer', x=271.50, y=69.04, z=90.50], EntityJetSki['Jet Ski'/186, l='MpServer', x=271.31, y=69.06, z=90.82], EntityVehicleTrailer['Vehicle Trailer'/187, l='MpServer', x=267.41, y=68.00, z=102.90], EntityDirtBike['entity.vehicle.dirt_bike.name'/27325, l='MpServer', x=201.46, y=68.00, z=154.91], EntityVehicleTrailer['Vehicle Trailer'/27329, l='MpServer', x=63.80, y=64.00, z=158.83], EntityItemFrame['entity.ItemFrame.name'/197, l='MpServer', x=278.97, y=69.50, z=92.50], EntityVehicleTrailer['Vehicle Trailer'/198, l='MpServer', x=281.79, y=68.00, z=91.98], EntityLawnMower['Lawn Mower'/199, l='MpServer', x=277.17, y=68.00, z=88.81], EntityJack['entity.vehicle.jack.name'/200, l='MpServer', x=275.50, y=69.04, z=92.50], EntityATV['ATV'/201, l='MpServer', x=275.37, y=69.06, z=92.28], EntityItemFrame['entity.ItemFrame.name'/202, l='MpServer', x=273.50, y=69.50, z=94.97], EntityVehicleTrailer['Vehicle Trailer'/203, l='MpServer', x=283.81, y=68.00, z=96.56], EntitySpeedBoat['Speed Boat'/204, l='MpServer', x=283.23, y=68.41, z=96.09], EntityVehicleTrailer['Vehicle Trailer'/205, l='MpServer', x=284.01, y=68.00, z=99.58], EntitySpeedBoat['Speed Boat'/206, l='MpServer', x=283.49, y=68.41, z=100.13], EntityBat['Bat'/211, l='MpServer', x=280.94, y=23.05, z=145.69], EntityJack['entity.vehicle.jack.name'/27349, l='MpServer', x=275.50, y=71.04, z=22.50], EntityGolfCart['Golf Cart'/27350, l='MpServer', x=275.50, y=71.06, z=22.41], EntityJack['entity.vehicle.jack.name'/27351, l='MpServer', x=279.50, y=71.04, z=22.50], EntityLawnMower['Lawn Mower'/27352, l='MpServer', x=279.43, y=71.06, z=21.75], EntitySmartCar['Smart Car'/27353, l='MpServer', x=266.28, y=70.00, z=12.90], EntityJack['entity.vehicle.jack.name'/228, l='MpServer', x=288.50, y=68.56, z=97.50], EntityJetSki['Jet Ski'/229, l='MpServer', x=288.16, y=68.44, z=97.65], EntityJack['entity.vehicle.jack.name'/230, l='MpServer', x=289.50, y=69.04, z=100.50], EntityJetSki['Jet Ski'/231, l='MpServer', x=289.87, y=69.06, z=100.47], EntityJack['entity.vehicle.jack.name'/232, l='MpServer', x=291.50, y=69.04, z=104.50], EntityJetSki['Jet Ski'/233, l='MpServer', x=291.70, y=69.06, z=104.18], EntityJetSki['Jet Ski'/241, l='MpServer', x=309.74, y=62.54, z=103.85], EntitySpeedBoat['Speed Boat'/242, l='MpServer', x=317.49, y=62.54, z=98.84], EntityJetSki['Jet Ski'/243, l='MpServer', x=307.64, y=62.54, z=103.95], EntitySpeedBoat['Speed Boat'/244, l='MpServer', x=317.34, y=62.54, z=100.79], EntityJetSki['Jet Ski'/245, l='MpServer', x=311.97, y=62.54, z=104.27], EntitySpeedBoat['Speed Boat'/246, l='MpServer', x=317.34, y=62.54, z=102.64], EntityBat['Bat'/20731, l='MpServer', x=258.05, y=27.10, z=154.75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 526716032 bytes (502 MB) / 2785017856 bytes (2656 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version       | Source                                        | Signature                                |
	|:------ |:-------------------------------------------- |:------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft                                    | 1.12.2        | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp                                          | 9.42          | minecraft.jar                                 | None                                     |
	| UCHIJA | FML                                          | 8.0.99.99     | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                                        | 14.23.5.2768  | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | com.elytradev.movingworld.common.asm.coremod |               | minecraft.jar                                 | None                                     |
	| UCHIJA | obfuscate                                    | 0.4.2         | minecraft.jar                                 | None                                     |
	| UCHIJA | securitycraft                                | v1.8.4.1      | [1.12.x]+SecurityCraft+v1.8.4.1.jar           | None                                     |
	| UCHIJA | buildcraftlib                                | 7.99.17       | buildcraft-7.99.17.jar                        | None                                     |
	| UCHIJA | buildcraftcore                               | 7.99.17       | buildcraft-7.99.17.jar                        | None                                     |
	| UCHIJA | buildcraftbuilders                           | 7.99.17       | buildcraft-7.99.17.jar                        | None                                     |
	| UCHIJA | buildcraftenergy                             | 7.99.17       | buildcraft-7.99.17.jar                        | None                                     |
	| UCHIJA | buildcraftfactory                            | 7.99.17       | buildcraft-7.99.17.jar                        | None                                     |
	| UCHIJA | buildcraftrobotics                           | 7.99.17       | buildcraft-7.99.17.jar                        | None                                     |
	| UCHIJA | buildcrafttransport                          | 7.99.17       | buildcraft-7.99.17.jar                        | None                                     |
	| UCHIJA | buildcraftsilicon                            | 7.99.17       | buildcraft-7.99.17.jar                        | None                                     |
	| UCHIJA | cdm                                          | 0.4.1         | cdm-0.4.1-mc1.12.2 (1).jar                    | None                                     |
	| UCHIJA | cfm                                          | 6.3.0         | cfm-6.3.0-mc1.12.2.jar                        | None                                     |
	| UCHIJA | codechickenlib                               | 3.2.3.358     | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | movingworld                                  | 1.12-6.342    | movingworld-1.12-6.342-full.jar               | None                                     |
	| UCHIJA | davincisvessels                              | @DVESSELSVER@ | davincisvessels-1.12-6.340-full.jar           | None                                     |
	| UCHIJA | ptrmodellib                                  | 1.0.3         | PTRLib-1.0.3.jar                              | None                                     |
	| UCHIJA | props                                        | 2.6.2         | Decocraft-2.6.2_1.12.2.jar                    | None                                     |
	| UCHIJA | bruh_mod                                     | 1.0.0         | emeraldmod_0.3.jar                            | None                                     |
	| UCHIJA | forgemultipartcbe                            | 2.6.2.83      | ForgeMultipart-1.12.2-2.6.2.83-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | microblockcbe                                | 2.6.2.83      | ForgeMultipart-1.12.2-2.6.2.83-universal.jar  | None                                     |
	| UCHIJA | minecraftmultipartcbe                        | 2.6.2.83      | ForgeMultipart-1.12.2-2.6.2.83-universal.jar  | None                                     |
	| UCHIJA | trackapi                                     | 1.1           | TrackAPI-1.1_1.12.jar                         | None                                     |
	| UCHIJA | immersiverailroading                         | 1.5.0         | ImmersiveRailroading-1.5.0_1.12-402.jar       | None                                     |
	| UCHIJA | lightswitch                                  | 1.1.2         | lightswitch-1.1.2-mc1.12.2.jar                | None                                     |
	| UCHIJA | malisiscore                                  | 1.12.2-6.4.0  | malisiscore-1.12.2-6.4.0.jar                  | None                                     |
	| UCHIJA | malisisdoors                                 | 1.12.2-7.3.0  | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| UCHIJA | mcef                                         | 0.9           | mcef-1.12.2-0.9.jar                           | None                                     |
	| UCHIJA | thutcore                                     | 5.15.1        | ThutCore-1.12.2.jar                           | None                                     |
	| UCHIJA | thuttech                                     | 6.0.4         | Thut-Elevator-1.12.jar                        | None                                     |
	| UCHIJA | thutcore_compat                              | 1.0           | ThutCore-1.12.2.jar                           | None                                     |
	| UCHIJA | vehicle                                      | 0.44.1        | vehicle-0.44.1-mc1.12.2.jar                   | None                                     |
	| UCHIJA | webdisplays                                  | 1.0           | webdisplays-1.12.2-1.0.jar                    | None                                     |
	| UCHIJA | worldedit                                    | 6.1.8         | worldedit-forge-mc1.12-6.1.8-dist.jar         | None                                     |
	| UCHIJA | wrcbe                                        | 2.3.2         | WR-CBE-1.12.2-2.3.2.33-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 451.67' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: f81517ca516363c381528480bb4c5189-New Default Betapack V2 (1).zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz

**Comment by MrCrayfish** [comment]
Update to the latest Forge...
