### ISSUE TITLE
Can't open gas tank

### ISSUE THREAD

**Issue by punkcats** [MrCrayfish/MrCrayfishVehicleMod#349]
I just added the Mrcrayfish vehicle mod to my server, but the gas tanks wont open on any of them. Ive tried everything and I dont know what to do. I cant use the vehicles in survival mode if I cant put fuel in them. Thank you!

**Comment by MrCrayfish** [comment]
I need more information. It works perfectly fine on 1.16.3. Use a jerry can on the fuel port.
