### ISSUE TITLE
Please add a Config setting to disable Fuel Consumption

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishVehicleMod#35]
Please add a setting in the config file to disable Fuel Consumption.

**Comment by MrCrayfish** [comment]
Will do!

**Comment by Sqaaakoi** [comment]
A gamerule or NBT tag would be useful too. Great suggestion
null

**Comment by fandomaniac** [comment]
Thanks!

**Comment by MokahTGS** [comment]
Any chance these vehicles will be able to use other mods fuel?

**Comment by MrCrayfish** [comment]
Next patch add in support to disable fuel using the tag "requiresFuel" set to false on a vehicle or fuel can be disabled completely through the config for all vehicles.
