### ISSUE TITLE
Textures Missing

### ISSUE THREAD

**Issue by MiscMorningstar** [MrCrayfish/MrCrayfishVehicleMod#351]
Textures for the blocks and vehicles in 1.16.1 are missing. The textures include the gas pump, the jack, all vehicles and vehicle crates.  The textures in the inventory are fine. The vehicles are still usable.
![2020-10-01_09 32 25](https://user-images.githubusercontent.com/72207888/94816076-496b2300-03c9-11eb-8159-3984d16be899.png)

**Comment by MrCrayfish** [comment]
Remove Optifine
