### ISSUE TITLE
Vehicle rendering on top of head when picked up

### ISSUE THREAD

**Issue by Carhenia** [MrCrayfish/MrCrayfishVehicleMod#352]
![image](https://user-images.githubusercontent.com/32433030/94948630-331cae80-0512-11eb-8509-6f7afa7e0624.png)

I've recently made a modpack with over 140 mods but I'm having an issue where when I pick up a vehicle by shift right clicking, it just shows up on top of my head, any idea what could be causing this? I disabled baubles rendering thinking it was the issue but nothing changed. 

Mods List:

Armourer's Workshop Armourers-Workshop-1.12.2-0.50.5.jar
Blockcraftery blockcraftery-1.12.2-1.3.1.jar
ChinjufuMod ChinjufuMod[1.12.2]5.1.3.jar
Chisel Chisel-MC1.12.2-1.0.2.45.jar
Cooking for Blockheads CookingForBlockheads_1.12.2-6.5.0.jar
Dark Roleplay Medieval drpmedieval-1.12.2-0.3.6.jar
Dawn of Time dawnoftime_builder_edition-1.0.7.jar
DecoCraft Decocraft-2.6.3_1.12.2.jar
MrCrayfish's Furniture Mod furniture-6.3.1-1.12.2.jar
MrCrayfish's Vehicle Mod vehicle-mod-0.44.1-1.12.2.jar
MultiBeds multibeds-1.12.0-1.4.6.jar
Ore Excavation OreExcavation-1.4.150.jar
Pam's HarvestCraft Pam's HarvestCraft 1.12.2zg.jar
Quark Quark-r1.6-179.jar
Saracalia's City Mod SCM-v1.12.2-1.0.03a.jar
Waystones Waystones_1.12.2-4.1.0.jar
WorldEdit worldedit-forge-mc1.12.2-6.1.10-dist.jar
Progressive Bosses ProgressiveBosses-1.5.4-mc1.12.x.jar
Infernal Mobs InfernalMobs-1.12.2.jar
Netherbound netherbound-1.2.jar
Roguelike Dungeons RoguelikeDungeons-1.12.2-1.8.0.jar
Bad Wither No Cookie - Reloaded badwithernocookiereloaded-1.12.2-3.4.18.jar
Better HUD betterhud-1.12.2-1.4.3.jar
Blur Blur-1.0.4-14.jar
Controlling Controlling-3.0.10.jar
Ding Ding-1.12.2-1.0.2.jar
Its the little things itlt-1.12.2-1.0.2.jar
JourneyMap journeymap-1.12.2-5.7.1.jar
Reauth reauth-3.6.0.jar
Tips Tips-1.12.2-1.0.9.jar
Toast Control Toast Control-1.12.2-1.8.1.jar
WorldEdit CUI WorldEdit CUI Forge Edition 2-2.2.0-mf-1.12.2-14.23.5.2768.jar
Mod Name Tooltip modnametooltip_1.12.2-1.10.1.jar
CraftPresence CraftPresence-Forge-1.12.2-Release-1.7.1.jar
Hwyla Hwyla-1.8.26-B41_1.12.2.jar
Waila Harvestability WailaHarvestability-mc1.12-1.1.12.jar
JEI jei_1.12.2-4.16.1.301.jar
JEI Integration jeiintegration_1.12.2-1.6.0.jar
Just Enough Resources (JER) JustEnoughResources-1.12.2-0.9.2.60.jar
Tinker's JEI tinkersjei-1.2.jar
JEI Bees jeibees-0.9.0.5-mc1.12.2.jar
GalacticCraft Galacticraft-Planets-1.12.2-4.0.2.280
GalacticCraft - More Planets More-Planets-1.12.2-2.0.24-GC251
NetherEx NetherEx-1.12.2-2.1.8.jar
BetterFPS BetterFps-1.4.8.jar
CraftTweaker CraftTweaker2-1.12-4.1.20.586.jar
FastWorkbench FastWorkbench-1.12.2-1.7.3.jar
Foamfix foamfix-0.10.10-1.12.2.jar
FutureMC future-mc-1.12.2-0.2.4.1.jar
Inventory Tweaks InventoryTweaks-1.63.jar
Mouse Tweaks MouseTweaks-2.10-mc1.12.2.jar
No More Recipe Conflicts NoMoreRecipeConflict-0.13(1.12.2).jar
NotEnoughIDs NotEnoughIDs-1.5.4.4.jar
Phosphor phosphor-1.12.2-0.2.6+build50-universal.jar
UniDict UniDict-1.12.2-2.9.7.jar
VanillaFix VanillaFix-1.0.10-150.jar
More Player Models MorePlayerModels_1.12.2-(05Dec19).jar
Baubles Baubles-1.12-1.5.2.jar
Cosmetic Armor Reworked CosmeticArmorReworked-1.12.2-v5a.jar
Astral Sorcery astralsorcery-1.12.2-1.10.27.jar
Blood Magic BloodMagic-1.12.2-2.4.3-105.jar
Botania Botania r1.10-363.jar
Corail Tombstone tombstone-4.0.0-1.12.2.jar
PSI Psi-r1.1-78.1.jar
Wizardry Mod wizardry-0.11.1.jar
Mystical Agriculture MysticalAgriculture-1.12.2-1.7.5.jar
Mystical Agradditions MysticalAgradditions-1.12.2-1.3.2.jar
Animania animania-1.12.2-1.7.3.jar
Vampirism Vampirism-1.12.2-1.6.2.jar
Vampirism Integrations VampirismIntegrations-1.12.2-1.3.0.jar
Minecraft Comes Alive MCA-1.12.2-6.1.0-universal.jar
Bonsai Trees bonsaitrees-1.1.4-b170.jar
Botanic Bonsai BotanicBonsai-1.0.0.5.jar
FTB Backups FTBBackups-1.1.0.1.jar
FTB Utilities FTBUtilities-5.4.1.130.jar
Item Blacklist ItemBlacklist-1.4.3.jar
Morpheus Morpheus-1.12.2-3.5.106.jar
Sampler sampler-1.84.jar
Enter Storage EnderStorage-1.12.2-2.4.6.137-universal.jar
Iron Chests ironchest-1.12.2-7.0.72.847.jar
Storage Drawers StorageDrawers-1.12.2-5.4.2.jar
Applied Energistics 2 appliedenergistics2-rv6-stable-7.jar
Wireless Crafting Terminal WirelessCraftingTerminal-1.12.2-3.12.97.jar
Iron Backpacks IronBackpacks-1.12.2-3.0.8-12.jar
Actually Additions ActuallyAdditions-1.12.2-r151-2.jar
EnderIO EnderIO-1.12.2-5.2.60.jar
Extra Utilities extrautils2-1.12-1.9.9.jar
Extreme Reactors ExtremeReactors-1.12.2-0.4.5.67.jar
RFTools rftools-1.12-7.73.jar
Tiny Progressions tinyprogressions-1.12.2-3.3.34-Release.jar
Forestry forestry_1.12.2-5.8.2.387.jar
Binnie's Mods binnie-mods-1.12.2-2.5.1.203.jar
Gendustry gendustry-1.6.5.8-mc1.12.2.jar
Magic Bees MagicBees-1.12.2-3.1.10.jar
Thermal Expansion ThermalExpansion-1.12.2-5.5.7.1-universal.jar
Thermal Dynamics ThermalDynamics-1.12.2-2.5.6.1-universal.jar
Thermal Foundation ThermalFoundation-1.12.2-2.6.7.1-universal.jar
Tinker's Consctruct TConstruct-1.12.2-2.13.0.183.jar
Construct's Armory conarm-1.12.2-1.2.5.9.jar
Tinker's Tool Leveling TinkerToolLeveling-1.12.2-1.1.0.jar
Biomes O' Plenty BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar
Plants Plants-1.12.2-2.10.7.jar
Streams Streams-1.12-0.4.8.jar
Torchmaster

**Comment by Carhenia** [comment]
sorry, forgot about the core mods

MysticalLib mysticallib-1.12.2-1.9.0.jar
Connected Textures Mod CTM-MC1.12.2-1.0.2.31.jar
Dark Roleplay Core drpcore-1.12.2-0.4.8.jar
PTRLib PTRLib-1.0.4.jar
Obsfucate obfuscate-0.4.2-1.12.2.jar
shetiphiancore shetiphiancore-1.12.0-3.5.9.jar
AutoRegLib AutoRegLib-1.3-32.jar
FCL Fexcraft Common Library-1.12.56.jar
LibraryEx LibraryEx-1.12.2-1.1.3.jar
Placebo Placebo-1.12.2-1.6.0.jar
Shadowfacts' Forgelin Forgelin-1.8.4.jar
WanionLib WanionLib-1.12.2-2.5.jar
Guide-API Guide-API-1.12-2.1.8-63.jar
LibrarianLib librarianlib-1.12.2-4.22.jar
Cucumber Lib Cucumber-1.12.2-1.1.3.jar 
Craftstudio API CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar
FTB Library FTBLib-5.4.7.2.jar
Code Chicken Lib CodeChickenLib-1.12.2-3.2.3.358-universal.jar
Charmeleon Chameleon-1.12-4.1.3.jar
AE2 Wireless Terminal Library AE2WTLib-1.12.2-1.0.34.jar, p455w0rd's library p455w0rdslib-1.12.2-2.3.161.jar
EnderCore EnderCore-1.12.2-0.5.76.jar
ZeroCore zerocore-1.12.2-0.1.2.8.jar
McJtyLib mcjtylib-1.12-3.5.4.jar
bdlib bdlib-1.14.3.12-mc1.12.2.jar
CoFH Core CoFHCore-1.12.2-4.6.6.1-universal.jar, CoFH World CoFHWorld-1.12.2-1.4.0.1-universal.jar Redstone Flux RedstoneFlux-1.12-2.1.1.1-universal.jar
Mantle Mantle-1.12-1.3.3.55.jar
Placebo Placebo-1.12.2-1.6.0.jar
Farseek Farseek-1.12-2.5.jar

**Comment by MrCrayfish** [comment]
That's how it works. Obviously a compatibility issue because the arms are suppose to be holding it.
