### ISSUE TITLE
Plane with more than just one seat

### ISSUE THREAD

**Issue by ExDomino** [MrCrayfish/MrCrayfishVehicleMod#358]
Hello,

I would like to suggest you a plane that has more than juste one place. For example, 4 ou 5 seats.
If possible, can you bring this plane on 1.12.2 please ?

Thank you in advance.

**Comment by MrCrayfish** [comment]
In the future and maybe 1.12.2

**Comment by Shlepsss** [comment]
@MrCrayfish please do this!!!

**Comment by alfre375** [comment]
This would be a cool idea
