### ISSUE TITLE
Bugged textures on 1.16.1

### ISSUE THREAD

**Issue by BLXCKONE** [MrCrayfish/MrCrayfishVehicleMod#359]
![2020-10-16_21 27 07](https://user-images.githubusercontent.com/72764007/96301732-e64bd400-0ff7-11eb-973b-6bdbded91743.png)

**Comment by BLXCKONE** [comment]
Update: It works without optifine, but playing without optifine is just like eating french fries without salt, but they'll be shitty. It's the same with optifine, especially as they allow you to play custom texture packs, not to mention shaders.

Sorry for the mistakes in advance, I used Google Translate

**Comment by MrCrayfish** [comment]
Yeah remove optifine.

**Comment by BLXCKONE** [comment]
But I don't want to play without optifine

**Comment by MrCrayfish** [comment]
Unfortuantely Optifine breaks a feature in Forge which this mod utilises
