### ISSUE TITLE
issue with airplane

### ISSUE THREAD

**Issue by Heisler70** [MrCrayfish/MrCrayfishVehicleMod#37]
Not sure if this is where i would post this so if wrong please let me know. my game kept crashing and the report came back to something wrong with the vehicle mod specifically the airplane. I finally had to remove the mod just so i could load the game. I have the crash report if you want me to post that if it would help. would you want it as an attachment or just copy and paste? Thanks for your help I love the mod and your videos!!

**Comment by MokahTGS** [comment]
Use pastebin to post and link your crash logs.

https://pastebin.com/

**Comment by JanHolger** [comment]
This is the same issue as #21

**Comment by MrCrayfish** [comment]
Duplicate issue
