### ISSUE TITLE
1.16.3 version is mis-labeled as 1.16.4 at cursrforge

### ISSUE THREAD

**Issue by Tsoccerguy3** [MrCrayfish/MrCrayfishVehicleMod#371]
I can confirm that the 1.16.4 version at curse is a mis-labled 1.16.3 and does not work with 1.16.4 .

**Comment by MrCrayfish** [comment]
I just performed a clean installation with Forge 1.16.4-35.0.7 with the Vehicle Mod and Obfuscate and it's loaded and played fine. Not sure how you confirmed it. Closing unless proven otherwise.

**Comment by MrCrayfish** [comment]
Also I'm not going to upload a 1.16.4 version when 1.16.3 version works fine. The only difference would be the label.

**Comment by Tsoccerguy3** [comment]
![Capture1](https://user-images.githubusercontent.com/22108822/98671869-eacb8a00-2322-11eb-95a7-9e62b43e1c22.PNG)
[crash-2020-11-10_07.00.48-client.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/5517091/crash-2020-11-10_07.00.48-client.txt)

Ok , I found the problem , it's not compatible with Optifine , OptiFine_1.16.4_HD_U_G5
