### ISSUE TITLE
Incompatible with Optifine OptiFine_1.16.4_HD_U_G5

### ISSUE THREAD

**Issue by Tsoccerguy3** [MrCrayfish/MrCrayfishVehicleMod#373]
![Capture1](https://user-images.githubusercontent.com/22108822/98692263-ead88380-233c-11eb-907e-f8228c5649f0.PNG)
[crash-2020-11-10_07.00.48-client.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/5518214/crash-2020-11-10_07.00.48-client.txt)

Seems to be incompatible with OptiFine_1.16.4_HD_U_G5 , Log is above

**Comment by MrCrayfish** [comment]
Obfuscate is not compatible with Optifine. https://github.com/MrCrayfish/Obfuscate/issues/3
