### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by nathou0** [MrCrayfish/MrCrayfishVehicleMod#382]
I couldn't find a channel to ask questions so I made my request here. I want to ask you if in a future update mobs could take control of vehicles? Whether there will be military vehicles (which fire projectiles) or mining vehicles? if we will have an option to activate the explosion of planes during a collision? Keep it up, your mod is fantastic

**Comment by MrCrayfish** [comment]
No plans to support mobs driving vehicles. Not going to be adding militay vehicles, that would be more suited towards an addon rather than in the base mod.
