### ISSUE TITLE
Authorized transfer to China [搬运到中国]

### ISSUE THREAD

**Issue by q804991929** [MrCrayfish/MrCrayfishVehicleMod#387]
Hello, author. I'm from China. Can I transfer your module to my World China edition? Let more Chinese friends like your work and apply it to my server? It would be a great honor for me to have your approval

中文：作者，你好。我来自中国。我可以把这个模组搬运到我的世界中国版上吗？并兼职到我的服务器上吗？如果得到您的同意，我将万分荣幸

**Comment by 2353739509** [comment]
我想问你一个问题，什么是所谓的“我的世界中国版”，是指“我的世界中文论坛，还是“你自己的游戏”。据我个人所知，你是一个网络主播，你能够用这个模组来为自己带收益。不要说中国，中国人。你直接说你是一个某某网络主播可以吗朋友，我们都爱自己的祖国

I want to ask you a question, what is the so-called "my world Chinese version", which means "my world Chinese Forum", or "your own game". As far as I know, you are a network anchor, you can use this module to bring benefits for yourself. Don't talk about China, Chinese people. Can you say that you are a network anchor, friend? We all love our motherland

**Comment by 2353739509** [comment]
> 您好，作者。我來自中國。我可以將您的模塊轉移到我的世界中國版嗎？讓更多的中國朋友喜歡您的作品並將其應用於我的服務器嗎？得到您的認可對我來說是我的榮幸
> 
> 中文：作者，你好。我來自中國。我可以把這個模組搬運到我的世界中國版上嗎？並兼職到我的服務器上嗎？如果得到您的同意，我將萬分榮幸

我想问你一个问题，什么是所谓的“我的世界中国版”，是指“我的世界中文论坛，还是“你自己的游戏”。据我个人所知，你是一个网络主播，你能够用这个模组来为自己带收益。不要说中国，中国人。你直接说你是一个某某网络主播可以吗朋友，我们都爱自己的祖国

I want to ask you a question, what is the so-called "my world Chinese version", which means "my world Chinese Forum", or "your own game". As far as I know, you are a network anchor, you can use this module to bring benefits for yourself. Don't talk about China, Chinese people. Can you say that you are a network anchor, friend? We all love our motherland

**Comment by q804991929** [comment]
> > 您好，作者。我來自中國。我可以將您的模塊轉移到我的世界中國版嗎？讓更多的中國朋友喜歡您的作品並將其應用於我的服務器嗎？得到您的認可對我來說是我的榮幸
> > 中文：作者，你好。我來自中國。我可以把這個模組搬運到我的世界中國版上嗎？並兼職到我的服務器上嗎？如果得到您的同意，我將萬分榮幸
> 
> 我想问你一个问题，什么是所谓的“我的世界中国版”，是指“我的世界中文论坛，还是“你自己的游戏”。据我个人所知，你是一个网络主播，你能够用这个模组来为自己带收益。不要说中国，中国人。你直接说你是一个某某网络主播可以吗朋友，我们都爱自己的祖国
> 
> I want to ask you a question, what is the so-called "my world Chinese version", which means "my world Chinese Forum", or "your own game". As far as I know, you are a network anchor, you can use this module to bring benefits for yourself. Don't talk about China, Chinese people. Can you say that you are a network anchor, friend? We all love our motherland
你这么厉害的吗？我是网络主播你都知道，我都怀疑你是哪里人了？哈哈。言归正，我说的“我的世界中国版”就是网易代理的我的世界。我也是网易CC直播的一名小主播而已。我自己开服想入驻网易，所以想取得该模组的应用授权，希望作者能同意@
