### ISSUE TITLE
Possible Conflict with Create Mod

### ISSUE THREAD

**Issue by Camawama** [MrCrayfish/MrCrayfishVehicleMod#391]
The create mod uses something to do with Minecarts. While driving a plane around in the air, the game shortly crashes and says something about minecarts and the create mod. 
[crash-2021-01-10_23.51.28-client.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/5794185/crash-2021-01-10_23.51.28-client.txt)

**Comment by ThePlasticPotato** [comment]
I had this happening too- however, after the latest create update released on january thirteenth, it no longer occurs. I believe it was fixed.

**Comment by jacksonhardaway** [comment]
This isn't an issue with the vehicle mod, it's an issue with Create and has been fixed with their latest update.
