### ISSUE TITLE
Crash while flying planes in my modpack.

### ISSUE THREAD

**Issue by Camawama** [MrCrayfish/MrCrayfishVehicleMod#392]
Possible conflict with the Create Mod. The create mod uses something to do with Minecarts. While driving a plane around in the air, the game shortly crashes and says something about minecarts and the create mod. 
[crash-2021-01-10_23.51.28-client.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/5794185/crash-2021-01-10_23.51.28-client.txt)

**Comment by MrCrayfish** [comment]
Another thread mentioned this was an issue with Create and has been fixed. https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/391
