### ISSUE TITLE
[1.16.4] The game crashes when the map is loaded

### ISSUE THREAD

**Issue by 2353739509** [MrCrayfish/MrCrayfishVehicleMod#395]
First of all, thank you for making such an interesting module.
Let's talk about my problems,When I loaded the map, the game crashed and encountered the following problems
[Parsing error loading recipe vehicle:boost_ramp
com.google.gson.JsonSyntaxException: Unknown item 'vehicle:boost_pad']
I downloaded this module from curseforge.The version of jar package is 0.45.2.This integration package was easy to use a few days ago.I tested all the vehicles, which is very interesting, My friend.That's cool.But there are problems today. I put the log in the attachment. Of course, it may also be the conflict of other mods. If I need to provide the integration package, please send me an email. The email address is 2353739509@qq.com . I'm sorry that there may be something wrong with English grammar, because it is formed by translation. My friend, I wish you a happy life.
[thelog.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/5834494/thelog.txt)

**Comment by jacksonhardaway** [comment]
The recipe error is not the issue (it's not causing the crash) and the crash is not caused by the Vehicle Mod.

**Comment by 2353739509** [comment]
Thank you for your answer. I'll look for other questions. The Chinese New Year is coming. I wish you a happy new year and all the best, my friend



 
---Original---
