### ISSUE TITLE
[1.16.3] Ender sap and blaze juice not pumping into Fluid mixer

### ISSUE THREAD

**Issue by kitkam** [MrCrayfish/MrCrayfishVehicleMod#398]
I have the vehicle mod loaded into my minecraft server, and for what ever reason, i cannot get both ender sap and blaze juice to pump into the fluid mixer. I've redirected the pipes between both systems well over 10 times, waited for the tanks to fill, etc. Sometimes, only one fluid will pump and not the other (I have not had any succeful attempts at getting Ender Sap to go into the fluid mixer.) Theres some screen shots provided of what the system looks like. 

I don't know what's exactly happening, but I know for a fact its annoying. I've rewatched the "How to make Fuelium" and the gas pump video 3 times to see if I misplaced anything, or something but nothing seemed wrong. I'm not sure if this is a bug, or im just placing something incorrectly. 
![2021-01-27_03 52 13](https://user-images.githubusercontent.com/77915053/105981976-f0985800-6053-11eb-8e9a-6b964f165493.png)
![2021-01-27_03 52 10](https://user-images.githubusercontent.com/77915053/105981986-f2621b80-6053-11eb-96a9-cce48a3dc302.png)
![2021-01-27_03 52 07](https://user-images.githubusercontent.com/77915053/105981990-f42bdf00-6053-11eb-92a2-1f904aba740c.png)
![2021-01-27_03 52 02](https://user-images.githubusercontent.com/77915053/105981998-f5f5a280-6053-11eb-96e9-e108a86ed334.png)

**Comment by kitkam** [comment]
Oddest thing is, every time when I re-do the pipes, it will drain the fluid from the extractors (Like the animation will occur of it being "pumped" into the pipes, but it simply doesn't go into the mixer. Its like the fluid is getting lost in the pipes, or something.

**Comment by MrCrayfish** [comment]
The pipes are facing the wrong direction. I should probably make this more clear.
