### ISSUE TITLE
EnderIO item conduits not connecting to fluid extractors and fluid mixers (bump of issue #266)

### ISSUE THREAD

**Issue by varappdev** [MrCrayfish/MrCrayfishVehicleMod#399]
Minecraft version: 1.12.2
Forge version: 14.23.5.2855
Mod version: 0.44.1

As issue #266 said, EnderIO item conduits do not connect to any fuel fabrication blocks in the vehicle mod. What is strange is that the fluid conduits do connect, but not the item ones.
What is even weirder is that thermal dynamics itemducts connect, also as said in issue #266 

Please fix this as EnderIO is focused on compactness but thermal dynamics is very **_C H O N K Y_** and uses up a lot of space. 
[Here](https://prnt.sc/xq05xb) is an image showing this.

**Comment by MrCrayfish** [comment]
Only the top and bottom can be used for item input/output. This makes sense for the Fluid Mixer, however there could definitely be an exception for the Fluid Extractor. I'm not too familiar with Ender IO and how the conduits work, so any more details will be helpful with improving the vehicle mod.

**Comment by varappdev** [comment]
The only problem is that in the image that is a fluid extractor. I tried all sides, top, bottom, front, back, left and right.

**Comment by MrCrayfish** [comment]
Did you even read my previous reply? I mentioned that only the top and bottom of the block work for item input/output. I said I would implement an exception for the fluid extractor.

**Comment by varappdev** [comment]
EnderIO conduits work like any other regular pipes. The most special thing about them is that you can compact multiple types of conduits in a 1 block space, forming a cluster of conduits [just like this](https://prnt.sc/xrgbg2). You can cover the conduits using a facade to make them look like regular. Then putting a cluster of item anf fluid conduits next to the fluid mixer/extractor, only the fluid conduit will connect [just like this](https://prnt.sc/xrggej).
And sorry fur that but I just did not understand the previous reply. And also, the item conduit does not work with the fluid mixer or extractor no matter the side.
This is from my understanding that you want to say that the conduits will work on top and bottom. [They do not](https://prnt.sc/xrgjqe). 
I have already tried that.

**Comment by MrCrayfish** [comment]
Sorry for my rude comments. I believe most of this should be fixed in newer versions of the mod, I can't say for 1.12.2 since it's now discontinued.
