### ISSUE TITLE
[VehicleMod v0.8.0] Vehicle Coloring Issue on Multiplayer Servers

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishVehicleMod#4]
Coloring vehicles works great on singleplayer, but on a multiplayer server, it is disabled and all previously colored vehicles from the last Vehicles mod version have lost coloring and are now white, after the update.

**Comment by MrCrayfish** [comment]
Cheers for the report. Fixed in https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/e7c661c62b57af3cdf327f92a3013455629d908f
