### ISSUE TITLE
Short-cut for Creative.

### ISSUE THREAD

**Issue by khdhhde21** [MrCrayfish/MrCrayfishVehicleMod#409]
I use Creative mode all the time. Let's say I want to add a Mini Bus. It requires 128 iron ingots and some other parts. Does that mean I must double-click 128 times on the iron ingot icon just to instantiate one bus? Is there a short-cut for Creative? Thanks.

**Comment by MrCrayfish** [comment]
Are you talking about getting the iron ingots from the creative menu? If so you can just Shift + Left Click to grab a whole stack. The better method is to just grab the vehicle crates from the Vehicle Mod tab instead of using the workbench.

**Comment by khdhhde21** [comment]
Thank you. Vehicle crates work great!
