### ISSUE TITLE
Crash when driving certain vehicles (1.16.4)

### ISSUE THREAD

**Issue by SharpForceTrauma** [MrCrayfish/MrCrayfishVehicleMod#412]
I haven't tested with all vehicles, but apparently with the Off Roader and the Lawn mower, attempting to drive them causes the game to freeze and then CTD
[crash-2021-02-15_17.54.57-client.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/5984730/crash-2021-02-15_17.54.57-client.txt)
It appears to relate to Create, any help?

**Comment by MrCrayfish** [comment]
Nothing in this log indidicates it's my mod.
