### ISSUE TITLE
(Hint) Don't close problems without first solving them

### ISSUE THREAD

**Issue by Marcos-MMD** [MrCrayfish/MrCrayfishVehicleMod#421]
@MrCrayfish I advise you not to close problems without first solving them because normally when a problem is closed, it usually means that it has already been solved. Do not do it anymore

**Comment by Marcos-MMD** [comment]
@MrCrayfish I advise you not to close problems without first solving them because normally when a problem is closed, it usually means that it has already been solved. Do not do it anymore

**Comment by MrCrayfish** [comment]
Remember that time you created a Device Mod issue on the Vehicle Mod repo? Yeah, good try.

**Comment by MrCrayfish** [comment]
Also you're using the issue tracker as a support ticket system. Maybe word your issues like "Add a guide on how to use vehicle jack" instead of "I don't know how to use mod" and I may be a little more inclined to implement your suggestion.
