### ISSUE TITLE
Unable to disable fuel in single player

### ISSUE THREAD

**Issue by shields42** [MrCrayfish/MrCrayfishVehicleMod#425]
Haven't tried server-side yet, but I don't see an option to disable fuel use locally. I see the setting in the source code:

`public final ForgeConfigSpec.BooleanValue fuelEnabled;`

But I can't figure out how to set it for single player.

**Comment by MrCrayfish** [comment]
Disabling fuel is located in the server-config folder which is located in your world folder.
