### ISSUE TITLE
Vehicles don't spawn?

### ISSUE THREAD

**Issue by CallMeIlai** [MrCrayfish/MrCrayfishVehicleMod#432]
Anytime I place a vehicle crate in survival, it just sits there. No animation, nothing. Am I dumb and doing something wrong...?

**Comment by CallMeIlai** [comment]
Side note: When placed in creative, it does the normal animation and the vehicle pops out like normal.

**Comment by MrCrayfish** [comment]
You have to use a wrench in survival to open it
