### ISSUE TITLE
Problem w shopping cart

### ISSUE THREAD

**Issue by Robertosonoio** [MrCrayfish/MrCrayfishVehicleMod#44]
I can't push it becouse with that control i take that (sorry for the english but i'm italian)

**Comment by Robertosonoio** [comment]
I'm sorry 😅. Lol. Thank you 😁

**Comment by RyanCR03** [comment]
no there is a bug where when you shift click a shopping cart you can push it, but because of the new picking up the vehicles it doesnt work
