### ISSUE TITLE
Very high CPU usage by Fluid Pipe (1.12.2)

### ISSUE THREAD

**Issue by wanou067** [MrCrayfish/MrCrayfishVehicleMod#440]
Hello,
I have a problem with MrCrayfish Vehicle mod or maybe with Randoms Things mod. When all chunks are unloaded (no players connected on the server), when we join again the TPS are very low (between 0.5 and 4). I ran some debugs with spark and tick profiler, and found 2 mods that seems to use a lot of CPU: MrCrayfish Vehicle mod's fluid pipe and Randoms Things redstone interface. Look at the spark report, maybe you will understand what's the problem. Is it caused by vehicle mod or by randomthings ? is it an incompatibility ?
https://spark.lucko.me/6mcF7YNwQR
(I also created an issue an Random Things github)

**Comment by MrCrayfish** [comment]
![image](https://user-images.githubusercontent.com/4958241/116607823-a0da6d00-a971-11eb-9c7e-e91b2ef887d5.png)

Seems to point to Random Things. Thanks for the Spark report, actually helpful!
