### ISSUE TITLE
Crashing when placing a vehicle crate!

### ISSUE THREAD

**Issue by StatiK404** [MrCrayfish/MrCrayfishVehicleMod#441]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_20.16.0.2_Forge_1.12.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.1.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  weaponlib (mw_2.0-0.4.4.6_mc1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 5/2/21 1:43 PM
Description: Rendering entity in world

java.lang.ArrayIndexOutOfBoundsException: 28
	at net.minecraftforge.client.model.pipeline.LightUtil.unpack(LightUtil.java:173)
	at net.minecraftforge.client.model.pipeline.LightUtil.putBakedQuad(LightUtil.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.block.model.BakedQuad.pipe(BakedQuad.java:146)
	at net.minecraftforge.client.model.pipeline.LightUtil.renderQuadColorSlow(LightUtil.java:303)
	at net.minecraftforge.client.model.pipeline.LightUtil.renderQuadColor(LightUtil.java:318)
	at com.mrcrayfish.vehicle.util.RenderUtil.renderQuads(RenderUtil.java:200)
	at com.mrcrayfish.vehicle.util.RenderUtil.renderModel(RenderUtil.java:172)
	at com.mrcrayfish.vehicle.util.RenderUtil.renderModel(RenderUtil.java:158)
	at com.mrcrayfish.vehicle.util.RenderUtil.renderColoredModel(RenderUtil.java:116)
	at com.mrcrayfish.vehicle.client.render.AbstractRenderVehicle.renderDamagedPart(AbstractRenderVehicle.java:93)
	at com.mrcrayfish.vehicle.client.render.AbstractRenderVehicle.renderDamagedPart(AbstractRenderVehicle.java:48)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderGoKart.render(RenderGoKart.java:20)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderGoKart.render(RenderGoKart.java:15)
	at com.mrcrayfish.vehicle.client.render.RenderLandVehicleWrapper.render(RenderLandVehicleWrapper.java:89)
	at com.mrcrayfish.vehicle.client.render.RenderLandVehicleWrapper.render(RenderLandVehicleWrapper.java:16)
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.doRender(RenderEntityVehicle.java:61)
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_76986_a(RenderEntityVehicle.java:19)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at com.mrcrayfish.vehicle.client.render.tileentity.VehicleCrateRenderer.render(VehicleCrateRenderer.java:125)
	at com.mrcrayfish.vehicle.client.render.tileentity.VehicleCrateRenderer.func_192841_a(VehicleCrateRenderer.java:29)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:201)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:157)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1032)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1801)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.pipeline.LightUtil.unpack(LightUtil.java:173)
	at net.minecraftforge.client.model.pipeline.LightUtil.putBakedQuad(LightUtil.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.block.model.BakedQuad.pipe(BakedQuad.java:146)
	at net.minecraftforge.client.model.pipeline.LightUtil.renderQuadColorSlow(LightUtil.java:303)
	at net.minecraftforge.client.model.pipeline.LightUtil.renderQuadColor(LightUtil.java:318)
	at com.mrcrayfish.vehicle.util.RenderUtil.renderQuads(RenderUtil.java:200)
	at com.mrcrayfish.vehicle.util.RenderUtil.renderModel(RenderUtil.java:172)
	at com.mrcrayfish.vehicle.util.RenderUtil.renderModel(RenderUtil.java:158)
	at com.mrcrayfish.vehicle.util.RenderUtil.renderColoredModel(RenderUtil.java:116)
	at com.mrcrayfish.vehicle.client.render.AbstractRenderVehicle.renderDamagedPart(AbstractRenderVehicle.java:93)
	at com.mrcrayfish.vehicle.client.render.AbstractRenderVehicle.renderDamagedPart(AbstractRenderVehicle.java:48)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderGoKart.render(RenderGoKart.java:20)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderGoKart.render(RenderGoKart.java:15)
	at com.mrcrayfish.vehicle.client.render.RenderLandVehicleWrapper.render(RenderLandVehicleWrapper.java:89)
	at com.mrcrayfish.vehicle.client.render.RenderLandVehicleWrapper.render(RenderLandVehicleWrapper.java:16)
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.doRender(RenderEntityVehicle.java:61)
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_76986_a(RenderEntityVehicle.java:19)

-- Entity being rendered --
Details:
	Entity Type: vehicle:go_kart (com.mrcrayfish.vehicle.entity.vehicle.EntityGoKart)
	Entity ID: 673
	Entity Name: Go Kart
	Entity's Exact location: 1.88, 0.00, -0.51
	Entity's Block location: World: (1,0,-1), Chunk: (at 1,0,15 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: com.mrcrayfish.vehicle.client.render.RenderEntityVehicle@7ad19f46
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 0.079959035
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at com.mrcrayfish.vehicle.client.render.tileentity.VehicleCrateRenderer.render(VehicleCrateRenderer.java:125)
	at com.mrcrayfish.vehicle.client.render.tileentity.VehicleCrateRenderer.func_192841_a(VehicleCrateRenderer.java:29)

-- Block Entity Details --
Details:
	Name: vehicle:vehicle_crate // com.mrcrayfish.vehicle.tileentity.TileEntityVehicleCrate
	Block type: ID #1120 (tile.vehicle.vehicle_crate // com.mrcrayfish.vehicle.block.BlockVehicleCrate // vehicle:vehicle_crate)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (1350,62,-601), Chunk: (at 6,3,7 in 84,-38; contains blocks 1344,0,-608 to 1359,255,-593), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
	Actual block type: ID #1120 (tile.vehicle.vehicle_crate // com.mrcrayfish.vehicle.block.BlockVehicleCrate // vehicle:vehicle_crate)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:201)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:157)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1032)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1801)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['StatiK_404'/39, l='MpServer', x=1348.12, y=62.00, z=-600.49]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1338,4,-590), Chunk: (at 10,0,2 in 83,-37; contains blocks 1328,0,-592 to 1343,255,-577), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
	Level time: 1121 game time, 1121 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 55 total; [EntityCrackedZombie['Cracked Zombie'/257, l='MpServer', x=1322.50, y=62.00, z=-674.50], EntityCrackedZombie['Cracked Zombie'/259, l='MpServer', x=1280.50, y=62.00, z=-552.50], EntityCrackedZombie['Cracked Zombie'/260, l='MpServer', x=1276.50, y=62.00, z=-554.50], EntityCrackedZombie['Cracked Zombie'/261, l='MpServer', x=1272.50, y=62.00, z=-549.50], EntityCrackedZombie['Cracked Zombie'/134, l='MpServer', x=1346.13, y=62.00, z=-591.23], EntityCrackedZombie['Cracked Zombie'/262, l='MpServer', x=1270.50, y=62.00, z=-552.50], EntityCrackedZombie['Cracked Zombie'/136, l='MpServer', x=1357.43, y=62.00, z=-591.04], EntityItem['item.item.porkchopRaw'/649, l='MpServer', x=1349.24, y=62.00, z=-658.82], EntityCrackedZombie['Cracked Zombie'/267, l='MpServer', x=1390.50, y=62.00, z=-540.50], EntityItem['item.item.rottenFlesh'/651, l='MpServer', x=1366.37, y=62.00, z=-606.61], EntityCrackedZombie['Cracked Zombie'/268, l='MpServer', x=1387.50, y=62.00, z=-538.50], EntityCrackedZombie['Cracked Zombie'/141, l='MpServer', x=1404.50, y=62.00, z=-560.50], EntityCrackedZombie['Cracked Zombie'/142, l='MpServer', x=1401.50, y=62.00, z=-563.50], EntityCrackedZombie['Cracked Zombie'/654, l='MpServer', x=1287.50, y=62.00, z=-637.50], EntityCrackedZombie['Cracked Zombie'/271, l='MpServer', x=1362.15, y=62.00, z=-649.50], EntityCrackedZombie['Cracked Zombie'/655, l='MpServer', x=1289.50, y=62.00, z=-640.50], EntityCrackedZombie['Cracked Zombie'/272, l='MpServer', x=1361.07, y=62.00, z=-650.39], EntityCrackedZombie['Cracked Zombie'/656, l='MpServer', x=1293.50, y=62.00, z=-638.50], EntityCrackedZombie['Cracked Zombie'/657, l='MpServer', x=1288.50, y=62.00, z=-639.50], EntityItem['item.item.rottenFlesh'/664, l='MpServer', x=1359.19, y=62.00, z=-598.63], EntityScent['entity.EntityScent.name'/671, l='MpServer', x=1350.50, y=62.50, z=-600.50], EntityCrackedPigZombie['Cracked PigZombie'/292, l='MpServer', x=1422.50, y=62.00, z=-674.50], EntityCrackedPigZombie['Cracked PigZombie'/293, l='MpServer', x=1426.50, y=62.00, z=-671.50], EntityCrackedPigZombie['Cracked PigZombie'/294, l='MpServer', x=1427.50, y=62.00, z=-668.50], EntityBanoAdapted['Adapted Bolster'/297, l='MpServer', x=1360.63, y=62.00, z=-596.27], EntityCrackedPigZombie['Cracked PigZombie'/171, l='MpServer', x=1341.50, y=62.00, z=-654.50], EntityCrackedPigZombie['Cracked PigZombie'/176, l='MpServer', x=1302.50, y=62.00, z=-565.50], EntityCrackedPigZombie['Cracked PigZombie'/177, l='MpServer', x=1304.50, y=62.00, z=-565.50], EntityCrackedZombie['Cracked Zombie'/182, l='MpServer', x=1387.02, y=62.00, z=-590.36], EntityCrackedPigZombie['Cracked PigZombie'/59, l='MpServer', x=1363.50, y=62.00, z=-538.50], EntityCrackedPigZombie['Cracked PigZombie'/62, l='MpServer', x=1356.50, y=62.00, z=-539.50], EntityCrackedPigZombie['Cracked PigZombie'/192, l='MpServer', x=1311.78, y=62.00, z=-596.18], EntityPlayerSP['StatiK_404'/39, l='MpServer', x=1348.12, y=62.00, z=-600.49], EntityLatchedRenderer['unknown'/68, l='MpServer', x=8.50, y=65.00, z=8.50], EntityCrackedZombie['Cracked Zombie'/203, l='MpServer', x=1332.50, y=62.00, z=-549.50], EntityCrackedZombie['Cracked Zombie'/208, l='MpServer', x=1325.42, y=62.00, z=-655.43], EntityChicken['Chicken'/220, l='MpServer', x=1423.50, y=62.00, z=-630.50], EntityChicken['Chicken'/221, l='MpServer', x=1426.50, y=62.00, z=-628.50], EntityChicken['Chicken'/222, l='MpServer', x=1424.50, y=62.00, z=-626.50], EntityChicken['Chicken'/223, l='MpServer', x=1424.50, y=62.00, z=-628.50], EntityPig['Pig'/224, l='MpServer', x=1363.47, y=62.00, z=-648.13], EntityPig['Pig'/225, l='MpServer', x=1363.58, y=62.00, z=-646.80], EntityPig['Pig'/226, l='MpServer', x=1363.00, y=62.00, z=-645.66], EntityCrackedZombie['Cracked Zombie'/101, l='MpServer', x=1386.81, y=62.00, z=-586.54], EntityCrackedPigZombie['Cracked PigZombie'/236, l='MpServer', x=1358.50, y=62.00, z=-667.50], EntityCrackedPigZombie['Cracked PigZombie'/237, l='MpServer', x=1361.50, y=62.00, z=-663.50], EntityCrackedPigZombie['Cracked PigZombie'/245, l='MpServer', x=1349.42, y=62.00, z=-521.73], EntityCrackedPigZombie['Cracked PigZombie'/246, l='MpServer', x=1350.50, y=62.00, z=-529.50], EntityCrackedPigZombie['Cracked PigZombie'/247, l='MpServer', x=1350.50, y=62.00, z=-530.50], EntityCrackedPigZombie['Cracked PigZombie'/632, l='MpServer', x=1272.50, y=62.00, z=-553.50], EntityCrackedPigZombie['Cracked PigZombie'/633, l='MpServer', x=1273.50, y=62.00, z=-552.50], EntityCrackedPigZombie['Cracked PigZombie'/634, l='MpServer', x=1275.50, y=62.00, z=-555.50], EntityCrackedPigZombie['Cracked PigZombie'/252, l='MpServer', x=1313.50, y=62.00, z=-564.50], EntityCrackedPigZombie['Cracked PigZombie'/125, l='MpServer', x=1395.58, y=62.00, z=-626.80], EntityCrackedPigZombie['Cracked PigZombie'/253, l='MpServer', x=1313.50, y=62.00, z=-565.50]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/68, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1180157776 bytes (1125 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -Xmx4G -Xms4G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version               | Source                                                    | Signature                                |
	|:------ |:--------------------- |:--------------------- |:--------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                | minecraft.jar                                             | None                                     |
	| LCHIJA | mcp                   | 9.42                  | minecraft.jar                                             | None                                     |
	| LCHIJA | FML                   | 8.0.99.99             | forge-1.12.2-14.23.5.2854.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2854          | forge-1.12.2-14.23.5.2854.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core     | 1.12.2-1.0            | minecraft.jar                                             | None                                     |
	| LCHIJA | obfuscate             | 0.4.2                 | minecraft.jar                                             | None                                     |
	| LCHIJA | securitycraft         | v1.8.20.2             | [1.12.2]+SecurityCraft+v1.8.20.2.jar                      | None                                     |
	| LCHIJA | salwayseat            | 1.0                   | alwayseat-1.1.jar                                         | None                                     |
	| LCHIJA | betterbuilderswands   | 0.13.2                | BetterBuildersWands-1.12.2-0.13.2.271+5997513 - Kopya.jar | None                                     |
	| LCHIJA | forgelin              | 1.8.4                 | Forgelin-1.8.4.jar                                        | None                                     |
	| LCHIJA | betterfoliage         | 2.3.1                 | BetterFoliage-MC1.12-2.3.1.jar                            | None                                     |
	| LCHIJA | biomesoplenty         | 7.0.1.2441            | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar             | None                                     |
	| LCHIJA | chameleon             | 1.12-4.1.3            | Chameleon-1.12-4.1.3.jar                                  | None                                     |
	| LCHIJA | classicbar            | @VERSION@             | classicbar-0.5.4.jar                                      | None                                     |
	| LCHIJA | clumps                | 3.1.2                 | Clumps-3.1.2.jar                                          | None                                     |
	| LCHIJA | corona                | 1.0.0                 | CoronaMask-1.12.2-v1.jar                                  | None                                     |
	| LCHIJA | extendedrenderer      | v1.0                  | coroutil-1.12.1-1.2.37.jar                                | None                                     |
	| LCHIJA | coroutil              | 1.12.1-1.2.37         | coroutil-1.12.1-1.2.37.jar                                | None                                     |
	| LCHIJA | configmod             | v1.0                  | coroutil-1.12.1-1.2.37.jar                                | None                                     |
	| LCHIJA | cosmeticarmorreworked | 1.12.2-v5a            | CosmeticArmorReworked-1.12.2-v5a.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | crackedzombiemod      | 3.8.1                 | crackedzombiemod-1.12.2-3.8.1-95.jar                      | None                                     |
	| LCHIJA | cdm                   | 0.4.1                 | device-mod-0.4.1-1.12.2.jar                               | None                                     |
	| LCHIJA | elevatorid            | 1.3.14                | ElevatorMod-1.12.2-1.3.14.jar                             | None                                     |
	| LCHIJA | cfm                   | 6.3.1                 | furniture-6.3.1-1.12.2.jar                                | None                                     |
	| LCHIJA | ichunutil             | 7.2.2                 | iChunUtil-1.12.2-7.2.2.jar                                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | inventoryhud          | 3.1.8                 | InventoryHud_1.12.2.forge-3.1.9.jar                       | None                                     |
	| LCHIJA | ironchest             | 1.12.2-7.0.67.844     | ironchest-1.12.2-7.0.72.847.jar                           | None                                     |
	| LCHIJA | ironfurnaces          | 1.3.5                 | ironfurnaces-1.3.5.jar                                    | None                                     |
	| LCHIJA | jei                   | 4.15.0.296            | jei_1.12.2-4.15.0.296.jar                                 | None                                     |
	| LCHIJA | malisiscore           | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                              | None                                     |
	| LCHIJA | malisisdoors          | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                             | None                                     |
	| LCHIJA | mantle                | 1.12-1.3.3.55         | Mantle-1.12-1.3.3.55.jar                                  | None                                     |
	| LCHIJA | mcwbridges            | 1.0.4                 | mcw-bridges-1.0.4-mc1.12.2.jar                            | None                                     |
	| LCHIJA | mw                    | 0.4.4.6               | mw_2.0-0.4.4.6_mc1.12.2.jar                               | None                                     |
	| LCHIJA | pogosticks            | 1.3.1                 | PogoSticks-1.12.2-1.3.1.jar                               | None                                     |
	| LCHIJA | silentlib             | 3.0.13                | SilentLib-1.12.2-3.0.14+168.jar                           | None                                     |
	| LCHIJA | scalinghealth         | 1.3.37                | ScalingHealth-1.12.2-1.3.42+147.jar                       | None                                     |
	| LCHIJA | shouldersurfing       | 1.16                  | ShoulderSurfing-1.12.2-1.15.1.jar                         | d6261bb645f41db84c74f98e512c2bb43f188af2 |
	| LCHIJA | spartanweaponry       | beta 1.3.8            | SpartanWeaponry-1.12.2-beta-1.3.8.jar                     | None                                     |
	| LCHIJA | srparasites           | 1.8.2                 | SRParasites-1.12.2v1.8.2.jar                              | None                                     |
	| LCHIJA | storagedrawers        | 5.2.2                 | StorageDrawers-1.12.2-5.4.2.jar                           | None                                     |
	| LCHIJA | tconstruct            | 1.12.2-2.13.0.183     | TConstruct-1.12.2-2.13.0.183.jar                          | None                                     |
	| LCHIJA | theoneprobe           | 1.4.28                | theoneprobe-1.12-1.4.28.jar                               | None                                     |
	| LCHIJA | toolbelt              | 1.9.13                | ToolBelt-1.12.2-1.9.13.jar                                | None                                     |
	| LCHIJA | torchmaster           | 1.8.1.82              | torchmaster_1.12.2-1.8.1.82.jar                           | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| LCHIJA | vehicle               | 0.44.1                | vehicle-mod-0.44.1-1.12.2.jar                             | None                                     |
	| LCHIJA | waystones             | 4.1.0                 | Waystones_1.12.2-4.1.0.jar                                | None                                     |
	| LCHIJA | xaerominimap          | 20.16.0.2             | Xaeros_Minimap_20.16.0.2_Forge_1.12.jar                   | None                                     |
	| LCHIJA | zombieawareness       | 1.12.1-1.11.16        | zombieawareness-1.12.1-1.11.16.jar                        | None                                     |
	| LCHIJA | llibrary              | 1.7.19                | llibrary-1.7.19-1.12.2.jar                                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
XaeroMinimapPlugin (Xaeros_Minimap_20.16.0.2_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.1.jar)
  com.teamderpy.shouldersurfing.asm.ShoulderTransformations
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
weaponlib (mw_2.0-0.4.4.6_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 457.63' Renderer: 'GeForce GTX 1660 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.63, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, file/minecraft-dungeons-chests-v1-1.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 457.63
	OpenGlRenderer: GeForce GTX 1660 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by MrCrayfish** [comment]
Not updating 1.12.2 anymore. Potnetial fix though is updating Optifine to the latest version or downgrading to older versions

**Comment by StatiK404** [comment]
thanks anyways!
