### ISSUE TITLE
Crate doesn't open in multiplayer

### ISSUE THREAD

**Issue by Ilasek2** [MrCrayfish/MrCrayfishVehicleMod#443]
Hi i have server with friends and if i create or take vehicle crate from creative and place it it doens't open. If i take crate from creative crate lose all nbt :// some help?

**Comment by MrCrayfish** [comment]
Mohist breaks the mod

**Comment by Ilasek2** [comment]
So mod dont work on servers right?

**Comment by MrCrayfish** [comment]
No, specifically Mohist breaks the logic of Forge. A normal Forge server will work fine.
