### ISSUE TITLE
Airplane keeps crashing my game

### ISSUE THREAD

**Issue by KiarashGaming** [MrCrayfish/MrCrayfishVehicleMod#444]
I mostly use this mod to build a big city. Very recently, I finished building a small regional airport for the planes in this mod to fly to. When I flew the plane for about 10 seconds my gamed crashed. In details, the game froze, it said "saving world" and then the game closed and opened minecraft launcher which said "game crashed due to unexpected error". I tried a few more times but still no luck, and my game never crashes while doing anything else on that world. It's only the planes. Is there any way I can fix this?

**Comment by MrCrayfish** [comment]
Can you send the crash report? Also which version of mod and minecraft?

**Comment by KiarashGaming** [comment]
I was playing on minecraft 1.16.3, and I was using the latest version of the mod. (v0.45.1).

**Comment by KiarashGaming** [comment]
wait sorry i meant minecraft 1.16.4*

**Comment by MrCrayfish** [comment]
Can you send the crash report?

**Comment by KiarashGaming** [comment]
Hey! I noticed I accidentally put an older version of the mod for 1.15.2 in my mods folder. I just switched my game versions. Thanks for your time though!
