### ISSUE TITLE
Can't spawn vehicle in survival

### ISSUE THREAD

**Issue by ghoodsite** [MrCrayfish/MrCrayfishVehicleMod#447]
Hi people have built vehicles, but once they have placed the crate down, it does nothing. Are we doing something wrong?

**Comment by MrCrayfish** [comment]
Are you using the wrench to open them?

**Comment by josh1368** [comment]
When I place anything it just disappears

**Comment by MrCrayfish** [comment]
@josh1368 Create a new issue with a video
