### ISSUE TITLE
Buckets of sap

### ISSUE THREAD

**Issue by CombatMonke** [MrCrayfish/MrCrayfishVehicleMod#452]
I dont know what to do with the sap and juice buckets, i cant put the sap/juice back in the extractors or mixers.
![image](https://user-images.githubusercontent.com/84431465/118754617-4cae0480-b81c-11eb-8483-c0cad4827dce.png)

**Comment by MrCrayfish** [comment]
Not an issue. You can right click the inputs on the mixer to put them back in
