### ISSUE TITLE
IT DOESNT SPAWN

### ISSUE THREAD

**Issue by diagamez** [MrCrayfish/MrCrayfishVehicleMod#457]
I crafted a shopping cart on my server and it doesnt spawn, for some reason on singleplayes it works, hmmm (its not that its an aternos server I think because I've had another server with the vehicle mod and then it worked)
(details:
server host:aternos
installed mods: 
jei, abnormals core, abnormals delight,adaptive performance tweaks, aquaculture 2, autoreglib, autumnity, backpacked, backpacker, betterend (forge), buzzier bees, cleanview, create, create plus, doggy talents, exotic birds, farmers delight, farmers delight compats
FPS reducer, kleeslabs, macaws doors, mantle, mrcrayfish furniture mod, the vehicle mod (obviously), obfuscate, pams harvestcraft crops/food core/trees/food extended, quark, quark oddities, scuba gear, storage drawers, twilight forest, tinkers construct, WTHIT

details about the cart:
motor: electric motor wood
wheels: normal wheels,
dye: none)

**Comment by MrCrayfish** [comment]
If you're using Mohist, it won't work.
