### ISSUE TITLE
Crash at start 

### ISSUE THREAD

**Issue by D3laz** [MrCrayfish/MrCrayfishVehicleMod#46]
Hi, ive a issue since a few days 
Here is my report 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.9.32_mc1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 10/8/18 6:16 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
	at com.mrcrayfish.vehicle.entity.EntityAirVehicle.getFlapDirection(EntityAirVehicle.java:233)
	at com.mrcrayfish.vehicle.entity.EntityAirVehicle.updateLift(EntityAirVehicle.java:191)
	at com.mrcrayfish.vehicle.entity.EntityAirVehicle.updateVehicleMotion(EntityAirVehicle.java:55)
	at com.mrcrayfish.vehicle.entity.EntityPoweredVehicle.onUpdateVehicle(EntityPoweredVehicle.java:230)
	at com.mrcrayfish.vehicle.entity.EntityVehicle.func_70071_h_(EntityVehicle.java:198)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.vehicle.entity.EntityAirVehicle.getFlapDirection(EntityAirVehicle.java:233)
	at com.mrcrayfish.vehicle.entity.EntityAirVehicle.updateLift(EntityAirVehicle.java:191)
	at com.mrcrayfish.vehicle.entity.EntityAirVehicle.updateVehicleMotion(EntityAirVehicle.java:55)
	at com.mrcrayfish.vehicle.entity.EntityPoweredVehicle.onUpdateVehicle(EntityPoweredVehicle.java:230)
	at com.mrcrayfish.vehicle.entity.EntityVehicle.func_70071_h_(EntityVehicle.java:198)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: vehicle:sports_plane (com.mrcrayfish.vehicle.entity.vehicle.EntitySportsPlane)
	Entity ID: 2721
	Entity Name: entity.sports_plane.name
	Entity's Exact location: 401.83, 90.00, -431.96
	Entity's Block location: World: (401,90,-432), Chunk: (at 1,5,0 in 25,-27; contains blocks 400,0,-432 to 415,255,-417), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['AT_Delaz'/2555, l='MpServer', x=362.40, y=63.00, z=-380.82]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (128,64,176), Chunk: (at 0,4,0 in 8,11; contains blocks 128,0,176 to 143,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 111059094 game time, 1395944 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 107 total; [EntityCreeper['Creeper'/2571, l='MpServer', x=324.50, y=76.00, z=-301.50], GCEntityClientPlayerMP['AT_Delaz'/2555, l='MpServer', x=362.40, y=63.00, z=-380.82], EntityWolf['Tom'/2573, l='MpServer', x=304.62, y=79.00, z=-364.74], EntityWolf['Loup'/2574, l='MpServer', x=305.35, y=79.00, z=-365.98], EntityMinecartHopper['Wagonnet à entonnoir'/2575, l='MpServer', x=333.50, y=59.06, z=-384.75], EntityMinecartHopper['Wagonnet à entonnoir'/2576, l='MpServer', x=332.50, y=58.06, z=-382.10], EntityMinecartHopper['Wagonnet à entonnoir'/2577, l='MpServer', x=333.50, y=56.06, z=-383.51], EntityOcelot['Lamie'/2583, l='MpServer', x=293.79, y=79.00, z=-357.40], EntityWolf['Félix'/2584, l='MpServer', x=291.72, y=79.00, z=-359.09], EntityItemFrame['Item Frame'/2585, l='MpServer', x=312.50, y=56.50, z=-376.97], EntityOcelot['Faitye'/2586, l='MpServer', x=305.88, y=79.00, z=-375.21], EntityItem['item.item.string'/2587, l='MpServer', x=314.01, y=79.00, z=-373.01], EntityItem['item.item.reeds'/2591, l='MpServer', x=306.46, y=63.00, z=-319.14], EntityItem['item.item.reeds'/2594, l='MpServer', x=306.72, y=63.00, z=-320.20], EntityItem['item.item.reeds'/2595, l='MpServer', x=306.83, y=64.00, z=-321.90], EntitySheep['Mouton'/2597, l='MpServer', x=318.43, y=72.00, z=-302.74], EntityLift['Elevator'/2598, l='MpServer', x=340.50, y=62.00, z=-375.50], EntityMinecartHopper['Wagonnet à entonnoir'/2599, l='MpServer', x=349.45, y=43.06, z=-333.87], EntityItem['item.item.reeds'/2601, l='MpServer', x=302.13, y=64.00, z=-322.71], EntityHorse['Cheval'/2604, l='MpServer', x=296.49, y=79.00, z=-405.48], EntityHorse['Prunelle'/2606, l='MpServer', x=293.34, y=79.00, z=-405.35], EntityATV['entity.atv.name'/2609, l='MpServer', x=314.42, y=64.00, z=-442.46], EntityGoKart['entity.go_kart.name'/2610, l='MpServer', x=319.44, y=64.00, z=-438.72], EntityMiniBike['entity.mini_bike.name'/2611, l='MpServer', x=318.34, y=64.00, z=-438.35], EntitySmartCar['entity.smart_car.name'/2612, l='MpServer', x=306.77, y=64.00, z=-434.05], EntityHorse['Epona'/2619, l='MpServer', x=284.26, y=79.00, z=-409.92], EntityLawnMower['entity.lawn_mower.name'/2627, l='MpServer', x=300.46, y=64.00, z=-432.86], EntityBat['Chauve-souris'/2631, l='MpServer', x=315.52, y=23.06, z=-456.33], EntitySheep['Mouton'/2633, l='MpServer', x=386.51, y=77.00, z=-320.08], EntityOcelot['Azure'/2636, l='MpServer', x=295.05, y=79.00, z=-374.59], EntityOcelot['Nala'/2637, l='MpServer', x=299.46, y=79.00, z=-372.96], EntityWolf['Kyubi'/2638, l='MpServer', x=296.58, y=78.94, z=-383.63], EntityWolf['Flocon'/2639, l='MpServer', x=300.48, y=79.00, z=-368.55], EntityWolf['Canelle'/2640, l='MpServer', x=286.95, y=79.00, z=-360.12], EntityWolf['Daxter'/2641, l='MpServer', x=283.09, y=79.00, z=-358.56], EntityOcelot['Louve'/2642, l='MpServer', x=283.30, y=79.00, z=-364.75], EntitySheep['Mouton'/2646, l='MpServer', x=308.28, y=77.00, z=-406.51], EntityLift['Elevator'/2651, l='MpServer', x=391.50, y=63.00, z=-501.50], EntityMoped['Moped'/2656, l='MpServer', x=325.75, y=64.00, z=-440.75], EntityOffRoader['entity.off_roader.name'/2658, l='MpServer', x=333.33, y=64.00, z=-438.73], EntityIronGolem['Golem de fer'/2406, l='MpServer', x=343.13, y=32.00, z=-393.01], EntityIronGolem['Golem de fer'/2407, l='MpServer', x=338.89, y=31.39, z=-401.78], EntityZombie['Zombie'/2408, l='MpServer', x=375.21, y=15.00, z=-362.50], EntityZombie['Zombie'/2409, l='MpServer', x=378.30, y=2.50, z=-364.30], EntityCreeper['Creeper'/2410, l='MpServer', x=378.30, y=2.50, z=-365.64], EntityZombie['Zombie'/2411, l='MpServer', x=378.30, y=2.50, z=-366.36], EntitySkeleton['Squelette'/2412, l='MpServer', x=374.50, y=15.00, z=-367.50], EntitySkeleton['Squelette'/2413, l='MpServer', x=378.30, y=2.50, z=-364.94], EntityZombie['Zombie'/2414, l='MpServer', x=379.02, y=2.50, z=-364.90], EntitySpider['Araignée'/2415, l='MpServer', x=376.34, y=22.00, z=-366.70], EntityZombie['Zombie'/2416, l='MpServer', x=377.15, y=29.00, z=-362.14], EntityZombie['Zombie'/2417, l='MpServer', x=372.08, y=29.00, z=-359.80], EntitySkeleton['Squelette'/2418, l='MpServer', x=377.28, y=28.33, z=-362.99], EntityZombie['Zombie'/2419, l='MpServer', x=375.08, y=29.00, z=-367.62], EntityBat['Chauve-souris'/2420, l='MpServer', x=382.11, y=17.10, z=-357.25], EntityZombie['Zombie'/2421, l='MpServer', x=381.50, y=22.00, z=-363.50], EntityCreeper['Creeper'/2422, l='MpServer', x=382.50, y=22.00, z=-362.50], EntityBat['Chauve-souris'/2423, l='MpServer', x=377.14, y=31.10, z=-363.93], EntityBat['Chauve-souris'/2424, l='MpServer', x=379.35, y=29.55, z=-364.50], EntityBat['Chauve-souris'/2425, l='MpServer', x=387.75, y=17.10, z=-362.56], EntitySpider['Araignée'/2426, l='MpServer', x=387.30, y=23.35, z=-359.09], EntityCreeper['Creeper'/2427, l='MpServer', x=386.50, y=22.00, z=-361.50], EntityCreeper['Creeper'/2428, l='MpServer', x=386.50, y=22.00, z=-363.50], EntityBat['Chauve-souris'/2429, l='MpServer', x=385.18, y=29.03, z=-367.69], EntityBat['Chauve-souris'/2430, l='MpServer', x=383.01, y=22.94, z=-364.52], EntityBat['Chauve-souris'/2431, l='MpServer', x=385.70, y=30.43, z=-358.39], EntityBat['Chauve-souris'/2432, l='MpServer', x=384.02, y=29.56, z=-365.47], EntitySkeleton['Squelette'/2433, l='MpServer', x=355.52, y=42.00, z=-356.64], EntityZombie['Zombie'/2700, l='MpServer', x=440.50, y=62.00, z=-401.50], EntityItem['item.item.arrow'/2704, l='MpServer', x=378.41, y=71.00, z=-439.55], EntityItem['item.item.bone'/2705, l='MpServer', x=378.30, y=71.00, z=-440.77], EntityItem['item.item.arrow'/2706, l='MpServer', x=378.88, y=71.00, z=-437.52], EntityItem['item.item.bone'/2707, l='MpServer', x=378.16, y=71.00, z=-438.05], EntitySheep['Mouton'/2708, l='MpServer', x=429.74, y=93.00, z=-368.48], EntityItem['item.item.rottenFlesh'/2709, l='MpServer', x=397.38, y=70.00, z=-351.34], EntitySheep['Mouton'/2712, l='MpServer', x=420.50, y=84.00, z=-435.75], EntityPig['Cochon'/2713, l='MpServer', x=428.47, y=80.00, z=-444.25], EntitySquid['Poulpe'/2715, l='MpServer', x=400.46, y=47.49, z=-417.61], EntityItem['item.item.dyePowder.black'/2716, l='MpServer', x=410.54, y=48.00, z=-417.12], EntityItem['item.item.dyePowder.black'/2717, l='MpServer', x=409.01, y=48.00, z=-417.86], EntityCreeper['Creeper'/2718, l='MpServer', x=401.50, y=71.00, z=-431.50], EntityWitch['Sorcière'/2719, l='MpServer', x=400.50, y=79.00, z=-419.50], EntityWitch['Sorcière'/2720, l='MpServer', x=400.50, y=79.00, z=-420.50], EntitySportsPlane['entity.sports_plane.name'/2721, l='MpServer', x=401.83, y=90.00, z=-431.96], EntitySheep['Mouton'/2724, l='MpServer', x=439.28, y=81.00, z=-458.45], EntitySquid['Poulpe'/2725, l='MpServer', x=393.87, y=47.04, z=-416.09], EntitySquid['Poulpe'/2726, l='MpServer', x=397.57, y=47.12, z=-415.82], EntitySquid['Poulpe'/2727, l='MpServer', x=394.82, y=47.11, z=-407.23], EntitySquid['Poulpe'/2728, l='MpServer', x=397.93, y=47.71, z=-405.91], EntityItemFrame['Item Frame'/2729, l='MpServer', x=394.50, y=65.50, z=-413.03], EntityItemFrame['Item Frame'/2730, l='MpServer', x=395.50, y=65.50, z=-413.03], EntityZombie['Zombie'/2731, l='MpServer', x=388.50, y=70.00, z=-412.50], EntityZombie['Zombie'/2732, l='MpServer', x=385.50, y=69.00, z=-414.50], EntityCreeper['Creeper'/2733, l='MpServer', x=398.91, y=79.00, z=-411.71], EntityZombieVillager['Zombie-villageois'/2734, l='MpServer', x=399.23, y=79.00, z=-410.56], EntityItem['item.item.dyePowder.black'/2735, l='MpServer', x=407.92, y=47.00, z=-405.13], EntityZombie['Zombie'/2736, l='MpServer', x=411.22, y=48.00, z=-405.54], EntityZombie['Zombie'/2737, l='MpServer', x=415.50, y=48.00, z=-411.30], EntitySkeleton['Squelette'/2738, l='MpServer', x=405.50, y=76.00, z=-415.50], EntitySkeleton['Squelette'/2739, l='MpServer', x=400.24, y=76.00, z=-409.17], EntitySquid['Poulpe'/2743, l='MpServer', x=394.75, y=47.28, z=-416.98], EntityZombie['Zombie'/2744, l='MpServer', x=389.50, y=73.00, z=-417.50], EntityPig['Cochon'/2747, l='MpServer', x=441.75, y=79.00, z=-426.50], EntitySheep['Mouton'/2748, l='MpServer', x=415.50, y=81.00, z=-391.45], EntityCreeper['Creeper'/2752, l='MpServer', x=439.50, y=76.00, z=-349.50], EntitySheep['Mouton'/2753, l='MpServer', x=439.48, y=86.00, z=-342.28], EntitySkeleton['Squelette'/209, l='MpServer', x=372.50, y=15.00, z=-372.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2739)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 744164248 bytes (709 MB) / 3321888768 bytes (3168 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2732 Optifine OptiFine_1.12.2_HD_U_E1 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                    | Source                                                       | Signature                                |
	|:------ |:------------------- |:-------------------------- |:------------------------------------------------------------ |:---------------------------------------- |
	| UCHIJA | minecraft           | 1.12.2                     | minecraft.jar                                                | None                                     |
	| UCHIJA | mcp                 | 9.42                       | minecraft.jar                                                | None                                     |
	| UCHIJA | FML                 | 8.0.99.99                  | forge-1.12.2-14.23.4.2732.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge               | 14.23.4.2732               | forge-1.12.2-14.23.4.2732.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | creativecoredummy   | 1.0.0                      | minecraft.jar                                                | None                                     |
	| UCHIJA | micdoodlecore       |                            | minecraft.jar                                                | None                                     |
	| UCHIJA | obfuscate           | 0.2.5                      | minecraft.jar                                                | None                                     |
	| UCHIJA | securitycraft       | v1.8.7                     | [1.12.x]+SecurityCraft+v1.8.7.jar                            | None                                     |
	| UCHIJA | appliedenergistics2 | rv6-stable-1               | appliedenergistics2-rv6-stable-1.jar                         | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCHIJA | aroma1997core       | 2.0.0.0                    | Aroma1997Core-1.12.2-2.0.0.0.jar                             | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJA | aroma1997sdimension | 1.3.0.0.b37                | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar            | None                                     |
	| UCHIJA | buildcraftlib       | 7.99.18                    | buildcraft-7.99.18.jar                                       | None                                     |
	| UCHIJA | buildcraftcore      | 7.99.18                    | buildcraft-7.99.18.jar                                       | None                                     |
	| UCHIJA | buildcrafttransport | 7.99.18                    | buildcraft-7.99.18.jar                                       | None                                     |
	| UCHIJA | forgelin            | 1.7.4                      | Forgelin-1.7.4.jar                                           | None                                     |
	| UCHIJA | bcextrapipes        | 1                          | bc-extra-pipes-1.12.2-1.jar                                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | bibliocraft         | 2.4.3                      | BiblioCraft[v2.4.3][MC1.12.0].jar                            | None                                     |
	| UCHIJA | buildcraftbuilders  | 7.99.18                    | buildcraft-7.99.18.jar                                       | None                                     |
	| UCHIJA | buildcraftenergy    | 7.99.18                    | buildcraft-7.99.18.jar                                       | None                                     |
	| UCHIJA | buildcraftfactory   | 7.99.18                    | buildcraft-7.99.18.jar                                       | None                                     |
	| UCHIJA | buildcraftrobotics  | 7.99.18                    | buildcraft-7.99.18.jar                                       | None                                     |
	| UCHIJA | buildcraftsilicon   | 7.99.18                    | buildcraft-7.99.18.jar                                       | None                                     |
	| UCHIJA | catwalks            | 1.12.2-4.0.44              | catwalks-1.12.2-4.0.44.jar                                   | None                                     |
	| UCHIJA | cdm                 | 0.4.1                      | cdm-0.4.1-mc1.12.2.jar                                       | None                                     |
	| UCHIJA | cfm                 | 5.13.0                     | cfm-5.13.0-mc1.12.2.jar                                      | None                                     |
	| UCHIJA | chameleon           | 1.12-4.1.3                 | Chameleon-1.12-4.1.3.jar                                     | None                                     |
	| UCHIJA | codechickenlib      | 3.2.2.353                  | CodeChickenLib-1.12.2-3.2.2.353-universal.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | chickenchunks       | 2.4.1.73                   | ChickenChunks-1.12.2-2.4.1.73-universal.jar                  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | creativecore        | 1.9.9                      | CreativeCore_v1.9.32_mc1.12.2.jar                            | None                                     |
	| UCHIJA | galacticraftcore    | 4.0.1.181                  | GalacticraftCore-1.12.2-4.0.1.181.jar                        | None                                     |
	| UCHIJA | galacticraftplanets | 4.0.1.181                  | Galacticraft-Planets-1.12.2-4.0.1.181.jar                    | None                                     |
	| UCHIJA | mjrlegendslib       | 1.12.2-1.1.5               | MJRLegendsLib-1.12.2-1.1.5.jar                               | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJA | extraplanets        | 1.12.2-0.4.3               | ExtraPlanets-1.12.2-0.4.3.jar                                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJA | waila               | 1.8.26                     | Hwyla-1.8.26-B41_1.12.2.jar                                  | None                                     |
	| UCHIJA | jei                 | 4.11.0.212                 | jei_1.12.2-4.11.0.212.jar                                    | None                                     |
	| UCHIJA | lunatriuscore       | 1.2.0.42                   | LunatriusCore-1.12.2-1.2.0.42-universal.jar                  | None                                     |
	| UCHIJA | malisiscore         | 1.12.2-6.4.0               | malisiscore-1.12.2-6.4.0.jar                                 | None                                     |
	| UCHIJA | malisisadvert       | 1.12.2-6.1.0               | malisisadvert-1.12.2-6.1.0.jar                               | None                                     |
	| UCHIJA | malisisblocks       | 1.12.2-6.1.0               | malisisblocks-1.12.2-6.1.0.jar                               | None                                     |
	| UCHIJA | malisisdoors        | 1.12.2-7.3.0               | malisisdoors-1.12.2-7.3.0.jar                                | None                                     |
	| UCHIJA | minecolonies        | 1.12.2-0.9.1-RELEASE       | minecolonies-1.12.2-0.9.1-RELEASE-universal.jar              | None                                     |
	| UCHIJA | opframe             | 1.4.0                      | OnlinePicFrame_v1.4.19_mc1.12.2.jar                          | None                                     |
	| UCHIJA | redstoneflux        | 2.0.1                      | RedstoneFlux-1.12-2.0.1.2-universal.jar                      | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJA | p455w0rdslib        | 2.0.35                     | p455w0rdslib-1.12-2.0.35.jar                                 | None                                     |
	| UCHIJA | placeableitems      | 3.3                        | placeableitems-3.3.jar                                       | None                                     |
	| UCHIJA | ptrmodellib         | 1.0.2                      | PTRLib-1.0.2.jar                                             | None                                     |
	| UCHIJA | qsilkspawners       | 1.0.0                      | Q-Silk-Spawners-Mod-1.12.2.jar                               | None                                     |
	| UCHIJA | rcroads             | 0.3.0                      | RC+Roads+0.3.0.jar                                           | None                                     |
	| UCHIJA | redstonepaste       | 1.7.5                      | redstonepaste-mc1.12-1.7.5.jar                               | None                                     |
	| UCHIJA | silentlib           | 2.3.1                      | SilentLib-1.12.2-2.3.1-107.jar                               | None                                     |
	| UCHIJA | simplefluidtanks    | 1.12.2-1.7.1.1             | simplefluidtanks-1.12.2-1.7.1.1.jar                          | None                                     |
	| UCHIJA | thutcore            | 5.19.8                     | thutcore-1.12.2-5.19.8.jar                                   | None                                     |
	| UCHIJA | thutcore_compat     | 1.0                        | thutcore-1.12.2-5.19.8.jar                                   | None                                     |
	| UCHIJA | thuttech            | 6.1.5                      | thuttech-1.12.2-6.1.5.jar                                    | None                                     |
	| UCHIJA | vehicle             | 0.25.0                     | vehicle-0.25.0-mc1.12.2.jar                                  | None                                     |
	| UCHIJA | wawla               | 2.5.261                    | Wawla-1.12.2-2.5.261.jar                                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | waystones           | 4.0.15                     | Waystones_1.12.1-4.0.15.jar                                  | None                                     |
	| UCHIJA | wct                 | 3.10.82                    | WirelessCraftingTerminal-1.12.2-3.10.82.jar                  | None                                     |
	| UCHIJA | worldedit           | 6.1.8                      | worldedit-forge-mc1.12-6.1.8-dist.jar                        | None                                     |
	| UCHIJA | worldeditcuife2     | 2.1.2-mf-1.12-14.21.1.2387 | WorldEdit+CUI+Forge+Edition+2-2.1.2-mf-1.12-14.21.1.2387.jar | None                                     |
	| UCHIJA | xaerominimap        | 1.15.2                     | Xaeros_Minimap_1.15.2_Forge_1.12.jar                         | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.9.32_mc1.12.2.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ForgelinPlugin (Forgelin-1.7.4.jar)
  
ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.jar)
  
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.36' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	AE2 Version: stable rv6-stable-1 for Forge 14.23.3.2655
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2732
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.36, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Realistic Adventure [64x].zip
	Current Language: Français (France)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E1
	OptiFine Build: 20180628-111228
	Render Distance Chunks: 30
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.14 High.zip
	OpenGlVersion: 4.6.0 NVIDIA 398.36
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by JanHolger** [comment]
Same issue as #21, but still exists in the current downloadable version.

**Comment by MrCrayfish** [comment]
Duplicate issue
