### ISSUE TITLE
The fuel pump makes every single entity show

### ISSUE THREAD

**Issue by Peiprjs** [MrCrayfish/MrCrayfishVehicleMod#468]
It's really weird, but the fuel pump makes me see all the entities in a 32-block radius (?).
![With the pump](https://user-images.githubusercontent.com/72313029/122634377-38407e80-d0de-11eb-8033-6479a1f37e91.png)
![W/O the pump](https://user-images.githubusercontent.com/72313029/122634382-3e365f80-d0de-11eb-9f24-45a680f4b091.png)

Maybe it's a Create-MCVM issue?

**Comment by Peiprjs** [comment]
First image is with the pump, second one is without

**Comment by Xtreviouz** [comment]
If you're using Optifine disable Fast Render (Options > Video Settings > Performance).
Helped for me.
