### ISSUE TITLE
the mrcrayfish vehicle spawner mod in not working for me in my aternos server

### ISSUE THREAD

**Issue by Galaxy1234577** [MrCrayfish/MrCrayfishVehicleMod#471]
i tried to spawn a car in my aternos server but it say 'cant summon object' but when i tried to summon the car in single player it worked..
server- aternos
version- 1.12.2 forge 14.23.5.2855
mods i have- mrcrayfish furniture mod, mrcrayfish vehicle mod, mrcrayfish vehicle spawner, obfuscate mod, mrcrayfish gun mod, mrcrayfish devise mod, pam's harvest craft, maidens marvelous materials

**Comment by MrCrayfish** [comment]
Yeah aternos breaks the mod. Nothing I can do

**Comment by Galaxy1234577** [comment]
its ok now it works
