### ISSUE TITLE
Crash on startup with Furniture mod installed

### ISSUE THREAD

**Issue by Tsoccerguy3** [MrCrayfish/MrCrayfishVehicleMod#473]
[crash-2021-07-04_23.37.43-fml.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/6761492/crash-2021-07-04_23.37.43-fml.txt)

forge-1.16.5-36.1.32
vehicle-mod-0.45.2-1.16.3
obfuscate-0.6.2-1.16.3
furniture-7.0.0-pre22-1.16.3

**Comment by MrCrayfish** [comment]
Did you build the mod from source? If so, the code here is ahead and currently incompatible with the Furniture Mod (can be fixed though if you know what you are doing).

**Comment by Tsoccerguy3** [comment]
[crash-2021-07-05_00.20.03-client.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/6761622/crash-2021-07-05_00.20.03-client.txt)

crash without the furniture mod

**Comment by Tsoccerguy3** [comment]
yes , i just built it an hour ago

**Comment by Tsoccerguy3** [comment]
I was just trying it out . I saw it was under heavy development the last few months , Lots of stuff a WIP.

**Comment by MrCrayfish** [comment]
If you go into `assets/vehicle/vehicles/` and rename `sofa_car.json` to `couch.json` it will fix the crash.

**Comment by Tsoccerguy3** [comment]
Thanks , I don't mind testing the mod. I guess its to early to use it . Trying to use the vehicles at this point in development just crashes the game.
