### ISSUE TITLE
[Suggestion] Add support for custom fuels/fluids

### ISSUE THREAD

**Issue by aaronjurrea** [MrCrayfish/MrCrayfishVehicleMod#477]
I think many people, especially those in the modpack community, would appreciate the ability to assign custom fuels/fluids for these vehicles. The ability to differentiate which vehicles require which fuels specifically, (i.e cars use gasoline, trucks require diesel) is also incredibly useful towards a more immersive experience.

As it stands, this mod is the definitive vehicle mod for Forge 1.16.5, and that tweak would make it much more compatible with the likes of mods such as Immersive Engineering.

Thank you

**Comment by MrCrayfish** [comment]
Added in https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/9b705fed5cd9d09c7ff30c6845dd766b9607cded
