### ISSUE TITLE
(1.16.5) seeing things like chests and book of enchanting table

### ISSUE THREAD

**Issue by pvtBlazingDeck** [MrCrayfish/MrCrayfishVehicleMod#482]
hello i was playing minecraft with my friends on a server i made, everything was good until i put down a gas pump, after that i could see chests and some other things through the wall, i asked my friends if they were also seeing but they said no, i dont know if it is because of optifine.
i still see it after i romoved it.
can someone help me fix it
![2021-07-26_17 21 16](https://user-images.githubusercontent.com/87269217/126988356-593f180f-9fb8-4958-adbb-e558543fa117.png)

**Comment by Autovw** [comment]
This is obviously an issue created by a so called "performance mod" which breaks something with vanilla rendering.
If you have any of them installed, both server and client side, you should remove them and try again.

**Comment by DevWolf31** [comment]
View the issues #446 and #468

**Comment by MrCrayfish** [comment]
Many duplicate. I'll be going through all issues within the next month
