### ISSUE TITLE
Upload a language file (es_es.lang)

### ISSUE THREAD

**Issue by DevWolf31** [MrCrayfish/MrCrayfishVehicleMod#486]
Could you create a file (es_es.lang) for your mod? Just send me the file (en_us.lang) and I will translate it to Spanish.

**Comment by MrCrayfish** [comment]
All lang files can already be found here
https://github.com/MrCrayfish/MrCrayfishVehicleMod/tree/1.16.X/src/main/resources/assets/vehicle/lang

**Comment by DevWolf31** [comment]
Ok
