### ISSUE TITLE
Crash on 1.16.X-dev branch

### ISSUE THREAD

**Issue by Tsoccerguy3** [MrCrayfish/MrCrayfishVehicleMod#493]
I was testing MrCrayfishVehicleMod latest commits to all involved mods and I get a crash. Maybe its just not finished yet , but here are the results.
[crash-2021-09-04_19.51.15-fml.txt.zip](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/7110658/crash-2021-09-04_19.51.15-fml.txt.zip)
[debug.zip](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/7110659/debug.zip)

**Comment by MrCrayfish** [comment]
Uninstall the Furniture Mod, currently bugged.
