### ISSUE TITLE
Colours seem to disappear / not work sometimes.

### ISSUE THREAD

**Issue by JacksonPlayz** [MrCrayfish/MrCrayfishVehicleMod#5]
Every now and then when I join the sponsor server the vehicles all turn white. I try to dye them but it stays as white while my friends can see them coloured. I fixed it by restarting my game.
![2018-05-10_19 49 51](https://user-images.githubusercontent.com/18062275/39904156-639c4398-548b-11e8-8281-cb9c2e4144e9.png)

**Comment by Sqaaakoi** [comment]
What version are you running? If you are on 0.8.0, update to 0.8.1

**Comment by MrCrayfish** [comment]
Update to 0.8.1
