### ISSUE TITLE
Problem with mod and dedicated server (1.16.5-dev) (a973c5622caf0f54ec27bcdb970b9887a6db67b3)

### ISSUE THREAD

**Issue by Redacted00** [MrCrayfish/MrCrayfishVehicleMod#502]
Hello! 
I ran into a problem when running a dedicated server with a test version of the mod. When you enter the server, an error gets out, and when you run it, other errors of this mod are displayed in the console
![unknown (1)](https://user-images.githubusercontent.com/38829120/140489245-a8d052fd-b40a-48bb-b035-84f3dfef0d84.png)

What should I do about this error?

**Comment by MrCrayfish** [comment]
Don't run the dev branch on a dedicated server. It's a separate branch for a reason.
