### ISSUE TITLE
1.16-DEV texure names wrong on 3 vehicles

### ISSUE THREAD

**Issue by Tsoccerguy3** [MrCrayfish/MrCrayfishVehicleMod#506]
Testing the 1.16-dev . 

I pulled the latest commits and found a regression . Some names are wrong on some vehicle parts 
causing missing textures. 

![2021-11-23_10 29 02](https://user-images.githubusercontent.com/22108822/143055519-e646e5fd-c465-4ab1-a78f-b06ed1f28280.png)

**Comment by MrCrayfish** [comment]
I just have uncommitted changes. I don't accept bugs on the development branch.

**Comment by Tsoccerguy3** [comment]
OK thanks for the update , can you push those updates please
