### ISSUE TITLE
I can't use the vehicle mod in server(when i place a crate of vehicle the vehicle wont come and and particles of it is like purple and black)

### ISSUE THREAD

**Issue by Devil-darkknight** [MrCrayfish/MrCrayfishVehicleMod#507]
hello sir!!! I use aternos for installing ur mod in server, when i downloaded it and used it the vehicles didn't appear out of the crates and also it gave the texture of unsupported blocks what to do sir.

**Comment by MrCrayfish** [comment]
Magma breaks the Vehicle Mod.
