### ISSUE TITLE
Custom Fuels are Broken!

### ISSUE THREAD

**Issue by Maximal98** [MrCrayfish/MrCrayfishVehicleMod#508]
No matter how hard i try, when attempting to use IE biodiesel or IP diesel, it does not work. it does not go in jerry cans or gas pumps.
i have checked the server configs and there is no "ValidFuels" setting. it does not exist.
the issue suggesting this was closed by crayfish and custom fuels were added (via a direct commit wich makes it harder to track) but, in the newest version, 0.45.2 which was released 24 days ago.
the commit was about 4 months ago so i assume this is a bug.

"happy" bugfixing!

**Comment by MrCrayfish** [comment]
It's coming in the next update
