### ISSUE TITLE
Three bugs in 1.16.5-dev 

### ISSUE THREAD

**Issue by Maximal98** [MrCrayfish/MrCrayfishVehicleMod#509]
1. the steering wheel of the minibus is broken, it does not appear to have a model, it is a square with a missing texture, which makes it hard to see when not in F5 mode.
2. Keys are broken. when they are bound to a vehicle, the vehicle no longer makes engine sounds and does not take fuel in survival.
3. The Jet ski is not in the center of the workshop window, it is outside the window. 
![image](https://user-images.githubusercontent.com/55159959/144632088-2fa53eee-65db-45cf-aefb-dce3397e914e.png)
(Its axis which it spins on is in the normal position, but the ski is not where it should be)

**Comment by MrCrayfish** [comment]
Don't report bugs for dev branch
