### ISSUE TITLE
Keys cannot be colored

### ISSUE THREAD

**Issue by wolfmasterm** [MrCrayfish/MrCrayfishVehicleMod#51]
Mrcrayfish I don’t know if u fixed dis yet but the key colors don’t show. If you have fixed this then I don’t know what’s wrong. But if you didn’t than plz fix this bug😣😣😣😣

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/576aaa6021adf38f2f1c39cc9d65f685396bd30c
