### ISSUE TITLE
Can't Craft Any Vehicles In Workstation 1.16.5

### ISSUE THREAD

**Issue by DogToy** [MrCrayfish/MrCrayfishVehicleMod#516]
I'm using vehicle-mod-0.45.2-1.16.3
Ive been using the mod for a long time now and it worked just fine but for some reason it doesn't craft even after I have all the materials I have tried restarting and it did nothing.
1.16.5-forge-36.2.0
![2022-01-31_18 53 43](https://user-images.githubusercontent.com/98786105/151892219-e78ab339-00ba-4107-8be8-05e7042100ff.png)
.

**Comment by MrCrayfish** [comment]
Pretty sure this is a compatibily issue, couldn't pinpoint which mod since I am not sure what you are running.

**Comment by DogToy** [comment]
ok
