### ISSUE TITLE
broken animation when use certain vehicles 

### ISSUE THREAD

**Issue by BluePepero** [MrCrayfish/MrCrayfishVehicleMod#52]
When I use certain vehicles the player start shaking when I try to see around, and when I stop using them the model of the player has the arms up, like zombies.

The first image shows the vehicle that has this problem (at least with me) and well... the second one, shows the other issue I mentioned and the plus one... the couch is broken. 

I use the last update: vehicle-0.27.0-mc1.12.2
and obfuscate-0.2.5-1.12.2

![2018-10-15_12 36 52](https://user-images.githubusercontent.com/44177872/46974750-bde01680-d079-11e8-8398-de98a68ee4ca.png)
![2018-10-15_12 37 24](https://user-images.githubusercontent.com/44177872/46974801-da7c4e80-d079-11e8-8c6c-09a74aed2386.png)

**Comment by MrCrayfish** [comment]
Don't use the shopping cart, it's broken
