### ISSUE TITLE
1.16.X-dev branch with not compile . Is this intentional?

### ISSUE THREAD

**Issue by Tsoccerguy3** [MrCrayfish/MrCrayfishVehicleMod#528]
For the last 8 months commits to the 1.16.X-dev branch with not compile . Is this intentional?

I get this java compile error can you please fix this . or explain how to fix this . 

G:\Dev\vm>gradlew build
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/6.9/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build

> Task :compileJava
G:\Dev\vm\src\main\java\com\mrcrayfish\vehicle\client\handler\ControllerHandler.java:107: error: cannot find symbol
                PacketHandler.getPlayChannel().sendToServer(new MessageCycleSeats());
                                                                ^
  symbol:   class MessageCycleSeats
  location: class com.mrcrayfish.vehicle.client.handler.ControllerHandler
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 11s
1 actionable task: 1 executed

**Comment by MrCrayfish** [comment]
I've just pushed a commit, it should compile now.
