### ISSUE TITLE
1.16.X-dev old bug , missed texture since August 2021

### ISSUE THREAD

**Issue by Tsoccerguy3** [MrCrayfish/MrCrayfishVehicleMod#529]
Here is 1 old bug in 1.16.X-dev
As you can see the mini-bus steering wheel texture is wrong since 2021 . not sure if you are using a new mini-bus steering wheel or using go-cart wheel . I changed MiniBusRenderer.java

Not sure what's up with the sports car name and textures , invisible .

    @Override
    protected void render(@Nullable MiniBusEntity vehicle, MatrixStack matrixStack, IRenderTypeBuffer renderTypeBuffer, float partialTicks, int light)
    {
        this.renderDamagedPart(vehicle, SpecialModels.MINI_BUS_BODY.getModel(), matrixStack, renderTypeBuffer, light);
        this.renderSteeringWheel(vehicle, SpecialModels.MINI_BUS_STEERING_WHEEL.getModel(), -5.0, 4.9039, 15.6378, 0.7F, -67.5F, matrixStack, renderTypeBuffer, light, partialTicks);
    }

	To

	    @Override
    protected void render(@Nullable MiniBusEntity vehicle, MatrixStack matrixStack, IRenderTypeBuffer renderTypeBuffer, float partialTicks, int light)
    {
        this.renderDamagedPart(vehicle, SpecialModels.MINI_BUS_BODY.getModel(), matrixStack, renderTypeBuffer, light);
        this.renderSteeringWheel(vehicle, SpecialModels.GO_KART_STEERING_WHEEL.getModel(), -5.0, 4.9039, 15.6378, 0.7F, -67.5F, matrixStack, renderTypeBuffer, light, partialTicks);
    } 

![2022-05-27_04 29 48](https://user-images.githubusercontent.com/22108822/170666405-347da758-5010-4657-b1db-60e3643d8afd.png)
![2022-05-27_04 49 51](https://user-images.githubusercontent.com/22108822/170666413-8cb66118-942a-43e1-8b71-ffe8f5e8534e.png)

**Comment by MrCrayfish** [comment]
Not taking bug reports on dev branch.
