### ISSUE TITLE
Currently unable to put fuel in the bathtub

### ISSUE THREAD

**Issue by Spiko360** [MrCrayfish/MrCrayfishVehicleMod#532]
hi, i was just wanting to reach out on how im supposed to fuel the bathtub in survival mod? i seem unable to figure it out or there is a bug 0.44.1 version of vehicle involving the creation of the bathtub and no way to fuel it. any help would be appreciated thank you

**Comment by MrCrayfish** [comment]
Won't be fixed. I don't maintain the 1.12.2 verison anymore
