### ISSUE TITLE
vehicle doesn't spawn(please help)

### ISSUE THREAD

**Issue by Datexcz** [MrCrayfish/MrCrayfishVehicleMod#538]
when i place vehicle it doesnt open. here is video https://drive.google.com/file/d/17wW0mo1S3N3Q2DHL5320QZ3gX0pCJCf_/view?usp=sharing

**Comment by MrCrayfish** [comment]
Not that I can tell you are on one but there is a problem with custom servers like Magma and Aternos. I can't fix it unfortuantely since it's their software causing the problem.
