### ISSUE TITLE
the sofacopter is bugged

### ISSUE THREAD

**Issue by RaulAandGyt** [MrCrayfish/MrCrayfishVehicleMod#543]
i've installed the mod in 1.14.4 and the model is bugging a lot
also in the furniture mod it doesn't apper a lot of things.
I think its a problem of obfuscate.

Hope you can solve it
!

**Comment by MrCrayfish** [comment]
The furniture mod is being redesigned from scratch and the sofa is not available yet hence why the sofa copter doesn't display correctly.
