### ISSUE TITLE
Crash by Starting Minecraft 1.12.2 with Vehicle Mod version 0.28.0

### ISSUE THREAD

**Issue by Titoo8899** [MrCrayfish/MrCrayfishVehicleMod#55]
Hi,
I have found a bug with the newest Mod version. It works normal by start Forge but in many time it crash by the end of loading. Her is the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.1.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  CamPatchingLoader (1.12.2.minecamera-1.1.2.jar)
  offlineskins (OfflineSkins-1.12.2-v4-core.jar)
  CamPatchingLoader (CMDCam+v1.3.0+mc1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.17.jar)
  wings (wings-1.1.0-1.12.2.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.0.jar)
  HCASM (HammerCore-1.12.2-2.0.3.1.jar)
  CreativePatchingLoader (CreativeCore_v1.9.35_mc1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre120_mc1.12.2.jar)
  FMLPlugin (elulib-0.1.12.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  LoadingPlugin (Quark-r1.5-130.jar)
  EmoticonsCore (emoticons-0.1-1.12.2.jar)
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 10/26/18 5:10 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MrCrayfish's Vehicle Mod (vehicle)
Caused by: java.lang.VerifyError: (class: javax/vecmath/Tuple3d, method: scaleAdd signature: (DLjavax/vecmath/Tuple3f;)V) Incompatible argument to function
	at com.mrcrayfish.vehicle.client.EntityRaytracer$MatrixTransformation.transform(EntityRaytracer.java:901)
	at com.mrcrayfish.vehicle.client.EntityRaytracer.init(EntityRaytracer.java:682)
	at com.mrcrayfish.vehicle.proxy.ClientProxy.init(ClientProxy.java:138)
	at com.mrcrayfish.vehicle.VehicleMod.onInit(VehicleMod.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 820005640 bytes (782 MB) / 7113539584 bytes (6784 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2771 136 mods loaded, 133 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                            | Version           | Source                                                  | Signature                                |
	|:----- |:----------------------------- |:----------------- |:------------------------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft                     | 1.12.2            | minecraft.jar                                           | None                                     |
	| UCHI  | mcp                           | 9.42              | minecraft.jar                                           | None                                     |
	| UCHI  | FML                           | 8.0.99.99         | forge-1.12.2-14.23.5.2771.jar                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge                         | 14.23.5.2771      | forge-1.12.2-14.23.5.2771.jar                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | MineCameraDummy               | 1.0.0             | minecraft.jar                                           | None                                     |
	| UCHI  | creativecoredummy             | 1.0.0             | minecraft.jar                                           | None                                     |
	| UCHI  | littletilescore               | 1.0.0             | minecraft.jar                                           | None                                     |
	| UCHI  | obfuscate                     | 0.2.6             | minecraft.jar                                           | None                                     |
	| UCHI  | clothesline-hooks             | 1.12.2-0.0.1.0    | minecraft.jar                                           | None                                     |
	| UCHI  | elucore                       | 1.0               | minecraft.jar                                           | None                                     |
	| UCHI  | minecamera                    | 1.1.1             | 1.12.2.minecamera-1.1.2.jar                             | None                                     |
	| UCHI  | securitycraft                 | v1.8.9            | [1.12.2]+SecurityCraft+v1.8.9.jar                       | None                                     |
	| UCHI  | fistful_of_hay                | 1.0.1             | a_fistful_of_hay-1.0.1.jar                              | None                                     |
	| UCHI  | applecore                     | 3.1.3             | AppleCore-mc1.12.2-3.1.3.jar                            | None                                     |
	| UCHI  | arcademod                     | 2.1.5             | arcademod-2.1.5-1.12.2.jar                              | None                                     |
	| UCHI  | architecturecraft             | @VERSION@         | ArchitectureCraft-ElytraDev-Mod-1.12.2.jar              | None                                     |
	| UCHI  | quark                         | r1.5-130          | Quark-r1.5-130.jar                                      | None                                     |
	| UCHI  | autoreglib                    | 1.3-20            | AutoRegLib-1.3-20.jar                                   | None                                     |
	| UCHI  | auto_third_person             | 1.2.0             | autothirdperson-1.2.0.jar                               | None                                     |
	| UCHI  | basketcase                    | 1.0.29            | Basketcase-v1.0.29-mc1.12.2.jar                         | None                                     |
	| UCHI  | betteranimals                 | 3.0               | betteranimals-3.0.jar                                   | None                                     |
	| UCHI  | betteranimalsplus             | 1.1.4             | betteranimalsplus-1.1.4.jar                             | None                                     |
	| UCHI  | mts                           | 11.2.1            | Minecraft+Transport+Simulator-1.12.2-11.2.1.jar         | None                                     |
	| UCHI  | unuparts                      | 1.3.0             | UNU+Parts+Pack+[MTS]+1.10.2-11.2.0-1.3.0.jar            | None                                     |
	| UCHI  | btcivil                       | 1.2.1             | BlackThorne+Civilian+Pack+[MTS]+1.10.2-11.2.0-1.3.0.jar | None                                     |
	| UCHI  | blockcraftery                 | 0.1.3             | blockcraftery-0.1.3.jar                                 | None                                     |
	| UCHI  | ctm                           | MC1.12.2-0.3.2.18 | CTM-MC1.12.2-0.3.2.18.jar                               | None                                     |
	| UCHI  | chisel                        | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                            | None                                     |
	| UCHI  | cathedral                     | 1.12.2-1.9.7g     | Cathedral-1.12.2-1.9.7g.jar                             | None                                     |
	| UCHI  | chineseworkshop               | 1.2.5             | ChineseWorkshop-1.12.2_1.2.5.jar                        | None                                     |
	| UCHI  | chiselsandbits                | 14.26             | chiselsandbits-14.26.jar                                | None                                     |
	| UCHI  | cleanview                     | 1.12.2-v1a        | CleanView-1.12.2-v1a.jar                                | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHI  | cmdcam                        | 1.1.7             | CMDCam+v1.3.0+mc1.12.2.jar                              | None                                     |
	| UCHI  | colouredsealanterns           | 1.0               | ColouredSeaLanterns-1.12.2-1.0.jar                      | None                                     |
	| UCHI  | costumes                      | 2.0.0             | Costumes-1.12.2.jar                                     | None                                     |
	| UCHI  | creativecore                  | 1.9.9             | CreativeCore_v1.9.35_mc1.12.2.jar                       | None                                     |
	| UCHI  | customnpcs                    | 1.12              | CustomNPCs_1.12.2(26aug18).jar                          | None                                     |
	| UCHI  | ptrmodellib                   | 1.0.3             | PTRLib-1.0.3.jar                                        | None                                     |
	| UCHI  | props                         | 2.6.2             | Decocraft-2.6.2_1.12.2.jar                              | None                                     |
	| UCHI  | df-roads                      | 1.4-mc1.12.2      | df-roads-1.4-mc1.12.2.jar                               | None                                     |
	| UCHI  | dsurround                     | 3.4.9.17          | DynamicSurroundings-1.12.2-3.4.9.17.jar                 | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHI  | presets                       | 3.4.9.17          | DynamicSurroundings-1.12.2-3.4.9.17.jar                 | None                                     |
	| UCHI  | elevatorid                    | 1.3.6             | ElevatorMod-1.12.2-1.3.6.jar                            | None                                     |
	| UCHI  | emoticons                     | 0.1               | emoticons-0.1-1.12.2.jar                                | None                                     |
	| UCHI  | fairylights                   | 2.1.4             | fairylights-2.1.4-1.12.2.jar                            | None                                     |
	| UCHI  | faunaandecology               | 0.1.1             | FE-1.12.2-0.1.2.3.jar                                   | None                                     |
	| UCHI  | fcl                           | XII.43            | Fexcraft+Common+Library-XII.43.jar                      | None                                     |
	| UCHI  | fmr                           | 1.0               | Fexcraft+Common+Library-XII.43.jar                      | None                                     |
	| UCHI  | forgelin                      | 1.7.4             | Forgelin-1.7.4.jar                                      | None                                     |
	| UCHI  | freelook                      | 1.2.2             | FreeLook-1.2.2.jar                                      | None                                     |
	| UCHI  | cfm                           | 5.15.0            | furniture-5.15.0-1.12.2.jar                             | None                                     |
	| UCHI  | trackapi                      | 1.1               | TrackAPI-1.1_1.12.jar                                   | None                                     |
	| UCHI  | fvtm                          | 2.8.33            | FVTM-2.8.33-1.12.x.jar                                  | None                                     |
	| UCHI  | gnomed                        | 1.0.0             | Gnomed-1.0.jar                                          | None                                     |
	| UCHI  | gokistats                     | @version@         | gokiStats-1.2.5.1.jar                                   | None                                     |
	| UCHI  | cgm                           | 0.6.4             | guns-0.6.4-1.12.2.jar                                   | None                                     |
	| UCHI  | hammercore                    | 2.0.3.1           | HammerCore-1.12.2-2.0.3.1.jar                           | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHI  | speedsterheroes               | 1.12.2-2.0.9      | SpeedsterHeroes-1.12.2-2.0.9.jar                        | None                                     |
	| UCHI  | lucraftcore                   | 1.12.2-2.3.1      | LucraftCore-1.12.2-2.3.1.jar                            | None                                     |
	| UCHI  | heroesexpansion               | 1.12.2-1.2.0      | HeroesExpansion-1.12.2-1.2.0.jar                        | None                                     |
	| UCHI  | heroicarmory                  | 1.1.3             | heroicarmory-1.2.0.jar                                  | None                                     |
	| UCHI  | imaginary                     | 1.0.3             | imaginary-1.0.3-1.12.jar                                | None                                     |
	| UCHI  | immersiveengineering          | 0.12-86           | ImmersiveEngineering-0.12-86.jar                        | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHI  | immersiverailroading          | 1.3.3             | ImmersiveRailroading-1.3.3_1.12.jar                     | None                                     |
	| UCHI  | improvableskills              | 3.5.8r            | ImprovableSkills-1.12.2-3.5.8r.jar                      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHI  | ic2                           | 2.8.101-ex112     | industrialcraft-2-2.8.101-ex112.jar                     | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHI  | industrialrenewal             | 0.7.0             | IndustrialRenewal_1.12.2-0.7.0.jar                      | None                                     |
	| UCHI  | joessuperheroesmod            | 1.1.5             | Joe's Superheroes Mod V 1.1.5 - 1.12.jar                | None                                     |
	| UCHI  | jph                           | 1.0               | jph_1.12-1.0.jar                                        | None                                     |
	| UCHI  | jaff                          | 1.7_for_1.12      | JustAFewFish-1.7_for_1.12.jar                           | None                                     |
	| UCHI  | buildingblocks                | 1.2               | JustBuildIt+MC1.12.2+v1.2.jar                           | None                                     |
	| UCHI  | landlust                      | 1.12.2-0.3.6      | landlust-1.12.2-0.3.6.jar                               | None                                     |
	| UCHI  | limelib                       | 1.7.12            | limelib-1.12.2-1.7.12.jar                               | None                                     |
	| UCHI  | littletiles                   | 1.5.0             | LittleTiles_v1.5.0-pre120_mc1.12.2.jar                  | None                                     |
	| UCHI  | lumpi                         | 0.7               | lumpi-1.12-0.7.jar                                      | None                                     |
	| UCHI  | malisiscore                   | 1.12.2-6.4.0      | malisiscore-1.12.2-6.4.0.jar                            | None                                     |
	| UCHI  | malisisdoors                  | 1.12.2-7.3.0      | malisisdoors-1.12.2-7.3.0.jar                           | None                                     |
	| UCHI  | mcpaint                       | 1.2.2             | mcpaint-1.2.2.jar                                       | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| UCHI  | mm                            | 1.2               | MerchMod-1.2.jar                                        | None                                     |
	| UCHI  | minewatch                     | 3.13              | Minewatch-1.12.X-3.13.jar                               | None                                     |
	| UCHI  | mmmpack                       | 0.0.0             | mmmpack V.1 Beta.jar                                    | None                                     |
	| UCHI  | modernlamps                   | 1.0.3             | ModernLights-1.0.3_1.12.jar                             | None                                     |
	| UCHI  | tm                            | 1.0 - MC 1.12     | mOREs+Mod+1.0.2_beta.jar                                | None                                     |
	| UCHI  | moreswordonline               | 2.8.2             | MoreSwordOnline+v2.8.1+-+1.12.2.jar                     | None                                     |
	| UCHI  | mrcrayfishvehiclespawner      | 1.3               | Mr_Crayfish_Vehicle_Spawner_1.3.jar                     | None                                     |
	| UCHI  | mtsofficialpack               | 6.0.0             | MTS_Official_Pack_V07.jar                               | None                                     |
	| UCHI  | mw                            | 1.11.7.7          | mw-1.11.7.7_mc1.12.2.jar                                | None                                     |
	| UCHI  | currency                      | 3.1.5             | NeverEnoughCurrency-4.0.1.jar                           | None                                     |
	| UCHI  | ngtlib                        | 2.4.3             | NGTLib2.4.3-20_forge-1.12.2-14.23.2.2611.jar            | None                                     |
	| UCHI  | noctrl                        | 1.2               | noctrl-1.2.jar                                          | None                                     |
	| UCHI  | notenoughroofs                | 0.8.0.0           | notenoughroofs-1.12.2-0.8.0.0.jar                       | None                                     |
	| UCHI  | offlineskins                  | 1.12.2-v4         | OfflineSkins-1.12.2-v4.jar                              | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHI  | opframe                       | 1.4.0             | OnlinePicFrame_v1.4.21_mc1.12.2.jar                     | None                                     |
	| UCHI  | overlordanimemod              | 0.7.7             | OverlordAnimeMod1.12.2-0.7.7.jar                        | None                                     |
	| UCHI  | pme                           | 0.3               | pme-0.4.jar                                             | None                                     |
	| UCHI  | randomloot                    | 1.3               | RandomLoot-1.4.1.jar                                    | None                                     |
	| UCHI  | rcroads                       | 0.3.0             | RC+Roads+0.3.0.jar                                      | None                                     |
	| UCHI  | realsurvivor                  | 1.0.5             | real-survivor-1.0.5.jar                                 | None                                     |
	| UCHI  | redstonepaste                 | 1.7.5             | redstonepaste-mc1.12-1.7.5.jar                          | None                                     |
	| UCHI  | rockhounding_core             | 3.16              | rockhounding_core-1.12.2-3.16.jar                       | None                                     |
	| UCHI  | gbook                         | 2.8.3             | Guidebook-1.12.2-2.8.3.jar                              | None                                     |
	| UCHI  | rockhounding_rocks            | 1.12.2-3.18       | rockhounding_rocks-1.12.2-3.18.jar                      | None                                     |
	| UCHI  | rockhounding_surface          | 1.12.2-3.11       | rockhounding_surface-1.12.2-3.11.jar                    | None                                     |
	| UCHI  | rtm                           | 2.4.5             | RTM2.4.5-24_forge-1.12.2-14.23.2.2611.jar               | None                                     |
	| UCHI  | scarper                       | 1.1               | scarper-1.1.jar                                         | None                                     |
	| UCHI  | simplezoom                    | 1.3.1             | simplezoom-1.12.2-1.3.1-universal.jar                   | None                                     |
	| UCHI  | simplifiedhorses              | 1.2               | SimplifiedHorses-v1.2-1.11-1.12.2.jar                   | None                                     |
	| UCHI  | simplyconveyors               | 3.0.6             | SimplyConveyors-4.0.4.jar                               | None                                     |
	| UCHI  | sit                           | v1.1.2            | sit-1.12.x-v1.1.2.jar                                   | None                                     |
	| UCHI  | skeletalband                  | 1.0.5             | skeletalband-1.12.2-1.0.5.jar                           | None                                     |
	| UCHI  | stackable                     | 1.3.2             | stackable-1.12.2-1.3.2.jar                              | None                                     |
	| UCHI  | storyoflife                   | 0.0.1             | storyoflife-0.1.2.jar                                   | None                                     |
	| UCHI  | sm                            | 1.1               | Sunglasses+and+more+1.1.jar                             | None                                     |
	| UCHI  | tenseishitaraslimedattakenmod | 0.2.7             | TenseiShitaraSlimeDattaKenMod-1.12.2-0.2.7.jar          | None                                     |
	| UCHI  | thercmod                      | 3.2.1.0           | TheRCMod-3.2.1.0.jar                                    | None                                     |
	| UCHI  | todayisagift                  | 1.0.0             | todayisagift-1.12.2-1.0.0.jar                           | None                                     |
	| UCHI  | transprot                     | 1.5.3             | transprot-1.12.2-1.5.3.jar                              | None                                     |
	| UCHEE | vehicle                       | 0.28.0            | vehicle-mod-0.28.0-1.12.2.jar                           | None                                     |
	| UCH   | walljump                      | 1.12.2-1.2.0      | walljump-1.12.2-1.2.0.jar                               | None                                     |
	| UCH   | warpbook                      | @VERSION@         | Warpbook-1.12.2-3.1.3c.jar                              | None                                     |
	| UCH   | waystones                     | 4.0.67            | Waystones_1.12.2-4.0.67.jar                             | None                                     |
	| UCH   | weaponlevels                  | 2.5.0             | weaponlevels-2.5.0.jar                                  | None                                     |
	| UCH   | wearableblocks                | 1.1a              | WearableBlocks-1.12.2-1.1a.jar                          | None                                     |
	| UCH   | llibrary                      | 1.7.15            | llibrary-1.7.15-1.12.2.jar                              | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCH   | wings                         | 1.1.0             | wings-1.1.0-1.12.2.jar                                  | None                                     |
	| UCH   | worldedit                     | 6.1.8             | worldedit-forge-mc1.12-6.1.8-dist.jar                   | None                                     |
	| UCH   | xaerominimap                  | 1.15.9            | Xaeros_Minimap_1.15.9_Forge_1.12.jar                    | None                                     |
	| UCH   | xaeroworldmap                 | 1.3.2             | XaerosWorldMap_1.3.2_Forge_1.12.jar                     | None                                     |
	| UCH   | zwangcraft                    | 1.0.8             | zwangcraft-1.0.8.jar                                    | None                                     |
	| UCH   | btdc                          | 1.2               | btdc-1.2.jar                                            | None                                     |
	| UCH   | clothesline                   | 1.12.2-0.0.2.0    | clothesline-1.12.2-0.0.2.0-bundle.jar                   | 3bae2d07b93a5971335cb2de15230c19c103db32 |
	| UCH   | pumpkinlauncher               | 1.12.2-1.6.1      | Jack-O'-Launcher-1.12.2-1.6.1.jar                       | None                                     |
	| UCH   | elulib                        | 0.1.12            | elulib-0.1.12.jar                                       | None                                     |
	| UD    | emoticons_core                | 0.1               | minecraft.jar                                           | None                                     |
	| UD    | bauble_wings                  | 1.0.0             | wings-1.1.0-1.12.2.jar                                  | None                                     |
	| UD    | mobends_wings                 | 1.0.0             | wings-1.1.0-1.12.2.jar                                  | None                                     |

	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  squeek.applecore.asm.TransformerModuleHandler
LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.1.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
ForgelinPlugin (Forgelin-1.7.4.jar)
  
CamPatchingLoader (1.12.2.minecamera-1.1.2.jar)
  com.porpit.minecamera.transform.CamTransformer
offlineskins (OfflineSkins-1.12.2-v4-core.jar)
  lain.mods.skins.asm.ASMTransformer
CamPatchingLoader (CMDCam+v1.3.0+mc1.12.2.jar)
  com.creativemd.cmdcam.transform.CamTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.17.jar)
  org.blockartistry.DynSurround.asm.Transformer
wings (wings-1.1.0-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.0.jar)
  com.jamieswhiteshirt.clothesline.hooks.plugin.ClassTransformer
HCASM (HammerCore-1.12.2-2.0.3.1.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
CreativePatchingLoader (CreativeCore_v1.9.35_mc1.12.2.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.0-pre120_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (Quark-r1.5-130.jar)
  vazkii.quark.base.asm.ClassTransformer
EmoticonsCore (emoticons-0.1-1.12.2.jar)
  mchorse.emoticons.core.EmoCoreClassTransformer
weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.34' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 565 names; 3645 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KYmxvY2tzIHsNCiAgICBCOkNodW5rTG9hZGVyPXRydWUNCiAgICBCOlRlc3NlcmFjdD10cnVlDQp9DQoNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KICAgIEI6Ik1vZCBCcm93c2VyIj10cnVlDQoNCiAgICAjIFJlcGxhY2UgdmFuaWxsYSBmdXJuYWNlIGFuZCBicmV3aW5nIHN0YW5kIHByb2dyZXNzIGJhcnMgdG8gdXNlIHNtb290aCByZW5kZXJpbmc/IFtkZWZhdWx0OiB0cnVlXQ0KICAgIEI6IlNtb290aCBWYW5pbGxhIEd1aXMiPXRydWUNCn0NCg0KDQpkZWJ1ZyB7DQogICAgQjpSYXl0cmFjZXI9ZmFsc2UNCiAgICBCOlphcHBlcj1mYWxzZQ0KfQ0KDQoNCml0ZW1zIHsNCiAgICBCOkFjY3VtdWxhdG9yPXRydWUNCn0NCg0KDQppd3JlbmNoIHsNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpDQogICAgUzpHcmVlbj0yMkZGMjINCg0KICAgICMgV2hhdCBpcyB0aGUgY29sb3Igd2hlbiB0aGUgaG92ZXJlZCBibG9jayBpcyBOT1Qgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpDQogICAgUzpSZWQ9RkYyMjIyDQp9DQoNCg0KbmV0d29ya2luZyB7DQogICAgQjoiT2xkIE5ldHdvcmsiPXRydWUNCn0NCg0KDQoidmFuaWxsYSBpbXByb3ZlbWVudHMiIHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSBmb3JjZS1zcGF3biBFbmRlciBEcmFnb24gRWdnIG9uIEVuZGVyIERyYWdvbiBkZWF0aD8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQWx3YXlzIFNwYXduIERyYWdvbiBFZ2ciPXRydWUNCn0NCg0KDQo=
Pastebin Connection: Okay.
Dependent Mods:
    -Improvable Skills (improvableskills) @3.5.8r

	
	FVTM Addons: 
	| generic | General Essentials Pack | 1.6.2 | ....\addons\General+Essentials+Pack-1.6.2-1.12.x.jar            |
	| hcp     | Heavy Cargo Pack        | 1.4.2 | ....\addons\Heavy+Cargo+Pack-1.4.2-1.12.x.jar                   |

**Comment by Titoo8899** [comment]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MrCrayfish's Vehicle Mod (vehicle)

This is the crash and it a loader Problem please fix this. The 0.27.0 works but the 0.28.0 works not

**Comment by MrCrayfish** [comment]
Does the latest version work?

**Comment by Dadoum** [comment]
I have the same problem, the latest version not fixed this issue

**Comment by MrCrayfish** [comment]
Sounds like a CoreMod or another mod is causing the problem.
