### ISSUE TITLE
mining fluid extractor gives duplicates

### ISSUE THREAD

**Issue by Spyeedy** [MrCrayfish/MrCrayfishVehicleMod#59]
When I mine a fluid extractor with a diamond pickaxe, it drops 2 fluid extractor, one has an NBT tag and the other has no NBT tag.

Linked below is a gif showing the bug:
https://i.gyazo.com/8c95b1b62dcb051873b713692661382f.gif

**Comment by MrCrayfish** [comment]
Fixed in latest versions
