### ISSUE TITLE
[Suggestion] Mod Interaction - Immersive Petroleum Gas

### ISSUE THREAD

**Issue by MokahTGS** [MrCrayfish/MrCrayfishVehicleMod#64]
I was wondering if you could add a config option to use gas from Immersive Petroleum if the mod is present with this mod.  I know I can use craft tweaker to change recipes to convert gas to this mods fuel, but it would be cool if I could just use the gas you produce from IP's refinery as fuel for these vehicles.

**Comment by Technowix** [comment]
I second this !

**Comment by luke110206** [comment]
I also agree

**Comment by Tazzer1993** [comment]
This would be awesome.

**Comment by FireheartIndustries** [comment]
Please do this? As a workaround I've edited the config file for Immersive Petroleum to produce Fuelium as well as the other fuels, but it would be nice if we could just use gasoline and/or diesel/biodiesel for different vehicles. Like gasoline in the smaller cars and diesel in things like the off roader and tractor, etc

**Comment by darthvader45** [comment]
Agreed.  I cannot wait to use an already well-known industrial mod for this.

**Comment by Dimitry-Blitzbrieg** [comment]
I would Love to see this as a feature. Immersive Engineering and immersive petroleum are both great mods and being able to produce the fuel to operate the Vehicles in your mod would be awesome! could provide some quite interesting visuals to our builds.

**Comment by Taknax** [comment]
Also agreed, Would be perfect! Their is an addon named Vehicle Registration, but i couldnt figured out how to get work with.

**Comment by MrCrayfish** [comment]
Good news, this will be a feature in the next update. You'll be able to specify the fluids considered a fuel in the form of a config value.
https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/9b705fed5cd9d09c7ff30c6845dd766b9607cded#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26

**Comment by MokahTGS** [comment]
Awesome!

**Comment by darthvader45** [comment]
Awesome!  I'll finally be able to put IP's gasoline and diesel in this mod's fuel pumps and fuel up my vehicles realistically.

**Comment by Dimitry-Blitzbrieg** [comment]
What versions of minecraft will this feature be supported? I just wanted to ask as I still play 1.7.10 as my favorite mods get fully ported I may go to 1.12

**Comment by darthvader45** [comment]
1.16.5, I believe, though it may be possible to backport it to 1.12.2, though I doubt it will happen.

**Comment by MrCrayfish** [comment]
Only 1.16 and above.

**Comment by darthvader45** [comment]
Thanks, Cray.

**Comment by k00lk4t** [comment]
Where do I change the config? the toml file in the cfg folder doesnt have anything about supported fuels?

**Comment by MrCrayfish** [comment]
This is coming in the next major update and not available yet. I want to make sure it's a good update and not rushed. If you know what you are doing you can build the 1.16.X-dev branch to test the new features and the config option.

**Comment by k00lk4t** [comment]
ty, im not quite sure of what to do but im sure i'll figure it out :)

**Comment by darthvader45** [comment]
Loving this update, will be sure to download it when it is released.

**Comment by k00lk4t** [comment]
quick question, where is the area to enter accepted fuels in? Is it in the actual files of the mod or is it in the toml file? I'm a bit stupid when it comes to this so apoligies but I can't find anything about fuel in the toml file?

**Comment by MrCrayfish** [comment]
It's located in the server config in the server directory or in the world folder if you are playing singleplayer.

**Comment by Fr3shlama** [comment]
is there any posibility that this update will be applied to 1.12.2 aswell?
