### ISSUE TITLE
Fast-Quick_Important

### ISSUE THREAD

**Issue by mNandhu** [MrCrayfish/MrCrayfishVehicleMod#66]
Hard work-Get items-Go pro-Go legend-Get the workstation-Get the fuel_extract-Mix it-Craft vehicle-Spray it -Finnaly done-with key-Comes GrieferNoob-Spam left clicks-Vehicle Gone-the Legend Dies-Noob Yeets-Please fix
Psst! It is hints development 
To, @MrCrayfish ,

**Comment by MrCrayfish** [comment]
Please report correctly...
