### ISSUE TITLE
Big Issue 

### ISSUE THREAD

**Issue by Aston-Lit** [MrCrayfish/MrCrayfishVehicleMod#7]
Hi, I'm Aston. I'm a fan too. My obfuscate is not working at all. even I used different versions of obfuscate.

Thankyou

**Comment by Sqaaakoi** [comment]
Use the latest version

**Comment by Aston-Lit** [comment]
i did

**Comment by Aston-Lit** [comment]
and the 2.3 version

**Comment by MrCrayfish** [comment]
Saying it's "not working" points me nowhere
