### ISSUE TITLE
[Bug] Fuel drain

### ISSUE THREAD

**Issue by grillo78** [MrCrayfish/MrCrayfishVehicleMod#74]
If the vehicle is turned off with the key and you are inside of the vehicle, the fuel doesn't stop to go down.

**Comment by Macintosh-Fan** [comment]
@grillo78 I tested that just now in survival mode. I think the issue you are talking about might not be the case anymore. But if I am wrong, here are some ideas:
• When your engine is on and you are sitting on the vehicle, it does drain the fuel, to stop the fuel drain, you can hop off the vehicle or take out the key if you have one paired to the vehicle.
• When I tested the key staying in the engine when I was off the vehicle, I gave it a few seconds and the fuel does not seem to drain while I hopped off the vehicle

That is my idea!

**Comment by Elvarion** [comment]
vehicle-0.41.0-mc1.12.2
Using a key on a vehicle and then removing the key will still cause the vehicle to consume fuel even if you cant drive it. So people can jump on your vehicle and spend all fuel (Sure its slow, but still)

**Comment by MrCrayfish** [comment]
Fixed recently. Download the latest version
