### ISSUE TITLE
My server continues to crash

### ISSUE THREAD

**Issue by ChubbyCats22** [MrCrayfish/MrCrayfishVehicleMod#75]
I left a report 2 days ago (#73) and it was closed. He said on the patch page that he fixed it but idk how to get the patch because my server is still crashing. Is the patch coming? Is there a special way to get it?

**Comment by JacksonPlayz** [comment]
Patch will come out whenever the new update comes out.

**Comment by MrCrayfish** [comment]
You have to wait till the update is released. It is technically fixed, just not released.
