### ISSUE TITLE
Hitting a cactus destroys vehicles.

### ISSUE THREAD

**Issue by technomancer21** [MrCrayfish/MrCrayfishVehicleMod#79]
Not sure if bug or intended, but I ran into a cactus and my vehicle broke and despawned. 
I know cacti are meant to destroy that which comes in contact with them, but a functioning vehicle with a diamond engine seems a bit expensive to simply lose it to a cactus on a long drive.

**Comment by MrCrayfish** [comment]
Vehicle destruction is being refactored soon!
