### ISSUE TITLE
[VehicleMod v0.12] Water Vehicles Coloring Issue on Multiplayer Servers

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishVehicleMod#9]
The Jet Skis are losing their color sometimes on multiplayer and appearing all white. It's a similar issue that we had with the ATVs a few weeks ago on 0.8.0. It doesn't happen all the time, but it seems to happen about 25% of the time.

**Comment by MrCrayfish** [comment]
Thanks. Should have a fix out soon!
