### ISSUE TITLE
Mini Biki doesn't render on jack

### ISSUE THREAD

**Issue by ionutsoran** [MrCrayfish/MrCrayfishVehicleMod#90]
The Mini Bike doesn't render when placed on the jack block, all the other vehicles work just fine. And also the jack is easily broken with just one left click.
And sometimes when i hit a mob the car just vanishes. For example I hit a horse with the off roader and the off roader vanished. I was with a player in the vehicle when that happened.
Hopefully you can look into this. Thanks!

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/59df3dd1f457a9e608e07dfbc7729ab7d87fa5f2
