### ISSUE TITLE
When I try to fuel the ATV, I get put in the seat.

### ISSUE THREAD

**Issue by JustProGit** [MrCrayfish/MrCrayfishVehicleMod#92]
I'm trying to fuel the ATV and I left-click on the fuel port, but it just puts me in the seat. I tried shift left-clicking, it picks up the ATV. I tried right clicking, hurts the ATV. I tried shift right-clicking, same thing.

**Comment by JustProGit** [comment]
I got this fixed. It was actually my Mouse that had a broken right click, where it would register as another key. Long story..

**Comment by MrCrayfish** [comment]
Glad you figured it out 😂
