### ISSUE TITLE
Can't open crate.

### ISSUE THREAD

**Issue by JMBA92** [MrCrayfish/MrCrayfishVehicleMod#93]
Nothing happens when i use the wrench on the vehicle crates.
It's in a server.

**Comment by MrCrayfish** [comment]
Are you right clicking the top of the vehicle crate with the wrench? Is the area around the block empty space or blocks without any collision?

**Comment by JMBA92** [comment]
Yes i did it all right. And in the inventory it dos not say whats in the crate. So i went in till cretive and got the material back and did it again. And now i ses i have o off-roader. And then same. So I cheated back the material again. Then I placed the create in cretive and it opens when I placed it. That is not god on my server.

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by MrCrayfish** [comment]
If it doesn't say what it is in the inventory, it will not open. I'm not sure how that happened. Did you happen to craft the vehicle then straight away try to open it? Can you describe exactly what you did so I can identify if there is a problem.

**Comment by JMBA92** [comment]
I Went into my garage to Craft the off-roader got the crate pop out off the crafting block. Dont remender what its calld. Went outside (ca 20 blocks) and placed it on the road. 8 blocks to the closest block.

And sorry for my English. I can read just fine.

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows 10

________________________________
Från: MrCrayfish <notifications@github.com>
Skickat: Wednesday, February 13, 2019 1:01:58 PM
Till: MrCrayfish/MrCrayfishVehicleMod
Kopia: JMBA92; Author
Ämne: Re: [MrCrayfish/MrCrayfishVehicleMod] Can't open crate. (#93)


If it doesn't say what it is in the inventory, it will not open. I'm not sure how that happened. Did you happen to craft the vehicle then straight away try to open it? Can you describe exactly what you did so I can identify if there is a problem.

**Comment by MrCrayfish** [comment]
I'm not exactly sure how the problem occurred. If it happens again, let me know. All I can say is that you make sure you have the latest version of the Vehicle Mod. If you have it on a server too, make sure that is updated also.
