### ISSUE TITLE
Crash with sports-plane

### ISSUE THREAD

**Issue by lays24mc** [MrCrayfish/MrCrayfishVehicleMod#95]
Hi,

i have a crash when i use the sports plane on my Server. Here my crashlog: https://pastebin.com/6j042ke9

forge-1.12.2-14.23.5.2784
vehicle-mod-0.35.0-1.12.2
obfuscate-0.2.6-1.12.2

**Comment by MrCrayfish** [comment]
Can you confirm this on the latest version of the mod? 0.36+

**Comment by MrCrayfish** [comment]
Also duplicate issue #21
