### ISSUE TITLE
Crash on servers with v0.36

### ISSUE THREAD

**Issue by Koopamillion** [MrCrayfish/MrCrayfishVehicleMod#96]
https://pastebin.com/hv790bV2

Dosent crash with v0.35

**Comment by kreezxil** [comment]
confirmed
--

 0.36.0-1.12.2 crashes dedicated server Forge 1.12.2 build 2815

Notes:
     appears to be looking for client side classes

crash report:
http://paste.ubuntu.com/p/Njsx8QXDNF/

fml server latest:
http://paste.ubuntu.com/p/N4xHkP2sBJ/

**Comment by RenanVieira88** [comment]
Confirmed too

**Comment by agentwolf88** [comment]
https://paste.ee/p/3e3VY

**Comment by MrCrayfish** [comment]
Fixed in 0.36.1
