### ISSUE TITLE
Server Crash On V0.36 and V0.35

### ISSUE THREAD

**Issue by uyghuy** [MrCrayfish/MrCrayfishVehicleMod#97]
First of all I understand that you probably don't care about another GitHub user complaining that the mod won't work on his server. So i do thank you for your time.

There is a Problem V0.36 Causing The Server To Crash When Launched. See The Crash Report Below. I Have Tried Seeing If Any Other Mods Are Causing The Issue But Even With Only The Vehicle Mod And Obfusucate. 

[Vehicle Mod V0.36 Crash Report.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/2888973/Vehicle.Mod.V0.36.Crash.Report.txt)

There Is Also A Problem With V0.35 Causing The Server World To Crash And The World To Corrupt When You Spawn In The Sports Plane. But This Is A Minor Problem As It Is With An Older Version Of The Mod.

Once Again I Thank You For Your Time. And I Do Want To Say That I Think All of Your Mods Are AMAZING Weather They Work On Servers Or Not.

**Comment by fabbe50** [comment]
Can confirm. 

https://pastebin.com/qFyyVsmh

**Comment by fabbe50** [comment]
#96

**Comment by agentwolf88** [comment]
https://paste.ee/p/3e3VY

**Comment by MrCrayfish** [comment]
Fixed in latest release
